# Generated by Django 4.2.7 on 2025-09-13 07:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('user_type', models.CharField(choices=[('individual', 'Osoba'), ('company', 'Firma'), ('school', 'Škola')], default='individual', max_length=20, verbose_name='Typ používateľa')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefón')),
                ('bio', models.TextField(blank=True, verbose_name='O mne')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profilová fotka')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokalita')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Názov firmy/školy')),
                ('website', models.URLField(blank=True, verbose_name='Webstránka')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Overený')),
                ('is_public', models.BooleanField(default=True, verbose_name='Verejný profil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Používateľ',
                'verbose_name_plural': 'Používatelia',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_communication', models.CharField(choices=[('online', 'Online'), ('offline', 'Osobne'), ('both', 'Oboje')], default='both', max_length=20, verbose_name='Preferovaná komunikácia')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email notifikácie')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notifikácie')),
                ('show_email', models.BooleanField(default=False, verbose_name='Zobraziť email')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Zobraziť telefón')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil používateľa',
                'verbose_name_plural': 'Profily používateľov',
            },
        ),
    ]
