# Generated by Django 4.2.7 on 2025-09-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Názov firmy'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Osoba'), ('company', 'Firma')], default='individual', max_length=20, verbose_name='Typ používateľa'),
        ),
    ]
