# Generated by Django 4.2.7 on 2025-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_company_name_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dátum narodenia'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Iné'), ('prefer_not_to_say', 'Nepreferujem uviesť')], max_length=20, verbose_name='Pohlavie'),
        ),
    ]
