# Generated by Django 4.2.7 on 2025-09-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_date_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Iné')], max_length=20, verbose_name='Pohlavie'),
        ),
    ]
