# Generated by Django 5.2.4 on 2025-09-17 11:43

import swaply.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[swaply.validators.validate_image_file], verbose_name='Profilová fotka'),
        ),
    ]
