# Generated by Django 4.2.7 on 2025-10-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_job_title'),
    ]

    operations = [
    ]
