# Generated by Django 4.2.7 on 2025-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20251015_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title_visible',
            field=models.BooleanField(default=False, verbose_name='Zobraziť profesiu verejne'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_visible',
            field=models.BooleanField(default=False, verbose_name='Zobraziť telefón verejne'),
        ),
    ]
