# Generated by Django 4.2.7 on 2025-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_job_title_visible_user_phone_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kontaktný email'),
        ),
    ]
