# Generated by Django 4.2.7 on 2025-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_websites',
            field=models.JSONField(blank=True, default=list, verbose_name='Dodatočné webstránky'),
        ),
    ]
