# Generated by Django 4.2.7 on 2025-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_additional_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ico',
            field=models.CharField(blank=True, max_length=14, verbose_name='IČO'),
        ),
        migrations.AddField(
            model_name='user',
            name='ico_visible',
            field=models.BooleanField(default=False, verbose_name='Zobraziť IČO verejne'),
        ),
    ]
