# Generated by Django 4.2.7 on 2025-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_ico_user_ico_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, max_length=64, verbose_name='Kategória'),
        ),
    ]
