# Generated by Django 4.2.7 on 2025-10-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category_sub',
            field=models.CharField(blank=True, max_length=64, verbose_name='Podkategória'),
        ),
    ]
