# Generated by Django 4.2.7 on 2025-11-05 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_category_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Kategória')),
                ('subcategory', models.CharField(max_length=100, verbose_name='Podkategória')),
                ('description', models.TextField(blank=True, max_length=75, verbose_name='Popis')),
                ('experience_value', models.FloatField(blank=True, null=True, verbose_name='Hodnota dĺžky praxe')),
                ('experience_unit', models.CharField(blank=True, choices=[('years', 'Roky'), ('months', 'Mesiace')], max_length=10, verbose_name='Jednotka dĺžky praxe')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tagy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ponúkaná zručnosť',
                'verbose_name_plural': 'Ponúkané zručnosti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='offeredskill',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'subcategory'), name='unique_user_skill_category'),
        ),
    ]
