# Generated by Django 4.2.7 on 2025-11-09 16:38

from django.db import migrations, models
import django.db.models.deletion
import swaply.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_offeredskill_offeredskill_unique_user_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedSkillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='offers/', validators=[swaply.validators.validate_image_file], verbose_name='Obrázok')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Poradie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.offeredskill')),
            ],
            options={
                'verbose_name': 'Obrázok ponuky',
                'verbose_name_plural': 'Obrázky ponúk',
                'ordering': ['order', 'id'],
            },
        ),
    ]
