# Generated by Django 4.2.7 on 2025-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_offeredskillimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='price_currency',
            field=models.CharField(blank=True, default='€', max_length=8, verbose_name='Mena'),
        ),
        migrations.AddField(
            model_name='offeredskill',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena od'),
        ),
    ]
