# Generated by Django 4.2.7 on 2025-11-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_offeredskill_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1200, verbose_name='Podrobný popis'),
        ),
        migrations.AlterField(
            model_name='offeredskill',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Popis'),
        ),
    ]
