# Generated by Django 4.2.7 on 2025-11-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_offeredskill_detailed_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredskill',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Podrobný popis'),
        ),
    ]
