# Generated by Django 4.2.7 on 2025-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_offeredskill_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Otváracia doba'),
        ),
    ]
