# Generated by Django 4.2.7 on 2025-11-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_opening_hours_to_offered_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Okres'),
        ),
    ]
