# Generated by Django 4.2.7 on 2025-12-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_district_to_offeredskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=25, verbose_name='Lokalita'),
        ),
    ]
