# Generated by Django 4.2.7 on 2025-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_change_phone_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredskill',
            name='location',
            field=models.CharField(blank=True, max_length=35, verbose_name='Miesto'),
        ),
    ]
