# Generated by Django 4.2.7 on 2025-12-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_change_offered_skill_location_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='is_seeking',
            field=models.BooleanField(default=False, help_text='True ak používateľ hľadá službu, False ak ponúka', verbose_name='Hľadám'),
        ),
    ]
