# Generated by Django 4.2.7 on 2025-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_urgency_to_offered_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeredskill',
            name='urgency',
            field=models.CharField(choices=[('low', 'Nízka'), ('medium', 'Stredná'), ('high', 'Vysoká')], default='low', help_text='Miera urgentnosti dopytu alebo ponuky', max_length=10, verbose_name='Urgentnosť'),
        ),
    ]
