# Generated by Django 4.2.7 on 2025-12-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_change_urgency_default_to_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('one_time', 'Jednorazovo'), ('long_term', 'Dlhodobo'), ('project', 'Zákazka')], help_text='Typ trvania služby', max_length=20, null=True, verbose_name='Trvanie'),
        ),
    ]
