# Generated by Django 4.2.7 on 2025-12-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_duration_type_to_offered_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Okres'),
        ),
    ]
