# Generated by Django 4.2.7 on 2026-01-12 16:30

import re
import unicodedata
from django.db import migrations


def generate_slug_for_user(user):
    """
    Vygeneruje slug pre používateľa (rovnaká logika ako v User._generate_base_slug)
    """
    # Získať display_name alebo username
    if user.user_type == 'individual':
        name = f"{user.first_name or ''} {user.last_name or ''}".strip()
    else:
        name = user.company_name or ''
    
    if not name:
        name = user.username or ''
    
    if not name:
        name = str(user.pk)
    
    # Odstrániť diakritiku
    normalized = unicodedata.normalize('NFKD', name)
    ascii_str = ''.join(ch for ch in normalized if unicodedata.category(ch) != 'Mn')
    value = ascii_str.lower()
    
    # Medzery -> bodky
    value = re.sub(r'\s+', '.', value)
    # Povolené len a-z, 0-9, bodka, pomlčka
    value = re.sub(r'[^a-z0-9\.-]+', '', value)
    # Zhluk bodiek/pomlčiek zjednotiť
    value = re.sub(r'\.{2,}', '.', value)
    value = re.sub(r'-{2,}', '-', value)
    # Odstrániť bodky/pomlčky na kraji
    value = value.strip('.-')
    
    return value or 'user'


def generate_slugs_for_existing_users(apps, schema_editor):
    """
    Vygeneruje slug pre všetkých používateľov, ktorí ho nemajú
    """
    User = apps.get_model('accounts', 'User')
    
    users_without_slug = User.objects.filter(slug__isnull=True) | User.objects.filter(slug='')
    
    for user in users_without_slug:
        base_slug = generate_slug_for_user(user)
        slug = base_slug
        idx = 1
        
        # Skontrolovať unikátnosť a pridať príponu ak je potrebné
        while User.objects.filter(slug=slug).exclude(pk=user.pk).exists():
            slug = f"{base_slug}-{idx}"
            idx += 1
            if idx > 50:
                # Fallback v extrémnom prípade kolízií
                slug = f"user-{user.pk}"
                break
        
        user.slug = slug
        user.save(update_fields=['slug'])


def reverse_generate_slugs(apps, schema_editor):
    """
    Revert funkcia - odstráni slug (nastaví na null)
    """
    User = apps.get_model('accounts', 'User')
    # Necháme slug tak, ako je - revert nie je potrebný


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_add_name_modified_by_user'),
    ]

    operations = [
        migrations.RunPython(
            generate_slugs_for_existing_users,
            reverse_generate_slugs,
        ),
    ]
