# Generated by Django 4.2.7 on 2026-01-16 16:21

from django.db import migrations, models
import swaply.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_generate_slugs_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskillimage',
            name='moderation_error',
            field=models.TextField(blank=True, null=True, verbose_name='Chyba moderácie'),
        ),
        migrations.AddField(
            model_name='offeredskillimage',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Čaká na kontrolu'), ('approved', 'Schválené'), ('rejected', 'Zamietnuté')], default='pending', help_text='Stav moderácie obsahu obrázka', max_length=20, verbose_name='Stav moderácie'),
        ),
        migrations.AlterField(
            model_name='offeredskillimage',
            name='image',
            field=models.ImageField(upload_to='offers/', validators=[swaply.validators.validate_image_file], verbose_name='Obrázok'),
        ),
    ]
