# Generated by Django 4.2.7 on 2026-01-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_add_moderation_status_to_offeredskillimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeredskillimage',
            name='moderation_error',
        ),
        migrations.RemoveField(
            model_name='offeredskillimage',
            name='moderation_status',
        ),
    ]
