# Generated by Django 4.2.7 on 2026-01-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_moderation_status_from_offeredskillimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredskill',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Ak je True, karta sa nezobrazí vo vyhľadávaní ani na cudzích profiloch', verbose_name='Skrytá'),
        ),
    ]
