# Generated by Django 4.2.7 on 2026-01-19 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_add_is_hidden_to_offered_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Čaká na odpoveď'), ('accepted', 'Prijaté'), ('rejected', 'Zamietnuté'), ('cancelled', 'Zrušené')], default='pending', max_length=20, verbose_name='Stav')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requests', to='accounts.offeredskill', verbose_name='Karta')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_skill_requests', to=settings.AUTH_USER_MODEL, verbose_name='Príjemca')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_skill_requests', to=settings.AUTH_USER_MODEL, verbose_name='Odosielateľ')),
            ],
            options={
                'verbose_name': 'Žiadosť o kartu',
                'verbose_name_plural': 'Žiadosti o kartu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('skill_request', 'Nová žiadosť'), ('skill_request_accepted', 'Žiadosť prijatá'), ('skill_request_rejected', 'Žiadosť zamietnutá'), ('skill_request_cancelled', 'Žiadosť zrušená')], max_length=50, verbose_name='Typ')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='Názov')),
                ('body', models.TextField(blank=True, default='', verbose_name='Text')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dáta')),
                ('is_read', models.BooleanField(default=False, verbose_name='Prečítané')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Prečítané o')),
                ('skill_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.skillrequest', verbose_name='Žiadosť')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Notifikácia',
                'verbose_name_plural': 'Notifikácie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='skillrequest',
            index=models.Index(fields=['recipient', 'status', 'created_at'], name='accounts_sk_recipie_9a5f67_idx'),
        ),
        migrations.AddIndex(
            model_name='skillrequest',
            index=models.Index(fields=['requester', 'status', 'created_at'], name='accounts_sk_request_75487b_idx'),
        ),
        migrations.AddIndex(
            model_name='skillrequest',
            index=models.Index(fields=['offer', 'created_at'], name='accounts_sk_offer_i_9d79af_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillrequest',
            constraint=models.UniqueConstraint(fields=('requester', 'offer'), name='unique_skill_request_per_requester_offer'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='accounts_no_user_id_cabb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type', 'is_read'], name='accounts_no_user_id_b0984b_idx'),
        ),
    ]
