# Generated by Django 4.2.7 on 2026-02-12 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_skillrequest_hide_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Hodnotenie od 0.0 do 5.0 v krokoch 0.5', max_digits=3, verbose_name='Hodnotenie')),
                ('text', models.TextField(blank=True, default='', max_length=300, verbose_name='Text recenzie')),
                ('pros', models.JSONField(blank=True, default=list, help_text='Zoznam plusov (max 10 položiek)', verbose_name='Plusy')),
                ('cons', models.JSONField(blank=True, default=list, help_text='Zoznam minusov (max 10 položiek)', verbose_name='Minusy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.offeredskill', verbose_name='Ponuka')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Recenzent')),
            ],
            options={
                'verbose_name': 'Recenzia',
                'verbose_name_plural': 'Recenzie',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer', 'created_at'], name='accounts_re_offer_i_551ae4_idx'), models.Index(fields=['reviewer', 'created_at'], name='accounts_re_reviewe_84276e_idx'), models.Index(fields=['rating', 'created_at'], name='accounts_re_rating_0603b6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'offer'), name='unique_review_per_reviewer_offer'),
        ),
    ]
