# Generated by Django 4.2.7 on 2026-02-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_add_review_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner_responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Odpoveď vlastníka dňa"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="owner_response",
            field=models.TextField(
                blank=True,
                max_length=700,
                null=True,
                verbose_name="Odpoveď vlastníka ponuky",
            ),
        ),
    ]
