# Generated by Django 4.2.7 on 2026-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_add_skill_request_completion_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mfa_secret",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="2FA TOTP secret"
            ),
        ),
    ]
