# Generated by Django 4.2.7 on 2026-02-25 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_increase_mfa_secret_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100, verbose_name="Dôvod")),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Vyriešené"),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nahlásil",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.review",
                        verbose_name="Recenzia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nahlásenie recenzie",
                "verbose_name_plural": "Nahlásenia recenzií",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reviewreport",
            constraint=models.UniqueConstraint(
                fields=("review", "reported_by"), name="unique_review_report_per_user"
            ),
        ),
    ]
