# Generated by Django 4.2.7 on 2026-02-25 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_add_review_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100, verbose_name="Dôvod")),
                ("description", models.TextField(blank=True, verbose_name="Popis")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Vyriešené"),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nahlásil",
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Nahlásený používateľ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nahlásenie používateľa",
                "verbose_name_plural": "Nahlásenia používateľov",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.UniqueConstraint(
                fields=("reported_user", "reported_by"),
                name="unique_user_report_per_reporter",
            ),
        ),
        migrations.AddConstraint(
            model_name="userreport",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("reported_user", models.F("reported_by")), _negated=True
                ),
                name="user_report_cannot_report_self",
            ),
        ),
    ]
