# Generated by Django 4.2.7 on 2026-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_add_user_report"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="offeredskill",
            index=models.Index(fields=["created_at"], name="acc_off_skill_created_idx"),
        ),
        migrations.AddIndex(
            model_name="offeredskill",
            index=models.Index(fields=["district"], name="acc_off_skill_district_idx"),
        ),
        migrations.AddIndex(
            model_name="offeredskill",
            index=models.Index(fields=["price_from"], name="acc_off_skill_price_idx"),
        ),
        migrations.AddIndex(
            model_name="offeredskill",
            index=models.Index(
                fields=["is_hidden", "-created_at"], name="acc_off_skill_hidden_new_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offeredskill",
            index=models.Index(
                fields=["is_hidden", "is_seeking", "-created_at"],
                name="acc_off_skill_type_new_idx",
            ),
        ),
    ]
