# Generated by Django 4.2.7 on 2026-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_add_offeredskill_search_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_email_visible",
            field=models.BooleanField(
                default=False, verbose_name="Zobraziť kontaktný email verejne"
            ),
        ),
    ]
