# Generated by Django 4.2.7 on 2026-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_add_contact_email_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeredskillimage",
            name="approved_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="S3 kľúč (approved)",
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="content_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Content-Type"
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="height",
            field=models.IntegerField(blank=True, null=True, verbose_name="Výška"),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="original_filename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Pôvodný názov súboru",
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="pending_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="S3 kľúč (pending)",
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Spracované o"
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="rejected_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Dôvod zamietnutia"
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="size_bytes",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Veľkosť (bytes)"
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Čaká na spracovanie"),
                    ("approved", "Schválené"),
                    ("rejected", "Zamietnuté"),
                ],
                default="approved",
                help_text="PENDING/REJECTED sa používajú pri asynchrónnom spracovaní obrázkov.",
                max_length=20,
                verbose_name="Stav",
            ),
        ),
        migrations.AddField(
            model_name="offeredskillimage",
            name="width",
            field=models.IntegerField(blank=True, null=True, verbose_name="Šírka"),
        ),
        migrations.AddIndex(
            model_name="offeredskillimage",
            index=models.Index(
                fields=["skill", "status", "order", "id"],
                name="acc_offer_img_skill_status_idx",
            ),
        ),
    ]
