# Generated by Django 4.2.7 on 2026-03-17 12:08

from django.db import migrations, models
import swaply.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_offeredskillimage_approved_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeredskillimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="offers/",
                validators=[swaply.validators.validate_image_file],
                verbose_name="Obrázok",
            ),
        ),
    ]
