# Generated by Django 4.2.7 on 2026-03-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_alter_offeredskillimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_email_visible",
            field=models.BooleanField(
                default=True, verbose_name="Zobraziť kontaktný email verejne"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ico_visible",
            field=models.BooleanField(
                default=True, verbose_name="Zobraziť IČO verejne"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title_visible",
            field=models.BooleanField(
                default=True, verbose_name="Zobraziť profesiu verejne"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_visible",
            field=models.BooleanField(
                default=True, verbose_name="Zobraziť telefón verejne"
            ),
        ),
    ]
