# Generated by Django 4.2.7 on 2026-03-26

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0054_dashboard_skill_search_projection"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="skillrequest",
            name="unique_skill_request_per_requester_offer",
        ),
        migrations.AddConstraint(
            model_name="skillrequest",
            constraint=models.UniqueConstraint(
                fields=("requester", "offer"),
                condition=Q(status__in=("pending", "accepted", "completion_requested")),
                name="unique_skill_request_per_requester_offer",
            ),
        ),
    ]

