# Generated by Django 4.2.7 on 2026-03-31 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_skillrequest_unique_active_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Hash endpointu"
                    ),
                ),
                (
                    "endpoint_encrypted",
                    models.TextField(verbose_name="Zašifrovaný endpoint"),
                ),
                (
                    "p256dh_encrypted",
                    models.TextField(verbose_name="Zašifrovaný p256dh kľúč"),
                ),
                (
                    "auth_encrypted",
                    models.TextField(verbose_name="Zašifrovaný auth kľúč"),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "device_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Označenie zariadenia",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Aktívna subscription"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Naposledy videné",
                    ),
                ),
                (
                    "last_success_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Naposledy úspešne odoslané"
                    ),
                ),
                (
                    "last_failure_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Naposledy zlyhalo odoslanie",
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Počet zlyhaní"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizované"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webpush_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Používateľ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web push subscription",
                "verbose_name_plural": "Web push subscriptions",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="acc_wps_user_act_idx"
                    ),
                    models.Index(
                        fields=["is_active", "last_seen_at"], name="acc_wps_seen_idx"
                    ),
                ],
            },
        ),
    ]
