# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_webpushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeredskill",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=2, verbose_name="Krajina"),
        ),
        migrations.AddField(
            model_name="offeredskill",
            name="district_code",
            field=models.CharField(blank=True, default="", max_length=80, verbose_name="Kód okresu"),
        ),
        migrations.AddIndex(
            model_name="offeredskill",
            index=models.Index(fields=["country_code"], name="acc_off_skill_country_idx"),
        ),
    ]
