# Generated by Codex on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_offeredskill_country_district_codes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="VytvorenÃ©"),
                ),
                (
                    "favorite_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by_users",
                        to="accounts.user",
                        verbose_name="ObÄ¾ÃºbenÃ½ pouÅ¾Ã­vateÄ¾",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_users",
                        to="accounts.user",
                        verbose_name="PouÅ¾Ã­vateÄ¾",
                    ),
                ),
            ],
            options={
                "verbose_name": "ObÄ¾ÃºbenÃ½ pouÅ¾Ã­vateÄ¾",
                "verbose_name_plural": "ObÄ¾ÃºbenÃ­ pouÅ¾Ã­vatelia",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="favoriteuser",
            constraint=models.UniqueConstraint(
                fields=("user", "favorite_user"),
                name="unique_favorite_user_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteuser",
            constraint=models.CheckConstraint(
                check=~models.Q(user=models.F("favorite_user")),
                name="favorite_user_cannot_point_to_self",
            ),
        ),
        migrations.AddIndex(
            model_name="favoriteuser",
            index=models.Index(
                fields=["user", "created_at"],
                name="acc_fav_user_owner_created_idx",
            ),
        ),
    ]
