# Generated by Django 4.2.7 on 2026-05-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0068_skillrequest_termination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("offer_liked", "Páči sa mi ponuka"),
                    ("skill_request", "Nová žiadosť"),
                    ("skill_request_accepted", "Žiadosť prijatá"),
                    (
                        "skill_request_completion_requested",
                        "Výmena označená ako dokončená",
                    ),
                    ("skill_request_completed", "Dokončenie výmeny potvrdené"),
                    ("review_created", "Nová recenzia"),
                    ("review_reply_created", "Odpoveď na recenziu"),
                    ("review_liked", "Páči sa mi recenzia"),
                    ("skill_request_rejected", "Žiadosť zamietnutá"),
                    ("skill_request_cancelled", "Žiadosť zrušená"),
                    ("skill_request_terminated", "Výmena skončila"),
                    ("group_invitation", "Pozvánka do skupiny"),
                ],
                max_length=50,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="skillrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Čaká na odpoveď"),
                    ("accepted", "Prijaté"),
                    ("rejected", "Zamietnuté"),
                    ("cancelled", "Zrušené"),
                    ("completion_requested", "Completion requested"),
                    ("completed", "Completed"),
                    ("terminated", "Predčasne ukončené"),
                ],
                default="pending",
                max_length=25,
                verbose_name="Stav",
            ),
        ),
    ]
