# Generated by Cursor on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0069_alter_notification_type_alter_skillrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium")],
                db_index=True,
                default="free",
                max_length=20,
                verbose_name="Subscription tier",
            ),
        ),
    ]
