# Generated by Cursor on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0070_user_subscription_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="offeredskill",
            name="price_negotiable",
            field=models.BooleanField(default=False, verbose_name="Cena dohodou"),
        ),
    ]
