# Generated by Django 5.2.15 on 2026-07-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_rename_email_to_in_app_notifications'),
        ('messaging', '0014_alter_message_image_alter_message_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrequest',
            name='proposal_description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Opis pomoci'),
        ),
        migrations.AlterField(
            model_name='skillrequesttermination',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Popis'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'created_at'], name='accounts_no_type_61275d_idx'),
        ),
    ]
