# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0089_notification_portfolio_liked_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                (
                    "profile_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_likes_received",
                        to="accounts.user",
                        verbose_name="Liked profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_likes_given",
                        to="accounts.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile like",
                "verbose_name_plural": "Profile likes",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="profilelike",
            constraint=models.UniqueConstraint(
                fields=("profile_user", "user"),
                name="unique_profile_like_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilelike",
            constraint=models.CheckConstraint(
                check=~models.Q(profile_user=models.F("user")),
                name="profile_like_cannot_point_to_self",
            ),
        ),
        migrations.AddIndex(
            model_name="profilelike",
            index=models.Index(
                fields=["profile_user", "created_at"],
                name="acc_plike_profile_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profilelike",
            index=models.Index(
                fields=["user", "created_at"],
                name="acc_plike_user_cr_idx",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("offer_liked", "Páči sa mi ponuka"),
                    ("portfolio_liked", "Paci sa mi portfolio"),
                    ("profile_liked", "Paci sa mi profil"),
                    ("skill_request", "Nová žiadosť"),
                    ("skill_request_accepted", "Žiadosť prijatá"),
                    ("skill_request_completion_requested", "Výmena označená ako dokončená"),
                    ("skill_request_completed", "Dokončenie výmeny potvrdené"),
                    ("review_created", "Nová recenzia"),
                    ("review_reply_created", "Odpoveď na recenziu"),
                    ("review_liked", "Páči sa mi recenzia"),
                    ("skill_request_rejected", "Žiadosť zamietnutá"),
                    ("skill_request_cancelled", "Žiadosť zrušená"),
                    ("skill_request_terminated", "Výmena skončila"),
                    ("group_invitation", "Pozvánka do skupiny"),
                ],
                max_length=50,
                verbose_name="Typ",
            ),
        ),
    ]
