# Generated by Codex on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0090_profilelike_notification_profile_liked_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "blocked_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_blocks_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocked user",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_blocks_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Blocker",
                    ),
                ),
            ],
            options={
                "verbose_name": "User block",
                "verbose_name_plural": "User blocks",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="userblock",
            constraint=models.UniqueConstraint(
                fields=("blocker", "blocked_user"),
                name="unique_user_block",
            ),
        ),
        migrations.AddConstraint(
            model_name="userblock",
            constraint=models.CheckConstraint(
                check=~models.Q(blocker=models.F("blocked_user")),
                name="user_block_cannot_target_self",
            ),
        ),
        migrations.AddIndex(
            model_name="userblock",
            index=models.Index(
                fields=["blocker", "-created_at", "-id"],
                name="acc_ub_blocker_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userblock",
            index=models.Index(
                fields=["blocked_user", "blocker"],
                name="acc_ub_blocked_by_idx",
            ),
        ),
    ]
