# Generated by Django 5.2.15 on 2026-07-27 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_backfill_review_reviewed_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='Visit date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits_received', to=settings.AUTH_USER_MODEL, verbose_name='Visited profile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits_made', to=settings.AUTH_USER_MODEL, verbose_name='Viewer')),
            ],
            options={
                'verbose_name': 'Profile visit',
                'verbose_name_plural': 'Profile visits',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['profile_user', 'visit_date'], name='acc_pvisit_profile_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile_user', 'viewer', 'visit_date'), name='unique_profile_visit_per_day'), models.CheckConstraint(check=~models.Q(profile_user=models.F('viewer')), name='profile_visit_cannot_point_to_self')],
            },
        ),
    ]
