# Generated by Django 4.2.7 on 2026-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_profilevisit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profilevisit',
            index=models.Index(fields=['created_at'], name='acc_pvisit_created_idx'),
        ),
    ]
