# Generated by Django 4.2.7 on 2026-07-29 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_profilevisit_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Verejné ID')),
                ('category', models.CharField(choices=[('not_working', 'Niečo nefunguje'), ('visual', 'Problém so vzhľadom'), ('performance', 'Aplikácia je pomalá alebo spadla'), ('other', 'Iný problém')], max_length=20, verbose_name='Kategória')),
                ('title', models.CharField(max_length=120, verbose_name='Názov')),
                ('description', models.TextField(max_length=2000, verbose_name='Popis')),
                ('reproduction_steps', models.TextField(blank=True, default='', max_length=2000, verbose_name='Postup zopakovania')),
                ('source_screen', models.CharField(blank=True, default='', max_length=64, verbose_name='Zdrojová obrazovka')),
                ('device_type', models.CharField(choices=[('unknown', 'Neznáme'), ('mobile', 'Mobil'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], default='unknown', max_length=16, verbose_name='Typ zariadenia')),
                ('locale', models.CharField(blank=True, default='', max_length=10, verbose_name='Jazyk aplikácie')),
                ('app_version', models.CharField(blank=True, default='', max_length=64, verbose_name='Verzia aplikácie')),
                ('browser', models.CharField(blank=True, default='', max_length=64, verbose_name='Prehliadač')),
                ('status', models.CharField(choices=[('new', 'Nové'), ('triaged', 'Skontrolované'), ('in_progress', 'Rieši sa'), ('resolved', 'Vyriešené'), ('closed', 'Zatvorené')], default='new', max_length=20, verbose_name='Stav')),
                ('priority', models.CharField(choices=[('low', 'Nízka'), ('normal', 'Normálna'), ('high', 'Vysoká'), ('critical', 'Kritická')], default='normal', max_length=16, verbose_name='Priorita')),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Interná poznámka')),
                ('support_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Podpora upozornená')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Vyriešené')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL, verbose_name='Nahlásil')),
            ],
            options={
                'verbose_name': 'Hlásenie chyby',
                'verbose_name_plural': 'Hlásenia chýb',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='acc_bug_status_created_idx'), models.Index(fields=['category', '-created_at'], name='acc_bug_category_created_idx'), models.Index(fields=['reported_by', '-created_at'], name='acc_bug_reporter_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(check=models.Q(('category__in', ['not_working', 'visual', 'performance', 'other'])), name='bug_report_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['new', 'triaged', 'in_progress', 'resolved', 'closed'])), name='bug_report_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ['low', 'normal', 'high', 'critical'])), name='bug_report_priority_valid'),
        ),
        migrations.AddConstraint(
            model_name='bugreport',
            constraint=models.CheckConstraint(check=models.Q(('device_type__in', ['unknown', 'mobile', 'desktop', 'tablet'])), name='bug_report_device_type_valid'),
        ),
    ]
