# Generated by Django 4.2.7 on 2026-07-30

from django.db import migrations, models
import django.db.models.deletion


def create_pending_notification_intents(apps, schema_editor):
    BugReport = apps.get_model("accounts", "BugReport")
    BugReportNotificationOutbox = apps.get_model(
        "accounts",
        "BugReportNotificationOutbox",
    )
    pending_report_ids = BugReport.objects.filter(
        support_notified_at__isnull=True
    ).values_list("id", flat=True)
    intents = []
    for report_id in pending_report_ids.iterator(chunk_size=1000):
        intents.append(BugReportNotificationOutbox(bug_report_id=report_id))
        if len(intents) == 1000:
            BugReportNotificationOutbox.objects.bulk_create(
                intents,
                batch_size=1000,
                ignore_conflicts=True,
            )
            intents.clear()
    if intents:
        BugReportNotificationOutbox.objects.bulk_create(
            intents,
            batch_size=1000,
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0097_bugreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugreport",
            name="app_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Verzia aplikácie v čase odoslania hlásenia.",
                max_length=64,
                verbose_name="Verzia aplikácie",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="browser",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Prehliadač určený klientskou aplikáciou.",
                max_length=64,
                verbose_name="Prehliadač",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="category",
            field=models.CharField(
                choices=[
                    ("not_working", "Niečo nefunguje"),
                    ("visual", "Problém so vzhľadom"),
                    ("performance", "Aplikácia je pomalá alebo spadla"),
                    ("other", "Iný problém"),
                ],
                help_text="Druh problému zvolený používateľom.",
                max_length=20,
                verbose_name="Kategória",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Neznáme"),
                    ("mobile", "Mobil"),
                    ("desktop", "Desktop"),
                    ("tablet", "Tablet"),
                ],
                default="unknown",
                help_text="Typ zariadenia určený klientskou aplikáciou.",
                max_length=16,
                verbose_name="Typ zariadenia",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="locale",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jazyk aplikácie v čase odoslania hlásenia.",
                max_length=10,
                verbose_name="Jazyk aplikácie",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Nízka"),
                    ("normal", "Normálna"),
                    ("high", "Vysoká"),
                    ("critical", "Kritická"),
                ],
                default="normal",
                help_text="Interná priorita spracovania hlásenia.",
                max_length=16,
                verbose_name="Priorita",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="source_screen",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Obrazovka aplikácie, z ktorej bolo hlásenie odoslané.",
                max_length=64,
                verbose_name="Zdrojová obrazovka",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nové"),
                    ("triaged", "Skontrolované"),
                    ("in_progress", "Rieši sa"),
                    ("resolved", "Vyriešené"),
                    ("closed", "Zatvorené"),
                ],
                default="new",
                help_text="Aktuálny stav spracovania hlásenia.",
                max_length=20,
                verbose_name="Stav",
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="title",
            field=models.CharField(
                help_text="Krátky názov problému zadaný používateľom.",
                max_length=120,
                verbose_name="Názov",
            ),
        ),
        migrations.CreateModel(
            name="BugReportNotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bug_report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_outbox",
                        to="accounts.bugreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Čakajúca notifikácia hlásenia chyby",
                "verbose_name_plural": "Čakajúce notifikácie hlásení chýb",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(
            create_pending_notification_intents,
            migrations.RunPython.noop,
        ),
    ]
