# Generated by Django 4.2.7 on 2026-07-30 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolioitem_description'),
        ('accounts', '0099_ensure_bugreport_outbox_claimed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('free_post', 'Voľný príspevok'), ('shared_offer', 'Zdieľaná ponuka'), ('shared_portfolio_item', 'Zdieľané portfólio')], max_length=30, verbose_name='Typ príspevku')),
                ('caption', models.TextField(blank=True, default='', max_length=500, verbose_name='Text')),
                ('image_status', models.CharField(blank=True, choices=[('pending', 'Čaká na spracovanie'), ('approved', 'Schválené'), ('rejected', 'Zamietnuté')], default='', max_length=20, verbose_name='Stav fotky')),
                ('image_pending_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='S3 kľúč (pending)')),
                ('image_approved_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='S3 kľúč (approved)')),
                ('image_thumbnail_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='S3 kľúč (thumbnail)')),
                ('image_original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Pôvodný názov súboru')),
                ('image_content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Content-Type')),
                ('image_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Veľkosť (bytes)')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Šírka')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Výška')),
                ('image_rejected_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Dôvod zamietnutia')),
                ('image_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Spracované o')),
                ('shared_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Snapshot: názov')),
                ('shared_category', models.CharField(blank=True, default='', max_length=100, verbose_name='Snapshot: kategória')),
                ('shared_thumbnail_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='Snapshot: S3 kľúč náhľadu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upravené')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('shared_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_shares', to='accounts.offeredskill', verbose_name='Zdieľaná ponuka')),
                ('shared_portfolio_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_shares', to='portfolio.portfolioitem', verbose_name='Zdieľaná položka portfólia')),
            ],
            options={
                'verbose_name': 'Príspevok na nástenke',
                'verbose_name_plural': 'Príspevky na nástenke',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedPostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Dôvod')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Vyriešené')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.feedpost', verbose_name='Príspevok')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_reports', to=settings.AUTH_USER_MODEL, verbose_name='Nahlásil')),
            ],
            options={
                'verbose_name': 'Nahlásenie príspevku',
                'verbose_name_plural': 'Nahlásenia príspevkov',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.feedpost', verbose_name='Príspevok')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Páči sa mi príspevok',
                'verbose_name_plural': 'Páči sa mi príspevky',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.feedpost', verbose_name='Príspevok')),
            ],
            options={
                'verbose_name': 'Komentár k príspevku',
                'verbose_name_plural': 'Komentáre k príspevkom',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='feedpostreport',
            constraint=models.UniqueConstraint(fields=('post', 'reported_by'), name='unique_feed_post_report_per_user'),
        ),
        migrations.AddIndex(
            model_name='feedpostlike',
            index=models.Index(fields=['post', 'created_at'], name='acc_fplike_post_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpostlike',
            index=models.Index(fields=['user', 'created_at'], name='acc_fplike_user_cr_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedpostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_feed_post_like_per_user'),
        ),
        migrations.AddIndex(
            model_name='feedpostcomment',
            index=models.Index(fields=['post', 'created_at'], name='acc_fpcomm_post_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['author', 'created_at'], name='acc_fpost_author_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['created_at'], name='acc_fpost_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedpost',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post_type', 'free_post'), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True), models.Q(('caption', ''), _negated=True)), models.Q(('image_status', ''), ('post_type', 'shared_offer'), ('shared_portfolio_item__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('image_status', ''), ('post_type', 'shared_portfolio_item'), ('shared_offer__isnull', True), models.Q(('shared_title', ''), _negated=True)), _connector='OR'), name='feed_post_type_consistency'),
        ),
    ]
