# Generated by Django 4.2.7 on 2026-07-31 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_feed_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='shared_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_shares_received', to=settings.AUTH_USER_MODEL, verbose_name='Pôvodný vlastník zdieľaného obsahu'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='shared_owner_display_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Snapshot: meno vlastníka'),
        ),
    ]
