# Generated by Django 4.2.7 on 2026-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_feed_post_shared_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='feedpostcomment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
    ]
