# Generated by Django 4.2.7 on 2026-08-01 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_feed_post_text_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='accounts.feedpost', verbose_name='Príspevok')),
                ('tagged_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_tags', to=settings.AUTH_USER_MODEL, verbose_name='Označený používateľ')),
            ],
            options={
                'verbose_name': 'Označenie v príspevku',
                'verbose_name_plural': 'Označenia v príspevkoch',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tagged_user', 'created_at'], name='acc_fptag_user_cr_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feedposttag',
            constraint=models.UniqueConstraint(fields=('post', 'tagged_user'), name='unique_feed_post_tag_per_user'),
        ),
    ]
