# Generated by Django 4.2.7 on 2026-08-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_feed_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offer_liked', 'Páči sa mi ponuka'), ('portfolio_liked', 'Paci sa mi portfolio'), ('profile_liked', 'Paci sa mi profil'), ('skill_request', 'Nová žiadosť'), ('skill_request_accepted', 'Žiadosť prijatá'), ('skill_request_completion_requested', 'Výmena označená ako dokončená'), ('skill_request_completed', 'Dokončenie výmeny potvrdené'), ('review_created', 'Nová recenzia'), ('review_reply_created', 'Odpoveď na recenziu'), ('review_liked', 'Páči sa mi recenzia'), ('skill_request_rejected', 'Žiadosť zamietnutá'), ('skill_request_cancelled', 'Žiadosť zrušená'), ('skill_request_terminated', 'Výmena skončila'), ('group_invitation', 'Pozvánka do skupiny'), ('feed_post_liked', 'Páči sa mi príspevok'), ('feed_post_commented', 'Komentár k príspevku')], max_length=50, verbose_name='Typ'),
        ),
    ]
