# Generated by Django 4.2.7 on 2026-08-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_feed_tagged_notification_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedpost',
            name='feed_post_type_consistency',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='shared_feed_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reshares', to='accounts.feedpost', verbose_name='Zdieľaný príspevok'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='shared_post_caption',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Snapshot: text príspevku'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='post_type',
            field=models.CharField(choices=[('free_post', 'Voľný príspevok'), ('shared_offer', 'Zdieľaná ponuka'), ('shared_portfolio_item', 'Zdieľané portfólio'), ('shared_feed_post', 'Zdieľaný príspevok')], max_length=30, verbose_name='Typ príspevku'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offer_liked', 'Páči sa mi ponuka'), ('portfolio_liked', 'Paci sa mi portfolio'), ('profile_liked', 'Paci sa mi profil'), ('skill_request', 'Nová žiadosť'), ('skill_request_accepted', 'Žiadosť prijatá'), ('skill_request_completion_requested', 'Výmena označená ako dokončená'), ('skill_request_completed', 'Dokončenie výmeny potvrdené'), ('review_created', 'Nová recenzia'), ('review_reply_created', 'Odpoveď na recenziu'), ('review_liked', 'Páči sa mi recenzia'), ('skill_request_rejected', 'Žiadosť zamietnutá'), ('skill_request_cancelled', 'Žiadosť zrušená'), ('skill_request_terminated', 'Výmena skončila'), ('group_invitation', 'Pozvánka do skupiny'), ('feed_post_liked', 'Páči sa mi príspevok'), ('feed_post_commented', 'Komentár k príspevku'), ('feed_post_tagged', 'Označenie v príspevku'), ('feed_post_shared', 'Zdieľanie príspevku')], max_length=50, verbose_name='Typ'),
        ),
        migrations.AddConstraint(
            model_name='feedpost',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post_type', 'free_post'), ('shared_feed_post__isnull', True), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True), models.Q(('caption', ''), _negated=True)), models.Q(('image_status', ''), ('post_type', 'shared_offer'), ('shared_feed_post__isnull', True), ('shared_portfolio_item__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('image_status', ''), ('post_type', 'shared_portfolio_item'), ('shared_feed_post__isnull', True), ('shared_offer__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('image_status', ''), ('post_type', 'shared_feed_post'), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True)), _connector='OR'), name='feed_post_type_consistency'),
        ),
    ]
