# Generated by Django 4.2.7 on 2026-08-07 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_feed_post_reshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('offer_liked', 'Páči sa mi ponuka'), ('portfolio_liked', 'Paci sa mi portfolio'), ('profile_liked', 'Paci sa mi profil'), ('skill_request', 'Nová žiadosť'), ('skill_request_accepted', 'Žiadosť prijatá'), ('skill_request_completion_requested', 'Výmena označená ako dokončená'), ('skill_request_completed', 'Dokončenie výmeny potvrdené'), ('review_created', 'Nová recenzia'), ('review_reply_created', 'Odpoveď na recenziu'), ('review_liked', 'Páči sa mi recenzia'), ('skill_request_rejected', 'Žiadosť zamietnutá'), ('skill_request_cancelled', 'Žiadosť zrušená'), ('skill_request_terminated', 'Výmena skončila'), ('group_invitation', 'Pozvánka do skupiny'), ('feed_post_liked', 'Páči sa mi príspevok'), ('feed_post_commented', 'Komentár k príspevku'), ('feed_post_tagged', 'Označenie v príspevku'), ('feed_post_shared', 'Zdieľanie príspevku'), ('feed_post_comment_liked', 'Páči sa mi komentár')], max_length=50, verbose_name='Typ'),
        ),
        migrations.CreateModel(
            name='FeedPostCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.feedpostcomment', verbose_name='Komentár')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_post_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Páči sa mi komentár',
                'verbose_name_plural': 'Páči sa mi komentáre',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['comment', 'created_at'], name='acc_fpclike_comm_cr_idx'), models.Index(fields=['user', 'created_at'], name='acc_fpclike_user_cr_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feedpostcommentlike',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_feed_comment_like_per_user'),
        ),
    ]
