# Generated by Django 4.2.7 on 2026-08-09 15:48

from itertools import islice

from django.db import migrations, models
import django.db.models.deletion


def move_images_to_child_table(apps, schema_editor):
    """Prevedie fotku z polí na FeedPost do samostatného FeedPostImage riadku.

    Beží PRED RemoveField, takže staré stĺpce sú ešte k dispozícii. Na prázdnej
    tabuľke (alebo pri príspevkoch bez fotky) je to no-op – prevádza sa len to,
    čo má vyplnený niektorý kľúč alebo status.

    Kľúče sa NEkopírujú v storage, len sa presúva odkaz na ne – súbor v S3
    ostáva ten istý, mení sa iba riadok, ktorý ho vlastní.
    """
    FeedPost = apps.get_model("accounts", "FeedPost")
    FeedPostImage = apps.get_model("accounts", "FeedPostImage")

    legacy = FeedPost.objects.exclude(
        image_status="",
        image_pending_key="",
        image_approved_key="",
        image_thumbnail_key="",
    ).only(
        "id",
        "image_status",
        "image_pending_key",
        "image_approved_key",
        "image_thumbnail_key",
        "image_original_filename",
        "image_content_type",
        "image_size_bytes",
        "image_width",
        "image_height",
        "image_rejected_reason",
        "image_processed_at",
    )

    def to_image(post):
        return FeedPostImage(
            post_id=post.id,
            # Jediná fotka starého modelu je vždy prvá.
            order=0,
            # Prázdny status znamenal „bez fotky"; sem sa dostane len post
            # s vyplneným kľúčom, takže ide o rozpracovaný upload → pending.
            status=post.image_status or "pending",
            pending_key=post.image_pending_key,
            approved_key=post.image_approved_key,
            thumbnail_key=post.image_thumbnail_key,
            original_filename=post.image_original_filename,
            content_type=post.image_content_type,
            size_bytes=post.image_size_bytes,
            width=post.image_width,
            height=post.image_height,
            rejected_reason=post.image_rejected_reason,
            processed_at=post.image_processed_at,
        )

    # Po dávkach, nie naraz: list comprehension nad iterator() by aj tak
    # zmaterializoval VŠETKY inštancie v pamäti naraz – islice drží
    # najviac BATCH_SIZE naraz bez ohľadu na veľkosť tabuľky.
    BATCH_SIZE = 500
    source = (to_image(post) for post in legacy.iterator(chunk_size=BATCH_SIZE))
    while True:
        batch = list(islice(source, BATCH_SIZE))
        if not batch:
            break
        FeedPostImage.objects.bulk_create(batch, batch_size=BATCH_SIZE)


def move_images_back_to_post(apps, schema_editor):
    """Spätný prevod pre `migrate accounts 0107`.

    Starý model uniesol len JEDNU fotku, takže sa berie tá s najnižším order;
    prípadné ďalšie sa do polí nezmestia (a ich storage kľúče by osireli) –
    preto sa tu ZÁMERNE nič nemaže, rollback je best-effort.
    """
    FeedPost = apps.get_model("accounts", "FeedPost")
    FeedPostImage = apps.get_model("accounts", "FeedPostImage")

    for image in FeedPostImage.objects.order_by("post_id", "order", "id").iterator():
        FeedPost.objects.filter(id=image.post_id).exclude(
            image_status__in=("pending", "approved", "rejected")
        ).update(
            image_status=image.status,
            image_pending_key=image.pending_key,
            image_approved_key=image.approved_key,
            image_thumbnail_key=image.thumbnail_key,
            image_original_filename=image.original_filename,
            image_content_type=image.content_type,
            image_size_bytes=image.size_bytes,
            image_width=image.width,
            image_height=image.height,
            image_rejected_reason=image.rejected_reason,
            image_processed_at=image.processed_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0107_feed_post_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Poradie')),
                ('status', models.CharField(choices=[('pending', 'Čaká na spracovanie'), ('approved', 'Schválené'), ('rejected', 'Zamietnuté')], default='pending', max_length=20, verbose_name='Stav')),
                ('pending_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='S3 kľúč (pending)')),
                ('approved_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='S3 kľúč (approved)')),
                ('thumbnail_key', models.CharField(blank=True, default='', max_length=1024, verbose_name='S3 kľúč (thumbnail)')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Pôvodný názov súboru')),
                ('content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Content-Type')),
                ('size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Veľkosť (bytes)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Šírka')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Výška')),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Dôvod zamietnutia')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Spracované o')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
            ],
            options={
                'verbose_name': 'Fotka príspevku',
                'verbose_name_plural': 'Fotky príspevkov',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='feedpostimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.feedpost', verbose_name='Príspevok'),
        ),
        migrations.AddIndex(
            model_name='feedpostimage',
            index=models.Index(fields=['post', 'order'], name='acc_fpimg_post_order_idx'),
        ),
        # Prevod dát MUSÍ byť medzi vytvorením tabuľky a odstránením starých
        # stĺpcov – po RemoveField by už nebolo z čoho čítať.
        migrations.RunPython(
            move_images_to_child_table,
            move_images_back_to_post,
        ),
        migrations.RemoveConstraint(
            model_name='feedpost',
            name='feed_post_type_consistency',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_approved_key',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_content_type',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_original_filename',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_pending_key',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_processed_at',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_rejected_reason',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_size_bytes',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_status',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_thumbnail_key',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='image_width',
        ),
        migrations.AddConstraint(
            model_name='feedpost',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post_type', 'free_post'), ('shared_feed_post__isnull', True), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True), models.Q(('caption', ''), _negated=True)), models.Q(('post_type', 'shared_offer'), ('shared_feed_post__isnull', True), ('shared_portfolio_item__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('post_type', 'shared_portfolio_item'), ('shared_feed_post__isnull', True), ('shared_offer__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('post_type', 'shared_feed_post'), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True)), _connector='OR'), name='feed_post_type_consistency'),
        ),
    ]
