# Generated by Django 4.2.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0108_feed_post_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeredskill",
            name="description",
            field=models.TextField(blank=True, max_length=150, verbose_name="Popis"),
        ),
    ]
