# Generated by Django 4.2.7 on 2026-08-13 18:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_alter_offeredskill_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Interná pozícia od 1 do 5, ktorá vynucuje limit sledovaní.', verbose_name='Pozícia')),
                ('category', models.CharField(max_length=100, verbose_name='Kategória')),
                ('subcategory', models.CharField(max_length=100, verbose_name='Podkategória')),
                ('is_seeking', models.BooleanField(default=False, help_text='True sleduje dopyty, False sleduje ponuky.', verbose_name='Dopyt')),
                ('country_code', models.CharField(max_length=2, verbose_name='Krajina')),
                ('district_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Kód okresu')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena od')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_watches', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
            ],
            options={
                'verbose_name': 'Sledovanie',
                'verbose_name_plural': 'Sledovania',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfferWatchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True, verbose_name='Zhoda nájdená')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notifikácia odoslaná')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_notifications', to='accounts.offeredskill', verbose_name='Ponuka alebo dopyt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_watch_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ')),
                ('watch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_candidates', to='accounts.offerwatch', verbose_name='Sledovanie')),
            ],
            options={
                'verbose_name': 'Kandidát notifikácie sledovania',
                'verbose_name_plural': 'Kandidáti notifikácií sledovania',
                'ordering': ['-matched_at', '-id'],
                'indexes': [models.Index(fields=['user', '-matched_at'], name='acc_watch_notif_user_idx'), models.Index(fields=['notified_at', 'matched_at'], name='acc_watch_notif_pending_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='offerwatchnotification',
            constraint=models.UniqueConstraint(fields=('user', 'offer'), name='acc_watch_notif_unique_offer'),
        ),
        migrations.AddIndex(
            model_name='offerwatch',
            index=models.Index(fields=['user', '-created_at'], name='acc_watch_user_new_idx'),
        ),
        migrations.AddIndex(
            model_name='offerwatch',
            index=models.Index(fields=['category', 'subcategory', 'is_seeking', 'country_code', 'district_code'], name='acc_watch_match_idx'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('slot__gte', 1), ('slot__lte', 5)), name='acc_watch_slot_range'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='acc_watch_unique_user_slot'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('country_code__in', ('SK', 'CZ', 'PL', 'HU', 'AT', 'DE'))), name='acc_watch_supported_country'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('category', ''), _negated=True), name='acc_watch_category_required'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('subcategory', ''), _negated=True), name='acc_watch_subcategory_required'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('price_min__isnull', True), ('price_min__gte', 0), _connector='OR'), name='acc_watch_price_min_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('price_max__isnull', True), ('price_max__gte', 0), _connector='OR'), name='acc_watch_price_max_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.CheckConstraint(check=models.Q(('price_min__isnull', True), ('price_max__isnull', True), ('price_min__lte', models.F('price_max')), _connector='OR'), name='acc_watch_price_order'),
        ),
        migrations.AddConstraint(
            model_name='offerwatch',
            constraint=models.UniqueConstraint(models.F('user'), models.F('category'), models.F('subcategory'), models.F('is_seeking'), models.F('country_code'), models.F('district_code'), django.db.models.functions.comparison.Coalesce('price_min', models.Value(Decimal('-1.00'))), django.db.models.functions.comparison.Coalesce('price_max', models.Value(Decimal('-1.00'))), name='acc_watch_unique_filters'),
        ),
    ]
