# Generated by Django 4.2.7 on 2026-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_expand_offer_watch_countries'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feedpost',
            name='feed_post_type_consistency',
        ),
        migrations.AddConstraint(
            model_name='feedpost',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post_type', 'free_post'), ('shared_feed_post__isnull', True), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True)), models.Q(('post_type', 'shared_offer'), ('shared_feed_post__isnull', True), ('shared_portfolio_item__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('post_type', 'shared_portfolio_item'), ('shared_feed_post__isnull', True), ('shared_offer__isnull', True), models.Q(('shared_title', ''), _negated=True)), models.Q(('post_type', 'shared_feed_post'), ('shared_offer__isnull', True), ('shared_portfolio_item__isnull', True)), _connector='OR'), name='feed_post_type_consistency'),
        ),
    ]
