# Generated by Django 4.2.7 on 2026-08-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_offer_watch_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpostcomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.feedpostcomment', verbose_name='Odpoveď na komentár'),
        ),
        migrations.AddIndex(
            model_name='feedpostcomment',
            index=models.Index(fields=['parent_comment', 'created_at'], name='acc_fpcomm_parent_cr_idx'),
        ),
    ]
