# Generated by Django 4.2.7 on 2026-08-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_notification_comment_reply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Text upravený'),
        ),
        migrations.AddField(
            model_name='feedpostcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Text upravený'),
        ),
    ]
