version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: swaply
      POSTGRES_USER: swaply_user
      POSTGRES_PASSWORD: swaply_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://swaply_user:swaply_password@db:5432/swaply
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://192.168.68.103:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
