# Default kompatibilný runtime. Na Railway môžeš použiť:
# - APP_SERVER_MODE=http pre gunicorn HTTP service
# - APP_SERVER_MODE=ws   pre daphne WebSocket service
web: ./start.sh
worker: celery -A swaply worker -l info
beat: celery -A swaply beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler

