# Default kompatibilný runtime. Na Railway môžeš použiť:
# - APP_SERVER_MODE=http pre gunicorn HTTP service
# - APP_SERVER_MODE=ws   pre daphne WebSocket service
web: ./start.sh
worker: celery -A swaply worker -l info

