# Generated by Codex on 2026-07-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portfolio", "0002_portfolioimage_variant_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioItemLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Vytvorene")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_likes",
                        to="portfolio.portfolioitem",
                        verbose_name="Polozka portfolia",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_item_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pouzivatel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paci sa mi portfolio",
                "verbose_name_plural": "Paci sa mi portfolia",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="portfolioitemlike",
            constraint=models.UniqueConstraint(
                fields=("item", "user"),
                name="unique_portfolio_item_like_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioitemlike",
            index=models.Index(
                fields=["item", "created_at"],
                name="port_like_item_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioitemlike",
            index=models.Index(
                fields=["user", "created_at"],
                name="port_like_user_created_idx",
            ),
        ),
    ]