# Generated by Django 5.2.15 on 2026-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitemlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Popis'),
        ),
    ]
