from django.urls import path

from .api.group_candidates import GroupMemberCandidatesView
from .api.presence_views import MessagePresenceView
from .api.views import (
    AcceptMessageRequestView,
    ConversationListView,
    ConversationPinStateView,
    DeleteMessageView,
    DeleteMessageRequestView,
    ForwardMessageView,
    GroupConversationCreateView,
    GroupConversationDetailView,
    GroupInvitationResponseView,
    GroupInviteView,
    GroupLeaveView,
    GroupMemberDetailView,
    HideConversationView,
    MarkConversationReadView,
    MarkMessageRequestsSeenView,
    MessageImageView,
    MessageListView,
    MessageRequestListView,
    MessageRequestUnreadSummaryView,
    OpenConversationView,
    PinMessageView,
    SendMessageView,
    StartDirectMessageView,
    UnreadMessagesSummaryView,
)

urlpatterns = [
    path("conversations/open/", OpenConversationView.as_view(), name="messaging_open"),
    path(
        "conversations/unread-summary/",
        UnreadMessagesSummaryView.as_view(),
        name="messaging_unread_summary",
    ),
    path(
        "conversations/requests/",
        MessageRequestListView.as_view(),
        name="messaging_list_message_requests",
    ),
    path(
        "conversations/requests/unseen-summary/",
        MessageRequestUnreadSummaryView.as_view(),
        name="messaging_message_request_unseen_summary",
    ),
    path(
        "conversations/requests/mark-seen/",
        MarkMessageRequestsSeenView.as_view(),
        name="messaging_mark_message_requests_seen",
    ),
    path(
        "conversations/direct/send/",
        StartDirectMessageView.as_view(),
        name="messaging_send_direct_message",
    ),
    path(
        "conversations/groups/",
        GroupConversationCreateView.as_view(),
        name="messaging_create_group_conversation",
    ),
    path(
        "conversations/group-member-candidates/",
        GroupMemberCandidatesView.as_view(),
        name="messaging_group_member_candidates",
    ),
    path("conversations/", ConversationListView.as_view(), name="messaging_list_conversations"),
    path("presence/", MessagePresenceView.as_view(), name="messaging_presence"),
    path(
        "conversations/<int:conversation_id>/messages/",
        MessageListView.as_view(),
        name="messaging_list_messages",
    ),
    path(
        "conversations/<int:conversation_id>/messages/send/",
        SendMessageView.as_view(),
        name="messaging_send_message",
    ),
    path(
        "conversations/<int:conversation_id>/messages/<int:message_id>/image/",
        MessageImageView.as_view(),
        name="messaging_message_image",
    ),
    path(
        "conversations/<int:conversation_id>/messages/<int:message_id>/delete/",
        DeleteMessageView.as_view(),
        name="messaging_delete_message",
    ),
    path(
        "conversations/<int:conversation_id>/messages/<int:message_id>/forward/",
        ForwardMessageView.as_view(),
        name="messaging_forward_message",
    ),
    path(
        "conversations/<int:conversation_id>/pin/",
        PinMessageView.as_view(),
        name="messaging_pin_message",
    ),
    path(
        "conversations/<int:conversation_id>/read/",
        MarkConversationReadView.as_view(),
        name="messaging_mark_read",
    ),
    path(
        "conversations/<int:conversation_id>/requests/accept/",
        AcceptMessageRequestView.as_view(),
        name="messaging_accept_message_request",
    ),
    path(
        "conversations/<int:conversation_id>/requests/delete/",
        DeleteMessageRequestView.as_view(),
        name="messaging_delete_message_request",
    ),
    path(
        "conversations/<int:conversation_id>/hide/",
        HideConversationView.as_view(),
        name="messaging_hide_conversation",
    ),
    path(
        "conversations/<int:conversation_id>/pin-state/",
        ConversationPinStateView.as_view(),
        name="messaging_conversation_pin_state",
    ),
    path(
        "conversations/<int:conversation_id>/group/",
        GroupConversationDetailView.as_view(),
        name="messaging_group_detail",
    ),
    path(
        "conversations/<int:conversation_id>/group/invite/",
        GroupInviteView.as_view(),
        name="messaging_group_invite",
    ),
    path(
        "conversations/<int:conversation_id>/group/members/<int:user_id>/",
        GroupMemberDetailView.as_view(),
        name="messaging_group_member_detail",
    ),
    path(
        "conversations/<int:conversation_id>/group/leave/",
        GroupLeaveView.as_view(),
        name="messaging_group_leave",
    ),
    path(
        "group-invitations/<int:invitation_id>/<str:action>/",
        GroupInvitationResponseView.as_view(),
        name="messaging_group_invitation_response",
    ),
]

