export const SLOVAK_DISTRICTS = [
  'Bánovce nad Bebravou',
  'Banská Bystrica',
  'Banská Štiavnica',
  'Bardejov',
  'Bratislava I',
  'Bratislava II',
  'Bratislava III',
  'Bratislava IV',
  'Bratislava V',
  'Brezno',
  'Bytča',
  'Čadca',
  'Detva',
  'Dolný Kubín',
  'Dunajská Streda',
  'Galanta',
  'Gelnica',
  'Hlohovec',
  'Humenné',
  'Ilava',
  'Kežmarok',
  'Komárno',
  'Košice I',
  'Košice II',
  'Košice III',
  'Košice IV',
  'Košice-okolie',
  'Krupina',
  'Kysucké Nové Mesto',
  'Levice',
  'Levoča',
  'Liptovský Mikuláš',
  'Lučenec',
  'Malacky',
  'Martin',
  'Medzilaborce',
  'Michalovce',
  'Myjava',
  'Námestovo',
  'Nitra',
  'Nové Mesto nad Váhom',
  'Nové Zámky',
  'Partizánske',
  'Pezinok',
  'Piešťany',
  'Poltár',
  'Poprad',
  'Považská Bystrica',
  'Prešov',
  'Prievidza',
  'Púchov',
  'Revúca',
  'Rimavská Sobota',
  'Rožňava',
  'Ružomberok',
  'Sabinov',
  'Senec',
  'Senica',
  'Skalica',
  'Snina',
  'Sobrance',
  'Spišská Nová Ves',
  'Stará Ľubovňa',
  'Stropkov',
  'Svidník',
  'Šaľa',
  'Topoľčany',
  'Trebišov',
  'Trenčín',
  'Trnava',
  'Turčianske Teplice',
  'Tvrdošín',
  'Veľký Krtíš',
  'Vranov nad Topľou',
  'Zlaté Moravce',
  'Zvolen',
  'Žarnovica',
  'Žiar nad Hronom',
  'Žilina',
];

export const CZECH_DISTRICTS = [
  'Benešov',
  'Beroun',
  'Blansko',
  'Brno-město',
  'Brno-venkov',
  'Bruntál',
  'Břeclav',
  'Česká Lípa',
  'České Budějovice',
  'Český Krumlov',
  'Děčín',
  'Domažlice',
  'Frýdek-Místek',
  'Havlíčkův Brod',
  'Hodonín',
  'Hradec Králové',
  'Cheb',
  'Chomutov',
  'Chrudim',
  'Jablonec nad Nisou',
  'Jeseník',
  'Jičín',
  'Jihlava',
  'Jindřichův Hradec',
  'Karlovy Vary',
  'Karviná',
  'Kladno',
  'Klatovy',
  'Kolín',
  'Kroměříž',
  'Kutná Hora',
  'Liberec',
  'Litoměřice',
  'Louny',
  'Mělník',
  'Mladá Boleslav',
  'Náchod',
  'Nový Jičín',
  'Nymburk',
  'Olomouc',
  'Opava',
  'Ostrava-město',
  'Pardubice',
  'Pelhřimov',
  'Písek',
  'Plzeň-jih',
  'Plzeň-město',
  'Plzeň-sever',
  'Praha-západ',
  'Praha-východ',
  'Příbram',
  'Prostějov',
  'Přerov',
  'Rakovník',
  'Rokycany',
  'Sokolov',
  'Strakonice',
  'Svitavy',
  'Šumperk',
  'Tachov',
  'Tábor',
  'Trutnov',
  'Třebíč',
  'Ústí nad Labem',
  'Ústí nad Orlicí',
  'Valašské Meziříčí',
  'Vsetín',
  'Vyškov',
  'Znojmo',
  'Žďár nad Sázavou',
  'Zlín',
];

export const POLISH_DISTRICTS = [
  'Biała Podlaska',
  'Białystok',
  'Bielsko-Biała',
  'Bydgoszcz',
  'Bytom',
  'Chełm',
  'Chorzów',
  'Częstochowa',
  'Dąbrowa Górnicza',
  'Elbląg',
  'Gdańsk',
  'Gdynia',
  'Gliwice',
  'Gorzów Wielkopolski',
  'Grudziądz',
  'Jastrzębie Zdrój',
  'Jaworzno',
  'Jelenia Góra',
  'Kalisz',
  'Katovice',
  'Kielce',
  'Konin',
  'Koszalin',
  'Kraków',
  'Krosno',
  'Legnica',
  'Leszno',
  'Lublin',
  'Łomża',
  'Lodž',
  'Mysłowice',
  'Nowy Sącz',
  'Olsztyn',
  'Opole',
  'Ostrołęka',
  'Piekary Śląskie',
  'Piotrków Trybunalski',
  'Płock',
  'Poznań',
  'Przemyśl',
  'Radom',
  'Ruda Śląska',
  'Rybnik',
  'Rzeszów',
  'Siedlce',
  'Siemianowice Śląskie',
  'Skierniewice',
  'Słupsk',
  'Sopot',
  'Sosnowiec',
  'Suwałki',
  'Szczecin',
  'Świętochłowice',
  'Świnoujście',
  'Tarnobrzeg',
  'Tarnów',
  'Toruń',
  'Tychy',
  'Warszawa',
  'Włocławek',
  'Wrocław',
  'Zabrze',
  'Zamość',
  'Zielona Góra',
  'Żory',
];

export const HUNGARIAN_DISTRICTS = [
  'Abádszalók',
  'Ajka',
  'Aszód',
  'Baja',
  'Baktalórántháza',
  'Balassagyarmat',
  'Balatonalmádi',
  'Balatonfüred',
  'Balmazújváros',
  'Barcs',
  'Berettyóújfalu',
  'Bicske',
  'Bonyhád',
  'Budapest',
  'Budaörs',
  'Bácsalmás',
  'Bátonyterenye',
  'Békés',
  'Békéscsaba',
  'Bélapátfalva',
  'Cegléd',
  'Celldömölk',
  'Cigánd',
  'Csenger',
  'Csepreg',
  'Csongrád',
  'Csorna',
  'Csurgó',
  'Dabas',
  'Debrecen',
  'Derecske',
  'Devecser',
  'Dombóvár',
  'Dorog',
  'Dunakeszi',
  'Dunaújváros',
  'Edelény',
  'Eger',
  'Encs',
  'Enying',
  'Esztergom',
  'Fehérgyarmat',
  'Fonyód',
  'Füzesabony',
  'Gyula',
  'Gyál',
  'Gyöngyös',
  'Győr',
  'Gárdony',
  'Gödöllő',
  'Gönc',
  'Hajdúböszörmény',
  'Hajdúhadház',
  'Hajdúnánás',
  'Hajdúszoboszló',
  'Hatvan',
  'Heves',
  'Hódmezővásárhely',
  'Ibrány',
  'Jánoshalma',
  'Jászapáti',
  'Jászberény',
  'Kalocsa',
  'Kaposvár',
  'Kapuvár',
  'Karcag',
  'Kazincbarcika',
  'Kecskemét',
  'Kemecse',
  'Keszthely',
  'Kisbér',
  'Kiskunfélegyháza',
  'Kiskunhalas',
  'Kiskőrös',
  'Kistelek',
  'Kisvárda',
  'Kisújszállás',
  'Komló',
  'Komárom',
  'Kunhegyes',
  'Kunszentmiklós',
  'Kunszentmárton',
  'Körmend',
  'Kőszeg',
  'Lenti',
  'Letenye',
  'Makó',
  'Marcali',
  'Martonvásár',
  'Mezőcsát',
  'Mezőkovácsháza',
  'Mezőkövesd',
  'Mezőtúr',
  'Miskolc',
  'Monor',
  'Mosonmagyaróvár',
  'Mátészalka',
  'Mór',
  'Mórahalom',
  'Nagyatád',
  'Nagyecsed',
  'Nagykanizsa',
  'Nagykálló',
  'Nagykáta',
  'Nyíradony',
  'Nyírbátor',
  'Nyíregyháza',
  'Orosháza',
  'Oroszlány',
  'Pacsa',
  'Paks',
  'Pannonhalma',
  'Pilisvörösvár',
  'Polgárdi',
  'Pápa',
  'Pásztó',
  'Pécs',
  'Pécsvárad',
  'Pétervására',
  'Püspökladány',
  'Ráckeve',
  'Rétság',
  'Salgótarján',
  'Sarkad',
  'Sellye',
  'Siófok',
  'Sopron',
  'Szarvas',
  'Szeged',
  'Szekszárd',
  'Szentendre',
  'Szentes',
  'Szentgotthárd',
  'Szentlőrinc',
  'Szerencs',
  'Szigetszentmiklós',
  'Szigetvár',
  'Szikszó',
  'Szolnok',
  'Szombathely',
  'Szécsény',
  'Székesfehérvár',
  'Sárbogárd',
  'Sárospatak',
  'Sárvár',
  'Sásd',
  'Sátoraljaújhely',
  'Sümeg',
  'Tab',
  'Tamási',
  'Tapolca',
  'Tata',
  'Tatabánya',
  'Tiszafüred',
  'Tiszavasvári',
  'Tiszaújváros',
  'Tokaj',
  'Tét',
  'Törökszentmiklós',
  'Vasvár',
  'Vecsés',
  'Veszprém',
  'Vác',
  'Várpalota',
  'Vásárosnamény',
  'Zalaegerszeg',
  'Zalaszentgrót',
  'Zirc',
  'Záhony',
  'Érd',
  'Ózd',
];

export const AUSTRIAN_DISTRICTS = [
  'Amstetten',
  'Baden',
  'Bludenz',
  'Braunau am Inn',
  'Bregenz',
  'Bruck an der Leitha',
  'Bruck-Mürzzuschlag',
  'Deutschlandsberg',
  'Dornbirn',
  'Eferding',
  'Eisenstadt',
  'Eisenstadt-Umgebung',
  'Feldkirch',
  'Feldkirchen',
  'Freistadt',
  'Gmunden',
  'Gmünd',
  'Graz',
  'Graz-Umgebung',
  'Grieskirchen',
  'Gänserndorf',
  'Güssing',
  'Hallein',
  'Hartberg-Fürstenfeld',
  'Hermagor',
  'Hollabrunn',
  'Horn',
  'Imst',
  'Innsbruck',
  'Innsbruck-Land',
  'Jennersdorf',
  'Kirchdorf an der Krems',
  'Kitzbühel',
  'Klagenfurt am Wörthersee',
  'Klagenfurt-Land',
  'Korneuburg',
  'Krems',
  'Krems an der Donau',
  'Kufstein',
  'Landeck',
  'Leibnitz',
  'Leoben',
  'Lienz',
  'Liezen',
  'Lilienfeld',
  'Linz',
  'Linz-Land',
  'Mattersburg',
  'Melk',
  'Mistelbach',
  'Murau',
  'Murtal',
  'Mödling',
  'Neunkirchen',
  'Neusiedl am See',
  'Oberpullendorf',
  'Oberwart',
  'Perg',
  'Reutte',
  'Ried im Innkreis',
  'Rohrbach',
  'Rust',
  'Salzburg',
  'Salzburg-Umgebung',
  'Sankt Johann im Pongau',
  'Sankt Pölten',
  'Sankt Pölten-Land',
  'Sankt Veit an der Glan',
  'Scheibbs',
  'Schwaz',
  'Schwechat',
  'Schärding',
  'Spittal an der Drau',
  'Steyr',
  'Steyr-Land',
  'Südoststeiermark',
  'Tamsweg',
  'Tulln',
  'Urfahr-Umgebung',
  'Villach',
  'Villach-Land',
  'Voitsberg',
  'Vöcklabruck',
  'Völkermarkt',
  'Waidhofen an der Thaya',
  'Waidhofen an der Ybbs',
  'Weiz',
  'Wels',
  'Wels-Land',
  'Wien',
  'Wien-Umgebung',
  'Wiener Neustadt',
  'Wiener Neustadt-Land',
  'Wolfsberg',
  'Zell am See',
  'Zwettl',
];

export const GERMAN_DISTRICTS = [
  'Aachen', 'Ahrweiler', 'Aichach-Friedberg', 'Alb-Donau-Kreis', 'Altenburger Land', 'Altenkirchen', 'Altmarkkreis Salzwedel', 'Altötting', 'Alzey-Worms', 'Amberg', 'Amberg-Sulzbach', 'Ammerland', 'Annaberg', 'Anhalt-Bitterfeld', 'Ansbach', 'Aschaffenburg', 'Augsburg', 'Aue-Schwarzenberg', 'Aurich', 'Bad Doberan', 'Bad Dürkheim', 'Bad Kissingen', 'Bad Kreuznach', 'Bad Tölz-Wolfratshausen', 'Baden-Baden', 'Bamberg', 'Barnim', 'Bautzen', 'Bayreuth', 'Berchtesgadener Land', 'Bergstraße', 'Bernkastel-Wittlich', 'Biberach', 'Bielefeld', 'Birkenfeld', 'Bitburg-Prüm', 'Bochum', 'Böblingen', 'Bodenseekreis', 'Bonn', 'Börde', 'Borken', 'Bottrop', 'Brandenburg an der Havel', 'Braunschweig', 'Breisgau-Hochschwarzwald', 'Bremen', 'Bremerhaven', 'Burgenlandkreis', 'Calw', 'Celle', 'Cham', 'Chemnitz', 'Cloppenburg', 'Coburg', 'Coesfeld', 'Cochem-Zell', 'Cottbus', 'Cuxhaven', 'Dachau', 'Dahme-Spreewald', 'Darmstadt', 'Darmstadt-Dieburg', 'Deggendorf', 'Delitzsch', 'Delmenhorst', 'Demmin', 'Dessau-Roßlau', 'Diepholz', 'Dillingen an der Donau', 'Dingolfing-Landau', 'Dithmarschen', 'Döbeln', 'Donau-Ries', 'Donnersbergkreis', 'Dortmund', 'Dresden', 'Duisburg', 'Düren', 'Düsseldorf', 'Ebersberg', 'Eichsfeld', 'Eichstätt', 'Eisenach', 'Elbe-Elster', 'Emmendingen', 'Emden', 'Emsland', 'Ennepe-Ruhr-Kreis', 'Enzkreis', 'Erding', 'Erfurt', 'Erlangen', 'Erlangen-Höchstadt', 'Essen', 'Esslingen', 'Euskirchen', 'Flensburg', 'Forchheim', 'Frankenthal', 'Frankfurt (Oder)', 'Frankfurt am Main', 'Freiburg im Breisgau', 'Freiberg', 'Freising', 'Freudenstadt', 'Freyung-Grafenau', 'Friesland', 'Fulda', 'Fürstenfeldbruck', 'Fürth', 'Garmisch-Partenkirchen', 'Gelsenkirchen', 'Gera', 'Germersheim', 'Gießen', 'Gifhorn', 'Göppingen', 'Görlitz', 'Goslar', 'Gotha', 'Göttingen', 'Grafschaft Bentheim', 'Greiz', 'Groß-Gerau', 'Güstrow', 'Gütersloh', 'Günzburg', 'Hagen', 'Halle (Saale)', 'Hamburg', 'Hameln-Pyrmont', 'Hannover', 'Harburg', 'Harz', 'Hassberge', 'Heidekreis', 'Heidelberg', 'Heidenheim', 'Heilbronn', 'Heinsberg', 'Helmstedt', 'Herford', 'Herne', 'Hersfeld-Rotenburg', 'Herzogtum Lauenburg', 'Hildburghausen', 'Hildesheim', 'Hochsauerlandkreis', 'Hochtaunuskreis', 'Hof', 'Hohenlohekreis', 'Holzminden', 'Ilm-Kreis', 'Jena', 'Jerichower Land', 'Kamenz', 'Karlsruhe', 'Kassel', 'Kelheim', 'Kiel', 'Kitzingen', 'Kleve', 'Köln', 'Konstanz', 'Krefeld', 'Kronach', 'Kulmbach', 'Kusel', 'Kyffhäuserkreis', 'Lahn-Dill-Kreis', 'Landau in der Pfalz', 'Landsberg am Lech', 'Landshut', 'Leverkusen', 'Lichtenfels', 'Limburg-Weilburg', 'Lindau', 'Lippe', 'Löbau-Zittau', 'Lörrach', 'Lübeck', 'Lüchow-Dannenberg', 'Ludwigshafen am Rhein', 'Ludwigslust', 'Ludwigsburg', 'Lüneburg', 'Magdeburg', 'Main-Kinzig-Kreis', 'Main-Spessart', 'Main-Taunus-Kreis', 'Main-Tauber-Kreis', 'Mainz', 'Mainz-Bingen', 'Mannheim', 'Mansfeld-Südharz', 'Marburg-Biedenkopf', 'Märkisch-Oderland', 'Märkischer Kreis', 'Mayen-Koblenz', 'Mecklenburgische Seenplatte', 'Meißen', 'Memmingen', 'Merzig-Wadern', 'Mettmann', 'Miesbach', 'Miltenberg', 'Minden-Lübbecke', 'Mittweida', 'Mönchengladbach', 'Mühldorf am Inn', 'Muldentalkreis', 'Mülheim an der Ruhr', 'München', 'Münster', 'Neckar-Odenwald-Kreis', 'Neuburg-Schrobenhausen', 'Neumarkt in der Oberpfalz', 'Neumünster', 'Neunkirchen', 'Neustadt an der Aisch-Bad Windsheim', 'Neustadt an der Waldnaab', 'Neustadt an der Weinstraße', 'Neuwied', 'Nienburg', 'Nordfriesland', 'Nordhausen', 'Nordvorpommern', 'Nordwestmecklenburg', 'Nordsachsen', 'Northeim', 'Nürnberg', 'Nürnberger Land', 'Oberallgäu', 'Oberbergischer Kreis', 'Oberhausen', 'Oberhavel', 'Oberspreewald-Lausitz', 'Odenwaldkreis', 'Oder-Spree', 'Offenbach', 'Oldenburg', 'Olpe', 'Ortenaukreis', 'Ostalbkreis', 'Ostallgäu', 'Ostholstein', 'Ostprignitz-Ruppin', 'Ostvorpommern', 'Paderborn', 'Parchim', 'Passau', 'Peine', 'Pfaffenhofen an der Ilm', 'Pinneberg', 'Pirmasens', 'Plauen', 'Plön', 'Potsdam', 'Prignitz', 'Rastatt', 'Ravensburg', 'Recklinghausen', 'Regen', 'Regensburg', 'Rems-Murr-Kreis', 'Remscheid', 'Rendsburg-Eckernförde', 'Reutlingen', 'Rheingau-Taunus-Kreis', 'Rhein-Hunsrück-Kreis', 'Rhein-Kreis Neuss', 'Rhein-Lahn-Kreis', 'Rhein-Neckar-Kreis', 'Rhein-Pfalz-Kreis', 'Rhein-Sieg-Kreis', 'Rhein-Erft-Kreis', 'Rhön-Grabfeld', 'Riesa-Großenhain', 'Rosenheim', 'Rostock', 'Roth', 'Rotenburg (Wümme)', 'Rottal-Inn', 'Rottweil', 'Rügen', 'Saalekreis', 'Saarbrücken', 'Saarlouis', 'Saarpfalz-Kreis', 'Saalfeld-Rudolstadt', 'Saale-Holzland-Kreis', 'Saale-Orla-Kreis', 'Sächsische Schweiz-Osterzgebirge', 'Salzlandkreis', 'Salzgitter', 'Schaumburg', 'Schleswig-Flensburg', 'Schmalkalden-Meiningen', 'Schwäbisch Hall', 'Schwalm-Eder-Kreis', 'Schwandorf', 'Schwarzwald-Baar-Kreis', 'Schweinfurt', 'Schwerin', 'Segeberg', 'Siegen-Wittgenstein', 'Sigmaringen', 'Soest', 'Solingen', 'Soltau-Fallingbostel', 'Sömmerda', 'Sonneberg', 'Spree-Neiße', 'Speyer', 'Stade', 'Starnberg', 'Steinfurt', 'Steinburg', 'Stendal', 'Stollberg', 'Stormarn', 'Straubing-Bogen', 'Stuttgart', 'Südliche Weinstraße', 'Südwestpfalz', 'Suhl', 'Teltow-Fläming', 'Tirschenreuth', 'Torgau-Oschatz', 'Traunstein', 'Trier', 'Trier-Saarburg', 'Tübingen', 'Tuttlingen', 'Uckermark', 'Uecker-Randow', 'Uelzen', 'Ulm', 'Unna', 'Unstrut-Hainich-Kreis', 'Unterallgäu', 'Vechta', 'Verden', 'Viersen', 'Vogtlandkreis', 'Vogelsbergkreis', 'Vorpommern-Greifswald', 'Vorpommern-Rügen', 'Vulkaneifel', 'Waldshut', 'Warendorf', 'Wartburgkreis', 'Wesel', 'Wesermarsch', 'Westerwaldkreis', 'Wetteraukreis', 'Weilheim-Schongau', 'Weimar', 'Weimarer Land', 'Weißenburg-Gunzenhausen', 'Werra-Meißner-Kreis', 'Wesel', 'Wiesbaden', 'Wilhelmshaven', 'Wittenberg', 'Wittmund', 'Wolfenbüttel', 'Wolfsburg', 'Worms', 'Wunsiedel im Fichtelgebirge', 'Wuppertal', 'Würzburg', 'Zollernalbkreis', 'Zweibrücken', 'Zwickau',
];


