// Rakúske okresy (Bezirke)
const AUSTRIAN_DISTRICTS = [
  'Amstetten',
  'Baden',
  'Bludenz',
  'Braunau am Inn',
  'Bregenz',
  'Bruck an der Leitha',
  'Bruck-Mürzzuschlag',
  'Deutschlandsberg',
  'Dornbirn',
  'Eferding',
  'Eisenstadt',
  'Eisenstadt-Umgebung',
  'Feldkirch',
  'Feldkirchen',
  'Freistadt',
  'Gmunden',
  'Gmünd',
  'Graz',
  'Graz-Umgebung',
  'Grieskirchen',
  'Gänserndorf',
  'Güssing',
  'Hallein',
  'Hartberg-Fürstenfeld',
  'Hermagor',
  'Hollabrunn',
  'Horn',
  'Imst',
  'Innsbruck',
  'Innsbruck-Land',
  'Jennersdorf',
  'Kirchdorf an der Krems',
  'Kitzbühel',
  'Klagenfurt am Wörthersee',
  'Klagenfurt-Land',
  'Korneuburg',
  'Krems',
  'Krems an der Donau',
  'Kufstein',
  'Landeck',
  'Leibnitz',
  'Leoben',
  'Lienz',
  'Liezen',
  'Lilienfeld',
  'Linz',
  'Linz-Land',
  'Mattersburg',
  'Melk',
  'Mistelbach',
  'Murau',
  'Murtal',
  'Mödling',
  'Neunkirchen',
  'Neusiedl am See',
  'Oberpullendorf',
  'Oberwart',
  'Perg',
  'Reutte',
  'Ried im Innkreis',
  'Rohrbach',
  'Rust',
  'Salzburg',
  'Salzburg-Umgebung',
  'Sankt Johann im Pongau',
  'Sankt Pölten',
  'Sankt Pölten-Land',
  'Sankt Veit an der Glan',
  'Scheibbs',
  'Schwaz',
  'Schwechat',
  'Schärding',
  'Spittal an der Drau',
  'Steyr',
  'Steyr-Land',
  'Südoststeiermark',
  'Tamsweg',
  'Tulln',
  'Urfahr-Umgebung',
  'Villach',
  'Villach-Land',
  'Voitsberg',
  'Vöcklabruck',
  'Völkermarkt',
  'Waidhofen an der Thaya',
  'Waidhofen an der Ybbs',
  'Weiz',
  'Wels',
  'Wels-Land',
  'Wien',
  'Wien-Umgebung',
  'Wiener Neustadt',
  'Wiener Neustadt-Land',
  'Wolfsberg',
  'Zell am See',
  'Zwettl',
];
