// Nemecké okresy (Landkreise)
const GERMAN_DISTRICTS = [
  'Aachen',
  'Ahrweiler',
  'Aichach-Friedberg',
  'Alb-Donau-Kreis',
  'Altenburger Land',
  'Altenkirchen',
  'Altmarkkreis Salzwedel',
  'Altötting',
  'Alzey-Worms',
  'Amberg',
  'Amberg-Sulzbach',
  'Ammerland',
  'Anhalt-Bitterfeld',
  'Annaberg',
  'Ansbach',
  'Aschaffenburg',
  'Aue-Schwarzenberg',
  'Augsburg',
  'Aurich',
  'Bad Doberan',
  'Bad Dürkheim',
  'Bad Kissingen',
  'Bad Kreuznach',
  'Bad Tölz-Wolfratshausen',
  'Baden-Baden',
  'Bamberg',
  'Barnim',
  'Bautzen',
  'Bayreuth',
  'Berchtesgadener Land',
  'Bergstraße',
  'Berlin',
  'Bernkastel-Wittlich',
  'Biberach',
  'Bielefeld',
  'Birkenfeld',
  'Bitburg-Prüm',
  'Bochum',
  'Bodenseekreis',
  'Bonn',
  'Borken',
  'Bottrop',
  'Brandenburg an der Havel',
  'Braunschweig',
  'Breisgau-Hochschwarzwald',
  'Bremen',
  'Bremerhaven',
  'Burgenlandkreis',
  'Böblingen',
  'Börde',
  'Calw',
  'Celle',
  'Cham',
  'Chemnitz',
  'Cloppenburg',
  'Coburg',
  'Cochem-Zell',
  'Coesfeld',
  'Cottbus',
  'Cuxhaven',
  'Dachau',
  'Dahme-Spreewald',
  'Darmstadt',
  'Darmstadt-Dieburg',
  'Deggendorf',
  'Delitzsch',
  'Delmenhorst',
  'Demmin',
  'Dessau-Roßlau',
  'Diepholz',
  'Dillingen an der Donau',
  'Dingolfing-Landau',
  'Dithmarschen',
  'Donau-Ries',
  'Donnersbergkreis',
  'Dortmund',
  'Dresden',
  'Duisburg',
  'Döbeln',
  'Düren',
  'Düsseldorf',
  'Ebersberg',
  'Eichsfeld',
  'Eichstätt',
  'Eisenach',
  'Elbe-Elster',
  'Emden',
  'Emmendingen',
  'Emsland',
  'Ennepe-Ruhr-Kreis',
  'Enzkreis',
  'Erding',
  'Erfurt',
  'Erlangen',
  'Erlangen-Höchstadt',
  'Essen',
  'Esslingen',
  'Euskirchen',
  'Flensburg',
  'Forchheim',
  'Frankenthal',
  'Frankfurt (Oder)',
  'Frankfurt am Main',
  'Freiberg',
  'Freiburg im Breisgau',
  'Freising',
  'Freudenstadt',
  'Freyung-Grafenau',
  'Friesland',
  'Fulda',
  'Fürstenfeldbruck',
  'Fürth',
  'Garmisch-Partenkirchen',
  'Gelsenkirchen',
  'Gera',
  'Germersheim',
  'Gießen',
  'Gifhorn',
  'Goslar',
  'Gotha',
  'Grafschaft Bentheim',
  'Greiz',
  'Groß-Gerau',
  'Göppingen',
  'Görlitz',
  'Göttingen',
  'Günzburg',
  'Güstrow',
  'Gütersloh',
  'Hagen',
  'Halle (Saale)',
  'Hamburg',
  'Hameln-Pyrmont',
  'Hamm',
  'Hannover',
  'Harburg',
  'Harz',
  'Hassberge',
  'Havelland',
  'Heidekreis',
  'Heidelberg',
  'Heidenheim',
  'Heilbronn',
  'Heinsberg',
  'Helmstedt',
  'Herford',
  'Herne',
  'Hersfeld-Rotenburg',
  'Herzogtum Lauenburg',
  'Hildburghausen',
  'Hildesheim',
  'Hochsauerlandkreis',
  'Hochtaunuskreis',
  'Hof',
  'Hohenlohekreis',
  'Holzminden',
  'Höxter',
  'Ilm-Kreis',
  'Jena',
  'Jerichower Land',
  'Kaiserslautern',
  'Kamenz',
  'Karlsruhe',
  'Kassel',
  'Kelheim',
  'Kiel',
  'Kitzingen',
  'Kleve',
  'Koblenz',
  'Konstanz',
  'Krefeld',
  'Kronach',
  'Kulmbach',
  'Kusel',
  'Kyffhäuserkreis',
  'Köln',
  'Lahn-Dill-Kreis',
  'Landau in der Pfalz',
  'Landsberg am Lech',
  'Landshut',
  'Leer',
  'Leipzig',
  'Leverkusen',
  'Lichtenfels',
  'Limburg-Weilburg',
  'Lindau',
  'Lippe',
  'Ludwigsburg',
  'Ludwigshafen am Rhein',
  'Ludwigslust',
  'Löbau-Zittau',
  'Lörrach',
  'Lübeck',
  'Lüchow-Dannenberg',
  'Lüneburg',
  'Magdeburg',
  'Main-Kinzig-Kreis',
  'Main-Spessart',
  'Main-Tauber-Kreis',
  'Main-Taunus-Kreis',
  'Mainz',
  'Mainz-Bingen',
  'Mannheim',
  'Mansfeld-Südharz',
  'Marburg-Biedenkopf',
  'Mayen-Koblenz',
  'Mecklenburgische Seenplatte',
  'Meißen',
  'Memmingen',
  'Merzig-Wadern',
  'Mettmann',
  'Miesbach',
  'Miltenberg',
  'Minden-Lübbecke',
  'Mittweida',
  'Muldentalkreis',
  'Märkisch-Oderland',
  'Märkischer Kreis',
  'Mönchengladbach',
  'Mühldorf am Inn',
  'Mülheim an der Ruhr',
  'München',
  'Münster',
  'Neckar-Odenwald-Kreis',
  'Neuburg-Schrobenhausen',
  'Neumarkt in der Oberpfalz',
  'Neumünster',
  'Neunkirchen',
  'Neustadt an der Aisch-Bad Windsheim',
  'Neustadt an der Waldnaab',
  'Neustadt an der Weinstraße',
  'Neuwied',
  'Nienburg',
  'Nordfriesland',
  'Nordhausen',
  'Nordsachsen',
  'Nordvorpommern',
  'Nordwestmecklenburg',
  'Northeim',
  'Nürnberg',
  'Nürnberger Land',
  'Oberallgäu',
  'Oberbergischer Kreis',
  'Oberhausen',
  'Oberhavel',
  'Oberspreewald-Lausitz',
  'Odenwaldkreis',
  'Oder-Spree',
  'Offenbach',
  'Oldenburg',
  'Olpe',
  'Ortenaukreis',
  'Osnabrück',
  'Ostalbkreis',
  'Ostallgäu',
  'Osterholz',
  'Ostholstein',
  'Ostprignitz-Ruppin',
  'Ostvorpommern',
  'Paderborn',
  'Parchim',
  'Passau',
  'Peine',
  'Pfaffenhofen an der Ilm',
  'Pforzheim',
  'Pinneberg',
  'Pirmasens',
  'Plauen',
  'Plön',
  'Potsdam',
  'Prignitz',
  'Rastatt',
  'Ravensburg',
  'Recklinghausen',
  'Regen',
  'Regensburg',
  'Rems-Murr-Kreis',
  'Remscheid',
  'Rendsburg-Eckernförde',
  'Reutlingen',
  'Rhein-Erft-Kreis',
  'Rhein-Hunsrück-Kreis',
  'Rhein-Kreis Neuss',
  'Rhein-Lahn-Kreis',
  'Rhein-Neckar-Kreis',
  'Rhein-Pfalz-Kreis',
  'Rhein-Sieg-Kreis',
  'Rheingau-Taunus-Kreis',
  'Rhön-Grabfeld',
  'Riesa-Großenhain',
  'Rosenheim',
  'Rostock',
  'Rotenburg (Wümme)',
  'Roth',
  'Rottal-Inn',
  'Rottweil',
  'Rügen',
  'Saale-Holzland-Kreis',
  'Saale-Orla-Kreis',
  'Saalekreis',
  'Saalfeld-Rudolstadt',
  'Saarbrücken',
  'Saarlouis',
  'Saarpfalz-Kreis',
  'Salzgitter',
  'Salzlandkreis',
  'Schaumburg',
  'Schleswig-Flensburg',
  'Schmalkalden-Meiningen',
  'Schwalm-Eder-Kreis',
  'Schwandorf',
  'Schwarzwald-Baar-Kreis',
  'Schweinfurt',
  'Schwerin',
  'Schwäbisch Hall',
  'Segeberg',
  'Siegen-Wittgenstein',
  'Sigmaringen',
  'Soest',
  'Solingen',
  'Soltau-Fallingbostel',
  'Sonneberg',
  'Speyer',
  'Spree-Neiße',
  'St. Wendel',
  'Stade',
  'Starnberg',
  'Steinburg',
  'Steinfurt',
  'Stendal',
  'Stollberg',
  'Stormarn',
  'Stralsund',
  'Straubing-Bogen',
  'Stuttgart',
  'Suhl',
  'Sächsische Schweiz-Osterzgebirge',
  'Sömmerda',
  'Südliche Weinstraße',
  'Südwestpfalz',
  'Teltow-Fläming',
  'Tirschenreuth',
  'Torgau-Oschatz',
  'Traunstein',
  'Trier',
  'Trier-Saarburg',
  'Tuttlingen',
  'Tübingen',
  'Uckermark',
  'Uecker-Randow',
  'Uelzen',
  'Ulm',
  'Unna',
  'Unstrut-Hainich-Kreis',
  'Unterallgäu',
  'Vechta',
  'Verden',
  'Viersen',
  'Vogelsbergkreis',
  'Vogtlandkreis',
  'Vorpommern-Greifswald',
  'Vorpommern-Rügen',
  'Vulkaneifel',
  'Waldshut',
  'Warendorf',
  'Wartburgkreis',
  'Weilheim-Schongau',
  'Weimar',
  'Weimarer Land',
  'Weißenburg-Gunzenhausen',
  'Weißeritzkreis',
  'Werra-Meißner-Kreis',
  'Wesel',
  'Wesermarsch',
  'Westerwaldkreis',
  'Wetteraukreis',
  'Wiesbaden',
  'Wilhelmshaven',
  'Wittenberg',
  'Wittmund',
  'Wolfenbüttel',
  'Wolfsburg',
  'Worms',
  'Wunsiedel im Fichtelgebirge',
  'Wuppertal',
  'Würzburg',
  'Zollernalbkreis',
  'Zweibrücken',
  'Zwickau',
];
