import os


WEB_PUSH_VAPID_PUBLIC_KEY = os.getenv("WEB_PUSH_VAPID_PUBLIC_KEY", "").strip()
WEB_PUSH_VAPID_PRIVATE_KEY = os.getenv("WEB_PUSH_VAPID_PRIVATE_KEY", "").strip()
WEB_PUSH_VAPID_SUBJECT = os.getenv("WEB_PUSH_VAPID_SUBJECT", "").strip()
WEB_PUSH_SUBSCRIPTION_ENCRYPTION_KEY = os.getenv(
    "WEB_PUSH_SUBSCRIPTION_ENCRYPTION_KEY", ""
).strip()
