export const REKLAMA_A_PR: string[] = [
  'Tvorba reklamných kampaní',
  'Strategické plánovanie kampaní',
  'Brand building a rozvoj značky',
  'Konzultácie a marketingové poradenstvo',
  'Správa sociálnych médií',
  'Content marketing a tvorba obsahu',
  'Copywriting a reklamné texty',
  'Tvorba vizuálov a grafický dizajn pre reklamu',
  'Video reklama a motion graphics',
  'Influencer marketing a spolupráce',
  'PR stratégie a komunikácia s médiami',
  'Public relations pre firmy a značky',
  'Tlačové správy a mediálne komuniké',
  'Event PR a mediálna podpora podujatí',
  'Crisis management a krízová komunikácia',
  'Monitoring médií a analýza zmienok',
  'Tvorba a správa webových stránok',
  'SEO a optimalizácia online obsahu',
  'PPC kampane a online reklama',
  'Email marketing a newslettery',
  'Reklamné bannery a display reklama',
  'Outdoor reklama a billboardy',
  'Guerilla marketing a netradičné kampane',
  'Reklama v rádiu a televízii',
  'Podcast a audio marketing',
  'Brand ambassador programy',
  'Marketingová komunikácia pre startupy',
  'Tvorba reklamných kampaní pre e-commerce',
  'Analytika a reporting kampaní',
  'Tvorba marketingových stratégii a plánov',
  'Tvorba obsahu pre blogy a články',
  'Sociálne kampane a awareness projekty',
  'Kreatívne koncepty a vizuálne identity',
  'Influencer a celebrity endorsement kampane',
  'Video a fotografická produkcia pre reklamu',
  'PR pre kultúrne a spoločenské podujatia',
  'Community management a interakcia so zákazníkmi',
  'Tvorba a distribúcia reklamných materiálov',
  'Marketingové konzultácie pre malé a stredné firmy',
  'Marketing automation a personalizovaná komunikácia',
  'Strategická komunikácia a positioning značky',
  'Employer branding a interná komunikácia',
  'Storytelling a brand narratives',
  'Mediálna stratégia a plánovanie',
  'Reklama na sociálnych sieťach (Facebook, Instagram, TikTok, LinkedIn)',
  'Tvorba vizuálnych kampaní a grafických materiálov',
  'Influencer management a spolupráce',
  'Publicity a promo akcie',
  'Marketingové analýzy a prieskum trhu',
  'Tvorba kampaní pre digitálne platformy',
  'Native advertising a sponzorovaný obsah',
  'Kreatívne kampane pre digitálny marketing',
  'Marketingové eventy a promo eventy',
  'Storyboard a scenáre pre reklamy',
  'Reklama a PR pre produktové launchy',
  'Správa reputácie značky online aj offline',
  'Konzultácie a školenia v oblasti reklamy a PR',
  'Tvorba PR materiálov (press kits, médiá, články)',
  'Spolupráca s mediálnymi partnermi',
  'Strategické poradenstvo v komunikácii',
  'Tvorba kampaní pre zvýšenie predaja a konverzií',
  'Online a offline propagácia značky',
  'Kreatívne stratégie a vizuálne koncepty',
  'Vývoj komunikácie pre rôzne cieľové skupiny',
  'Správa influencer kampaní a hodnotenie výkonu',
  'Koordinácia reklamných a PR projektov',
  'Krízová komunikácia a reputačný manažment',
  'Analýza dosahu kampaní a meranie KPI',
  'Content planning a editorial kalendáre',
  'Digitálne kampane a programatická reklama',
  'Tvorba animácií a vizuálnych efektov pre reklamu',
  'PR pre startupy a nové produkty',
  'Strategické poradenstvo pre budovanie značky',
  'Tvorba kreatívnych kampaní pre sociálne médiá',
  'Community building a angažovanie publika',
  'Vývoj vizuálneho a obsahového marketingu',
  'PR pre eventy, festivaly a spoločenské akcie',
  'Správa online reputácie a recenzií',
  'Tvorba multimediálneho obsahu pre marketing a PR',
  'Poradenstvo pri komunikácii s cieľovými skupinami',
  'Mediálne tréningy a príprava hovorcov',
  'Marketingová a PR stratégia pre digitálne kanály',
  'Influencer spolupráce a hodnotenie ROI kampaní',
  'Spolupráca s agentúrami a externými partnermi',
  'Kreatívne koncepty a vizuálna identita pre kampane',
  'Správa reklamných a PR rozpočtov',
  'Marketingová komunikácia pre B2B a B2C segmenty',
  'Tvorba PR kampaní pre produkty, služby a značky',
  'Monitoring a reporting mediálneho pokrytia a dosahu',
];

