export const KRASA_A_ZDRAVIE: string[] = [
  'Kadernícke služby',
  'Strihanie vlasov',
  'Farbenie a melírovanie',
  'Trvalá ondulácia',
  'Regenerácia vlasov',
  'Fúkaná a styling',
  'Účesy na spoločenské udalosti',
  'Barber služby',
  'Starostlivosť o fúzy a bradu',
  'Holenie a tvarovanie',
  'Kozmetické služby',
  'Čistenie pleti',
  'Hĺbkové ošetrenie pleti',
  'Masáže tváre',
  'Lifting a omladzovacie procedúry',
  'Ošetrenie akné',
  'Líčenie',
  'Make-up na svadby, oslavy, fotenie',
  'Permanentný make-up',
  'Úprava obočia a mihalníc',
  'Laminácia obočia',
  'Predlžovanie mihalníc',
  'Farbenie obočia a mihalníc',
  'Depilácia voskom alebo cukrovou pastou',
  'Epilácia laserom',
  'Manikúra',
  'Klasická manikúra',
  'Gélové nechty',
  'Akrylové nechty',
  'Lakovanie a nail art',
  'Starostlivosť o nechtové lôžko',
  'Parafínové zábaly na ruky',
  'Pedikúra',
  'Klasická pedikúra',
  'Medicinálna pedikúra',
  'Gél na nechty na nohách',
  'Masáž nôh',
  'Starostlivosť o stvrdnutú pokožku',
  'Masáže tela',
  'Klasická masáž',
  'Relaxačná masáž',
  'Športová masáž',
  'Thajská masáž',
  'Lymfodrenáž',
  'Aromaterapeutická masáž',
  'Reflexná masáž chodidiel',
  'Masáž lávovými kameňmi',
  'Bankovanie',
  'Fyzioterapia',
  'Rehabilitácia po úrazoch',
  'Cviky na chrbticu',
  'Kineziotaping',
  'Korekcia držania tela',
  'Cvičenie pre seniorov',
  'Zdravotné cvičenia',
  'Jóga',
  'Pilates',
  'Strečing',
  'Dýchacie cvičenia',
  'Meditácia',
  'Masážne techniky pre uvoľnenie stresu',
  'Fitness tréning',
  'Osobný tréner',
  'Silový tréning',
  'Kardio tréning',
  'Kruhový tréning',
  'Funkčný tréning',
  'Tréning s vlastnou váhou',
  'Online tréningy',
  'Poradenstvo vo výžive',
  'Tvorba jedálnička',
  'Analýza stravovacích návykov',
  'Výživové doplnky a poradenstvo',
  'Redukčné programy',
  'Naberanie svalovej hmoty',
  'Detox programy',
  'Psychológia a duševné zdravie',
  'Koučing a mentoring',
  'Terapia a poradenstvo',
  'Relaxačné techniky',
  'Mindfulness',
  'Arteterapia',
  'Zvuková terapia',
  'Aromaterapia',
  'Bylinkárstvo',
  'Výroba prírodnej kozmetiky',
  'Domáca výroba mydiel a balzamov',
  'Masážne oleje a sviečky',
  'Starostlivosť o telo prírodnými produktmi',
  'Wellness služby',
  'Sauna',
  'Kryoterapia',
  'Hydromasáže',
  'Zábalové procedúry',
  'Bahenné a minerálne kúry',
  'Omladzovacie kúry',
  'Starostlivosť o pleť a telo v salóne',
  'Estetické služby',
  'Neinvazívne omladzovanie',
  'Mezoterapia',
  'Botox a výplne',
  'Chemický peeling',
  'Mikrodermabrázia',
  'Laserové ošetrenie pleti',
  'Ošetrenie pigmentových škvŕn',
  'Tetovanie a piercing',
  'Tetovanie obočia, pier, tela',
  'Piercing uší, nosa, pupka',
  'Starostlivosť po tetovaní',
  'Odstraňovanie tetovaní',
  'Starostlivosť o telo po zákrokoch',
  'Rehabilitačné cvičenia',
  'Starostlivosť o jazvy a pokožku',
  'Správne držanie tela',
  'Regenerácia po športe',
  'Masáže po výkone',
  'Wellness pobyty a relax programy',
  'Poradenstvo v oblasti zdravého životného štýlu',
  'Zdravotná diagnostika',
  'Meranie tlaku, cukru, BMI',
  'Analýza telesného zloženia',
  'Prevencia chorôb',
  'Edukácia o zdraví a životospráve',
];


