export const REMESLA_A_VYROBA: string[] = [
  'Stolárstvo / výroba nábytku',
  'Rezanie a tvarovanie dreva',
  'Lepenie a spojovanie drevených komponentov',
  'Lakovanie / morenie dreva',
  'Opravy a rekonštrukcia nábytku',
  'Karosárske práce',
  'Zváranie kovov',
  'Kovospracovanie (kovanie, frézovanie, sústruženie)',
  'Výroba nástrojov a matríc (tool & die making)',
  'Liatie kovov',
  'Povrchová úprava kovových dielov',
  'Kováčstvo',
  'Výroba šperkov / zlatníctvo',
  'Opracovanie drahých kovov (zlato, striebro)',
  'Výroba kožených výrobkov (tašky, opasky, sedlá)',
  'Kožušinárstvo / spracovanie kože',
  'Výroba a oprava topánok',
  'Tkanie a textilné remeslá',
  'Pletenie, háčkovanie',
  'Výroba čiapok / klobúkov (millerstvo)',
  'Výroba košov / prútie väzba',
  'Výroba papiera / kníhviazanie / bookbinding',
  'Výroba sviečok',
  'Výroba keramiky / kameniny',
  'Glazovanie a vypaľovanie keramických výrobkov',
  'Výroba skla (fúkané sklo, tavené sklo)',
  'Mozaiky, obklady, dlažby',
  'Stavebné remeslá (murárstvo, omietky, obklady)',
  'Obklady, dlažby, kachličky',
  'Výroba nástrojov z dreva alebo kovu',
  'Renovácia historických budov / architektonické remeslá',
  'Výroba a inštalácia podláh / parkiet',
  'Oprava a údržba mechanizmov',
  'Spracovanie plastov / vstrekovanie plastov',
  'Montáž strojov / výrobných zariadení',
  'Údržba výrobných liniek',
  'Balenie a finálna úprava výrobkov',
  'Grafické potlače a dekoratívne povrchy',
  'Výroba doplnkov (domáce dekorácie, kancelárske potreby)',
  'Oprava a výroba hudobných nástrojov (luthierstvo)',
  'Výroba rukavíc / výroba odevov / šitie na mieru',
  'Spracovanie korku / výroba korkových výrobkov',
  'Výroba prírodných vlákien / plátenné výrobky',
  'Výroba šindľov, tradičné strešné krytiny',
  'Výroba nábytku z bambusu / bambusové remeslá',
  'Výroba a spracovanie drevených strojov (vodné mlyny, píly)',
  'Výroba dekoratívnych predmetov (sochy, reliéfy)',
  'Výroba hračiek / remeselné hračky',
  'Výroba predmetov z papiera / kartónu',
  'Výroba a oprava hodiniek / mechanických zariadení',
  'Výroba skiel a ich oprava (rezanie, brúsenie)',
  'Výroba optických zariadení / optotechnológie',
  'Opracovanie prírodného kameňa / kamenárstvo',
  'Opracovanie dreva na náradie a dekoračné predmety',
  'Výroba domácich potrieb (nocné stolíky, police, rámy)',
  'Strojové obrábanie (CNC, frézovanie, sústruženie)',
  'Spracovanie kompozitných materiálov',
  'Výroba elektrotechnických komponentov (montáž, pouzdrovanie)',
  'Výroba izolácií a izolačných materiálov',
  'Výroba textilných doplnkov (koberce, tapisérie)',
  'Údržba a renovácia historických mechanických zariadení',
  'Výroba tradičných remeselných produktov (regionálne ľudové remeslá)',
  'Spracovanie sklenených vlákien / laminátov',
  'Výroba produktov z recyklovaných materiálov',
  'Remeslá so zameraním na udržateľnosť / ekologické materiály',
  'Výroba a úprava drevených lodí / člnov',
  'Výroba remeňov a pásov pre strojné zariadenia',
  'Výroba keramických obkladov a dlažieb na mieru',
  'Výroba náradia pre iné remeslá (šablóny, formy)',
  'Výroba a údržba tepelno-izolačných systémov',
  'Výroba dlažobných prvkov z prírodného materiálu',
  'Výroba a montáž drevených štruktúr (trámy, krovy)',
  'Výroba a oprava mechanických hodín a hodinárskych dielov',
  'Výroba doplnkov do interiéru (svietniky, rámy z kovu/dreva)',
  'Výroba stavebných prvkov z dreva (okná, dvere, schody)',
  'Výroba kovových konštrukcií (zábradlia, brány)',
  'Výroba a montáž strojov na výrobu (výrobné linky)',
  'Výroba plastových komponentov (vstrekovanie, lisovanie)',
  'Výroba komerčných kuchynských a domáceho vybavenia (drez, linka)',
  'Výroba kovových nábytkových prvkov (skříně, regály)',
  'Výroba zvukových izolácií a akustických panelov',
  'Oprava a výroba tradičných nástrojov (kroje, drevené náradie)',
  'Výroba ručných nástrojov (kladivá, skrutkovače)',
  'Výroba a montáž automatických systémov (vs. výroba ručne)',
  'Výroba gumených a kaučukových výrobkov',
  'Výroba skiel a zrkadiel',
  'Výroba organizérov a úložných systémov (skrinky, boxy)',
  'Výroba a úprava výrobkov z bambusu, prútia, rohoží',
  'Ručná výroba personalizovaných produktov (gravírovanie, rytie)',
  'Výroba keramických sanitárnych výrobkov (umývadlá, vane)',
  'Výroba outdoorového nábytku / terasových prvkov',
  'Výroba svietidiel a osvetľovacích telies',
  'Výroba remeselného skla a krištáľu',
  'Výroba dekoratívnych kachličiek / mozaikových panelov',
  'Výroba a inštalácia systémov na spracovanie odpadu / recyklácie v remeselnej výrobe',
  'Výroba konzol pre 3D tlač a výroba prototypov',
  'Výroba nástrojov pre výuku remesiel (trenažéry, vzorové diely)',
  'Výroba a oprava bicyklov / mechanických dopravných prostriedkov',
  'Výroba remeselných doplnkov pre zvieratá (napr. klietky, búdy)',
  'Výroba ručných domácich spotrebičov (napr. ručné mixéry, stolné lampy)',
  'Výroba drevených hier a puzzle',
  'Výroba interiérových a exteriérových drevených prvkov (ploty, terasy, altánky)',
  'Výroba dielov pre tradičné hudobné nástroje (kovové, drevené)',
  'Výroba textilných doplnkov (šály, rukavice)',
  'Výroba obuvníckych komponentov (podrážky, stielky)',
  'Výroba nástrojov pre záhradnú architektúru (napr. lavičky, altánky)',
  'Výroba keramických dekorácií (vázy, sochy)',
  'Výroba a spracovanie plástov / včelích produktov (napr. voskové sviečky)',
  'Výroba a oprava optických skiel (okuliare, šošovky)',
  'Výroba a oprava hodinových mechanizmov a smontovanie hodinových dielov',
  'Výroba ručných mehānizmov a hodinových strojov (napr. mechanické hodiny)',
  'Výroba stavebných doplnkov z kovu/dreva (zábradlia, lišty)',
  'Výroba relikvií a umeleckých kovových predmetov (napr. medaile, plastiky)',
  'Výroba reprografických tlačových foriem (napr. raznice)',
  'Výroba personalizovaných darčekových predmetov (gravírovanie, výrábanie podľa objednávky)',
  'Výroba remeselných svetelných inštalácií (napr. svietidlá v umeleckom štýle)',
  'Zmontovanie a finalizácia výrobku (kontrola, balenie, expedícia)',
  'Spravovanie výroby a workflow v malovýrobe',
  'Valorizácia a doplnkový servis výrobku (údržba, oprava, renovácia)',
];


