export const KUTILSTVO_A_DIY_PROJEKTY: string[] = [
  'Drevoobrábanie a stolárske projekty',
  'Kovospracovanie a zváranie',
  'Opravy a údržba domácnosti',
  'Stavba nábytku a políc',
  'Renovácia a restaurovanie nábytku',
  'Maľovanie a dekorovanie',
  'Vnútorné a vonkajšie dekorácie',
  'Záhradné projekty a úprava exteriéru',
  'DIY záhradné doplnky',
  'Výroba dekorácií a handmade predmetov',
  'Kreatívne projekty z papiera a kartónu',
  'Šitie, pletenie a háčkovanie',
  'Výroba textilných dekorácií',
  'Výroba sviečok a mydiel',
  'Kreatívne projekty s recyklovanými materiálmi',
  'Modelárstvo a miniatury',
  'Elektronické DIY projekty',
  'Arduino a microcontroller projekty',
  'Robotika pre hobby a školské projekty',
  'Výroba domácich kozmetických produktov',
  'Kreatívne projekty s drevom a kovom',
  'Tvorba šperkov a doplnkov',
  'Výroba hračiek a hier',
  'Domáce opravárske a údržbárske práce',
  'Inštalácia a montáž nábytku',
  'Montáž a oprava zariadení a spotrebičov',
  'Vytváranie vlastných darčekov a suvenírov',
  'Kreatívne projekty s farbami a lakmi',
  'Výroba organizérov a úložných riešení',
  'DIY projekty pre deti a rodinu',
  'Domáce opravárske návody a tutoriály',
  'Tvorba personalizovaných dekorácií',
  'Kutilské nástroje a ich použitie',
  'Opravy bicyklov a doplnkov',
  'Domáce elektronické projekty',
  'DIY nástroje a pomôcky',
  'Domáce stavby a rekonštrukcie',
  'Malé domáce stolárske projekty',
  'Kreatívne recyklačné projekty',
  'Výroba nástrojov a doplnkov na záhradu',
  'Záhradný nábytok a dekorácie',
  'Výroba svetelných dekorácií a lampášov',
  'Domáce projekty s využitím 3D tlače',
  'Tvorba personalizovaného interiéru',
  'DIY projekty pre sezónne a sviatočné dekorácie',
  'Kreatívne balenie darčekov',
  'Domáce opravárske projekty pre kuchyňu a kúpeľňu',
  'Renovácia starých predmetov a nábytku',
  'Výroba domácich stojanov a držiakov',
  'DIY organizácia domácnosti',
  'Kreatívne projekty s prírodnými materiálmi',
  'Výroba vlastných dekoratívnych predmetov',
  'Projektovanie a stavba malých drevených stavieb',
  'Kutilské workshopy a kurzy',
  'DIY návodové videá a online tutoriály',
  'Kreatívne a umelecké projekty pre hobby',
  'Tvorba personalizovaných doplnkov do domácnosti',
  'Výroba záhradných dekorácií a nábytku',
  'DIY projekty pre zlepšenie komfortu a funkčnosti domácnosti',
  'Výroba doplnkov do kuchyne a jedálne',
  'DIY projekty pre interiérový dizajn',
  'Údržba a opravy domácich spotrebičov',
  'Kreatívne projekty pre školské a vzdelávacie účely',
  'Tvorba originálnych darčekov a handmade výrobkov',
  'Výroba nábytku a doplnkov z recyklovaných materiálov',
  'DIY projekty pre zábavu a relaxáciu',
  'Kombinované projekty drevo-kov-plast',
  'Projektovanie a realizácia hobby dielní',
  'Tvorba multifunkčných a praktických riešení do domácnosti',
  'DIY projekty pre deti a mládež',
  'Výroba vlastných nástrojov a pomôcok',
  'Kreatívne projekty z papiera, látok a iných materiálov',
  'DIY projekty s použitím elektroniky a smart technológií',
  'Renovácia a personalizácia starých predmetov a nábytku',
  'Kreatívne projekty pre sezónne dekorácie a sviatky',
  'Domáce DIY projekty pre hobby a zábavu',
  'Tvorba interaktívnych a funkčných predmetov pre domácnosť',
];

