export const EKOLOGIA_A_UDRZATELNY_ZIVOT: string[] = [
  'Recyklácia a separovanie odpadu',
  'Kompostovanie a tvorba hnojív',
  'Znižovanie plastov a jednorazových materiálov',
  'Zero waste a minimalizmus',
  'Šetrenie energie a efektívne využitie zdrojov',
  'Solárna a obnoviteľná energia',
  'Vodohospodárstvo a šetrenie vody',
  'Udržateľné bývanie a ekologické stavby',
  'Mestská a komunitná záhrada',
  'Pestovanie vlastnej zeleniny a ovocia',
  'Organické a ekologické záhradníctvo',
  'Ochrana biodiverzity a prírody',
  'Ekoturistika a zodpovedné cestovanie',
  'Ochrana ohrozených druhov a biotopov',
  'Eko doprava a alternatívne dopravné prostriedky',
  'Minimalizácia uhlíkovej stopy',
  'Udržateľná móda a textílie',
  'Ekologické čistiace a domácnosti produkty',
  'Podpora lokálnych a ekologických výrobkov',
  'Edukácia a environmentálne vzdelávanie',
  'Klimatické akcie a aktivizmus',
  'Udržateľné potraviny a stravovanie',
  'Biologicky odbúrateľné produkty',
  'Zelené technológie a inovácie',
  'Ochrana lesov a zalesňovanie',
  'Prevencia znečistenia ovzdušia a vody',
  'Udržateľné podnikanie a CSR iniciatívy',
  'Domáce a komunitné recyklačné projekty',
  'Energetická efektívnosť budov',
  'Udržateľná doprava a cyklistika',
  'Zelené strechy a vertikálne záhrady',
  'Alternatívne zdroje energie (veterné, geotermálne)',
  'Zníženie odpadu v potravinárstve',
  'Ochrana pôdy a prevencia erózie',
  'Udržateľná výroba a spotreba',
  'Podpora ekologických iniciatív a projektov',
  'Environmentálne dobrovoľníctvo',
  'Zodpovedný spotrebiteľský prístup',
  'Energetická nezávislosť a domácna výroba energie',
  'Klimatická adaptácia a prevencia rizík',
  'Odolnosť komunít voči environmentálnym zmenám',
  'Ekologické stavby a stavebné materiály',
  'Voda a odpadové hospodárstvo',
  'Znižovanie chemických látok a pesticídov',
  'Ochrana a regenerácia miestnych ekosystémov',
  'Edukačné programy pre školy a komunity',
  'Podpora environmentálnych iniciatív v biznise',
  'Udržateľné produkty a etiketa fair trade',
  'Circular economy – uzatváranie materiálových cyklov',
  'Lokálna produkcia a spotreba potravín',
  'Biologická rozmanitosť a ochrana zvierat',
  'Energetická efektívnosť a smart domácnosti',
  'Eko dizajn a udržateľné produkty',
  'Alternatívne dopravné prostriedky (elektromobily, kolobežky)',
  'Preventívne opatrenia proti klimatickým zmenám',
  'Podpora komunitných projektov a lokálnych iniciatív',
  'Ekologické kampane a osveta',
  'Výskum a inovácie pre udržateľný rozvoj',
  'Environmentálne štandardy a certifikácie',
  'Zodpovedný lov a rybolov',
  'Ochrana oceánov a sladkovodných ekosystémov',
  'Udržateľné záhradníctvo a permakultúra',
  'Komunitná výsadba stromov a zeleni',
  'Predchádzanie odpadom a opätovné použitie materiálov',
  'Vzdelávacie eko-workshopy a semináre',
  'Energetická udržateľnosť firiem a domácností',
  'Domáce solárne a alternatívne systémy',
  'Monitoring a ochrana kvality ovzdušia a vody',
  'Podpora lokálnych ekologických iniciatív a podnikania',
  'Eko aplikácie a digitálne nástroje pre udržateľný život',
  'Komunitné projekty pre ochranu životného prostredia',
  'Zelené financie a investície do udržateľných projektov',
  'Podpora environmentálne zodpovedných politík',
  'Recyklácia elektroniky a technológií',
  'Znižovanie odpadov v domácnosti a komunite',
  'Podpora alternatívnych zdrojov energie a smart grid',
  'Ochrana prírodných rezervácií a parkov',
  'Edukácia o klimatických zmenách a globálnom otepľovaní',
  'Zapájanie komunít do ekologických aktivít a dobrovoľníctva',
  'Environmentálne certifikácie a značky udržateľnosti',
];

