export const ECOMMERCE_A_ONLINE_PREDAJ: string[] = [
  'Tvorba a správa e-shopov',
  'Produktový listing a katalogizácia',
  'Optimalizácia produktových stránok',
  'Fotografia a prezentácia produktov',
  'Popisy produktov a copywriting',
  'Cenotvorba a manažment cien',
  'Správa skladov a inventúry',
  'Logistika a doprava tovaru',
  'Platobné brány a online platby',
  'Fakturácia a účtovníctvo',
  'Customer support a zákaznícka podpora',
  'Správa objednávok a reklamácií',
  'E-mail marketing a newslettery',
  'Sociálne siete a reklama (Facebook, Instagram, TikTok)',
  'SEO pre e-commerce',
  'PPC kampane a online reklama',
  'Remarketing a retargeting',
  'Affiliate marketing a partnerstvá',
  'Influencer marketing',
  'Tvorba a správa kampaní na marketplace (Amazon, eBay, Alza, Heureka)',
  'Dropshipping a fulfillment služby',
  'Analytika a reporting predaja',
  'Webová analytika (Google Analytics, Hotjar)',
  'Testovanie a UX optimalizácia e-shopu',
  'A/B testovanie',
  'Konverzný funnel a optimalizácia nákupného procesu',
  'Správa recenzií a hodnotení produktov',
  'Content marketing a blog pre e-shop',
  'Video marketing a produktové videá',
  'Live commerce a online prezentácie produktov',
  'CRM a správa zákazníckych dát',
  'Automatizácia marketingu a predaja',
  'Loyalty programy a vernostné systémy',
  'Správa kampaní na Google Shopping',
  'Marketplace management a optimalizácia predaja',
  'Integrácia e-shopu s ERP a ďalšími systémami',
  'Právne a daňové poradenstvo pre online predaj',
  'GDPR a ochrana osobných údajov zákazníkov',
  'Customer experience a UX dizajn e-shopu',
  'Mobilné aplikácie pre online predaj',
  'Omnichannel stratégie',
  'International e-commerce a predaj do zahraničia',
  'Trendy v e-commerce a nové technológie',
  'Chatboty a AI asistenti pre e-shop',
  'Sociálne dôkazy a recenzie produktov',
  'Video tutoriály a návody pre zákazníkov',
  'Eventy a live predaj online',
  'Správa reklamných bannerov a promo akcií',
  'Tvorba obsahových kampaní pre e-shop',
  'Influencer spolupráce a brand ambassadors',
  'Príprava produktových launchov',
  'Remarketing na sociálnych sieťach a Google',
  'Predikcia predaja a plánovanie zásob',
  'Analýza správania zákazníkov a segmentácia',
  'Marketingové automaty a retencia zákazníkov',
  'Integrácia s dopravcami a sledovanie zásielok',
  'Predaj digitálnych produktov',
  'Predaj služieb online',
  'Subscription a predplatné služby',
  'Správa promo kódov a zliav',
  'Správa affiliate a partnerských programov',
  'E-commerce consulting a poradenstvo',
  'Tvorba e-shop stratégie a plánovanie expanzie',
  'Správa online kampaní na rôznych platformách',
  'E-commerce fotografie a produktový vizuál',
  'Video marketing a animácie produktov',
  'UX/UI design pre e-shopy a mobilné aplikácie',
  'Správa inventúry a skladového hospodárstva',
  'Analytika predajných kanálov a optimalizácia konverzií',
  'Testovanie platobných procesov a checkout flow',
  'Customer journey mapping a zlepšenie nákupného procesu',
  'Správa a optimalizácia newsletter kampaní',
  'Tvorba obsahu a marketingový storytelling',
  'Prieskum trhu a analýza konkurencie',
  'Vývoj a implementácia vernostných programov',
  'Influencer a micro-influencer spolupráce',
  'Optimalizácia rýchlosti a výkonu e-shopu',
  'Správa viacerých predajných kanálov a marketplace integrácií',
  'Podpora zákazníkov cez chat a call centrum',
  'Automatizované riešenia a AI pre predaj a marketing',
  'Strategické plánovanie predaja a expanzie na nové trhy',
  'Branding a vizuálna identita online predaja',
  'Merchandising a vizuálna prezentácia produktov',
  'Organizovanie online eventov a promo akcií',
  'Analýza a reporting KPI pre e-commerce projekty',
  'Testovanie a zavádzanie nových predajných kanálov',
  'Správa digitálnych reklamných kampaní a rozpočtov',
];

