export const ZABAVA_A_HRY: string[] = [
  'Stolové hry',
  'Kartové hry',
  'Logické a strategické hry',
  'Hádanky a kvízy',
  'Puzzle',
  'Spoločenské hry',
  'Hry na párty',
  'Video hry',
  'Počítačové hry',
  'Konzolové hry',
  'Mobilné hry',
  'Online multiplayer hry',
  'E-sport',
  'Herné turnaje',
  'Simulačné hry',
  'RPG a D&D hry',
  'Akčné hry',
  'Adventúry',
  'Sandbox hry',
  'Hry s rozšírenou realitou (AR)',
  'Hry s virtuálnou realitou (VR)',
  'Kreatívne hry',
  'Stavanie a budovanie',
  'Dizajn postáv a svetov',
  'Hry s interaktívnym príbehom',
  'Únikové hry a escape rooms',
  'Hry v prírode',
  'Lov a hľadanie pokladov (geocaching)',
  'Športové hry a súťaže',
  'Fitness hry',
  'Tanečné hry',
  'Hry s fyzickou aktivitou',
  'Hry pre deti',
  'Edukačné hry',
  'Rozvoj zručností a talentov',
  'Hračky a stavebnice',
  'LEGO a stavebné sety',
  'Kreatívne dielne a workshopy',
  'Maľovanie a kreslenie hier',
  'Hudobné hry',
  'Karaoke',
  'Hudobné súťaže',
  'Hudobné kvízy',
  'Tvorba vlastných hier',
  'Programovanie hier',
  'Testovanie a beta hry',
  'Hry na stolný tenis',
  'Hry na šach a dáma',
  'Hry na športové simulácie',
  'Roleplay a improvizačné hry',
  'Aktivity pre skupiny a team building',
  'Kostýmové hry a cosplay',
  'Rekreačné a oddychové hry',
  'Hry na pláži a v prírode',
  'Hry s loptičkami a loptami',
  'Outdoor adventure hry',
  'Skauting a dobrodružné hry',
  'Hry s pravidlami a scénármi',
  'Kreatívne výzvy a súťaže',
  'Súťaže v spoločenských aktivitách',
  'Online streaming herného obsahu',
  'Twitch a YouTube hranie',
  'Herné recenzie a blogy',
  'Vývoj herných komunít',
  'Organizácia herných eventov a festivalov',
  'LAN párty a herné stretnutia',
  'Turnaje v e-športe',
  'Súťažné hranie s prize poolom',
  'Hry so spoločenským dopadom',
  'Edukačné a environmentálne hry',
  'Hry na budovanie tímu a spolupráce',
  'Strategické simulácie',
  'Real-time stratégie',
  'Hry s tvorbou obsahu (sandbox a creative mode)',
  'Hry s online rankingom a ligami',
  'Tvorba fanartov a fanfikcií k hrám',
  'Hry s rozšírenou komunitou a modifikáciami',
  'Hry so zvieratami a virtuálnymi domácimi miláčikmi',
  'Hry pre zábavu a relax',
  'Hry s humorom a paródiou',
  'Party videohry',
  'Interaktívne show a eventy',
  'Hry na festivaloch a verejných akciách',
  'Hry pre detské oslavy a oslavy narodenín',
  'Súťaže v tvorivosti a kreativite',
  'Kvízové show a súťaže',
  'Rýchlostné a reflexné hry',
  'Multiplayer kooperatívne hry',
  'Hry s digitálnymi kartami',
  'Hry s fyzikálnymi experimentmi',
  'Hry s mechanickými prvkami a gadgetmi',
  'Hry s rozprávaním príbehu',
  'Výzvy a challenge aktivity',
  'Hry s virtuálnymi svetmi a metaverzumom',
  'Tvorba scenára a herných svetov',
  'Hry s NPC a interaktívnymi postavami',
  'Vývoj indie hier',
  'Testovanie a QA hier',
  'Herné prototypovanie',
  'Beta testovanie a spätná väzba',
  'Participácia na herných fórach a komunitách',
  'Online turnaje a ligy',
  'Hranie hier pre charitu',
  'Herné výzvy na sociálnych sieťach',
  'Hry s augmented reality zážitkom',
  'Mix reality a hybridné hry',
  'Hry s mobilnou GPS integráciou',
  'Lokálne multiplayerové hry',
  'Hry pre seniorov a špeciálne skupiny',
  'Mentoring a vedenie herných komunít',
  'Edukačné workshopy na tému hier a gamifikácie',
];

