export const EVENTY_A_ORGANIZACIA_PODUJATI: string[] = [
  'Organizovanie konferencií a seminárov',
  'Firemné eventy a teambuilding',
  'Workshopy a školenia',
  'Kultúrne podujatia a festivaly',
  'Hudobné koncerty a vystúpenia',
  'Divadelné predstavenia a show',
  'Vernisáže a výstavy',
  'Otvorenia a launch eventy',
  'Sportové podujatia a turnaje',
  'Súťaže a olympiády',
  'Networkingové stretnutia',
  'Charitatívne a benefičné akcie',
  'Gala večere a spoločenské udalosti',
  'Rodinné a súkromné oslavy',
  'Svadby a hostiny',
  'Narodeninové oslavy a party',
  'Firemné večierky a recepcie',
  'Outdoor eventy a pikniky',
  'Témy a tematické večery',
  'Festivaly jedla a nápojov',
  'Degustácie a ochutnávky',
  'Kreatívne a umelecké workshopy',
  'Prezentácie a prednášky',
  'Team building aktivity a zážitkové programy',
  'Eventová logistika a koordinácia',
  'Rezervácia priestorov a vybavenie techniky',
  'Catering a občerstvenie na eventoch',
  'Technická podpora a AV vybavenie',
  'Dekorácie a scénografia',
  'Program a harmonogram podujatia',
  'Registrácia účastníkov a ticketing',
  'Propagácia a marketing podujatí',
  'Social media a online promotion',
  'Partnerstvá a sponzoring',
  'Správa účastníckych zoznamov',
  'Bezpečnostné a hygienické opatrenia',
  'Koordinácia dobrovoľníkov a personálu',
  'Riadenie prítomnosti hostí a VIP hostí',
  'Hostesing a eventová asistencia',
  'Fotografia a videodokumentácia podujatia',
  'Tvorba eventových materiálov (pozvánky, programy)',
  'Merchandising a promo materiály',
  'Hodnotenie a spätná väzba z podujatia',
  'Follow-up a reporting',
  'Event management software a nástroje',
  'Krízové riadenie a plánovanie rizík',
  'Tvorba tematických konceptov a scenárov',
  'Event design a experience design',
  'Umenie a kreatívna réžia eventov',
  'Výroba stage a scenických prvkov',
  'Hudobná a zvuková produkcia',
  'Osvetlenie a vizuálne efekty',
  'Koordinácia s dodávateľmi a partneri',
  'Logistika dopravy a parkovania',
  'Ubytovanie pre účastníkov',
  'Správa vstupeniek a registrácií online',
  'Interaktívne a gamifikované eventy',
  'Hybridné a online eventy',
  'Live streaming a digitálne eventy',
  'Moderovanie a hostovanie podujatí',
  'Príprava scenára a programového plánu',
  'Organizácia súťaží a aktivít počas eventu',
  'Event consulting a poradenstvo',
  'Strategické plánovanie eventov',
  'Rozpočet a finančné riadenie podujatí',
  'Koordinácia VIP a hostiteľských služieb',
  'Tvorba zážitkových a imerzívnych eventov',
  'Vývoj tematických konceptov pre klientov',
  'Riadenie logistických a technických tímov',
  'Monitorovanie a hodnotenie úspešnosti eventu',
  'Organizovanie outdoor festivalov a verejných podujatí',
  'Kreatívna koordinácia programov a aktívneho obsahu',
  'Podpora a komunikácia s médiami',
  'Marketingové kampane k eventom',
  'Influencer marketing a spolupráce pri eventoch',
  'Integrácia digitálnych a interaktívnych prvkov',
  'Storytelling a vizuálna komunikácia eventov',
  'Tvorba scenárov pre tematické večery a show',
  'Poradenstvo pri plánovaní a organizovaní eventov',
  'Budovanie značky cez eventy a zážitky',
  'Udržateľnosť a ekologické plánovanie eventov',
  'Koordinácia s bezpečnostnými a právnymi službami',
  'Realizácia podujatí pre rôzne cieľové skupiny',
  'Vytváranie zážitkových zón a interaktívnych priestorov',
  'Eventové inovácie a technologické riešenia',
  'Monitoring účastníkov a meranie zapojenia',
  'Tvorba a riadenie tematických festivalov',
  'Konzultácie pre firemné a súkromné podujatia',
  'Vedenie projektov a tímov v event manažmente',
  'Dokumentácia a archivácia podujatí',
  'Tvorba portfólia eventov a referencií pre klientov',
];

