export const FINANCNE_A_PRAVNE_PORADENSTVO: string[] = [
  'Osobné finančné plánovanie',
  'Tvorba rozpočtu a sledovanie výdavkov',
  'Úspory a finančné rezervy',
  'Investovanie a správa aktív',
  'Akcie, dlhopisy a podielové fondy',
  'Kryptomeny a digitálne aktíva',
  'Nehnuteľnosti a realitné investície',
  'Poistenie (životné, majetkové, cestovné)',
  'Dôchodkové plánovanie',
  'Daně a daňové poradenstvo',
  'Optimalizácia daňového zaťaženia',
  'Finančné produkty a služby bánk',
  'Hypotéky a úvery',
  'Spotrebiteľské úvery a pôžičky',
  'Refinancovanie úverov',
  'Finančné riziká a riadenie rizík',
  'Kreditné hodnotenie a správa úverov',
  'Osobný finančný audit',
  'Poradenstvo pre podnikateľov a firmy',
  'Finančné plánovanie pre malé a stredné podniky',
  'Cash flow management',
  'Firemné investície',
  'Podnikateľské úvery a financovanie',
  'Granty a dotácie',
  'Finančné reportovanie a analýzy',
  'Mergers & acquisitions poradenstvo',
  'Právne služby a poradenstvo',
  'Zmluvné právo',
  'Obchodné zmluvy a dohody',
  'Pracovné právo a zamestnanecké zmluvy',
  'Rodinné právo (rozvody, opatrovníctvo)',
  'Dedičské právo a testamenty',
  'Právna ochrana vlastníctva a duševného vlastníctva',
  'Licencie a patenty',
  'Právo nehnuteľností a prenájmy',
  'Sporové konanie a riešenie sporov',
  'Alternatívne riešenie sporov (mediácia, arbitráž)',
  'Compliance a regulácie',
  'GDPR a ochrana osobných údajov',
  'Obchodné právo a spoločnosti',
  'Zakladanie firiem a registrácia',
  'Licencie a povolenia',
  'Právne audity',
  'Právne zastupovanie pred súdmi',
  'Právne poradenstvo pre startupy',
  'Právna kontrola dokumentov',
  'Interné firemné politiky a regulácie',
  'Ochrana spotrebiteľa',
  'Právna analýza a hodnotenie rizík',
  'Poradenstvo pri bankrotoch a reštrukturalizácii',
  'Insolvenčné konanie',
  'Právne poradenstvo pri obchodných transakciách',
  'Zmluvné podmienky a kontrola dokumentov',
  'Právna edukácia a školenia',
  'Compliance školenia a interné politiky',
  'Finančné plánovanie pre dôchodcov',
  'Správa a optimalizácia majetku',
  'Poradenstvo pri investičných produktoch',
  'Finančné a právne poradenstvo pre freelancrov',
  'Právna ochrana spotrebiteľa',
  'Riešenie exekúcií a pohľadávok',
  'Právne služby pre nehnuteľnosti',
  'Právne a finančné due diligence',
  'Poradenstvo pri obchodných partnerstvách',
  'Ochrana obchodného mena a značky',
  'Právne služby pre digitálny biznis',
  'Právna podpora pri online zmluvách',
  'Finančné modelovanie a prognózy',
  'Poradenstvo pri daňovej optimalizácii firiem',
  'Právne služby pre startup a inovatívne firmy',
  'Poradenstvo v oblasti zamestnaneckých práv a povinností',
  'Právna kontrola interných dokumentov firiem',
  'Právne zastupovanie v sporných konaniach',
  'Finančné a právne poradenstvo pri investíciách',
  'Poradenstvo pri poistení a nárokoch z poistenia',
  'Právne služby pre zmluvné vzťahy s klientmi',
  'Právna podpora pri medzinárodných transakciách',
  'Finančné poradenstvo pri nákupe a predaji majetku',
  'Poradenstvo v oblasti dedenia a darovania',
  'Právna a finančná podpora pre podnikateľské projekty',
  'Právne poradenstvo pre online podnikanie',
  'Compliance a regulácie v oblasti financií',
  'Audit finančných a právnych procesov',
  'Poradenstvo pri riešení pohľadávok a dlhov',
  'Právna ochrana pred podvodmi a nezrovnalosťami',
  'Finančné a právne poradenstvo pre startupy a inovatívne projekty',
  'Vytváranie a kontrola obchodných a finančných zmlúv',
  'Právne a finančné poradenstvo pre fyzické osoby aj firmy',
];

