export const FOOD_A_GASTRONOMIA: string[] = [
  'Príprava jedál doma',
  'Recepty a varenie',
  'Pečenie sladkých jedál',
  'Pečenie slaných jedál',
  'Grilovanie a BBQ',
  'Tvorba šalátov',
  'Polievky a vývary',
  'Omáčky a dresingy',
  'Príprava dezertov',
  'Čokoládové dezerty',
  'Ovocné dezerty',
  'Cukrárske techniky',
  'Kulinárske techniky (sauté, dusenie, pečenie, varenie v pare)',
  'Tvorba raňajok',
  'Tvorba snackov a rýchlych jedál',
  'Smoothie a zdravé nápoje',
  'Mixológia a príprava koktailov',
  'Káva a čaje',
  'Degustácia a párovanie chutí',
  'Varenie pre špeciálne diéty (bezlepková, vegánska, vegetariánska)',
  'Výroba domácich nápojov',
  'Domáce kompóty a zaváraniny',
  'Fermentácia a nakladanie',
  'Výroba syrov a mliečnych výrobkov',
  'Pečenie chleba a pečiva',
  'Tvorba cestovín a knedlí',
  'Sushi a ázijská kuchyňa',
  'Medzinárodná kuchyňa',
  'Street food',
  'Fast food a snack food',
  'Catering a eventová gastronómia',
  'Food styling a prezentácia jedál',
  'Tvorba menu',
  'Sezónna a lokálna kuchyňa',
  'Experimentálna a molekulárna gastronómia',
  'Food photography',
  'Food blogging a vlogovanie',
  'Degustačné akcie',
  'Ochutnávky a food festivaly',
  'Gastronomické workshopy a kurzy',
  'Tvorba receptových kníh',
  'Vývoj a testovanie receptov',
  'Práca v reštaurácii',
  'Kuchárske pozície (šéfkuchár, kuchár, pomocník)',
  'Reštauračný management',
  'Hygiena a bezpečnosť potravín',
  'Food consulting a poradenstvo',
  'Food marketing a branding',
  'Výroba čokolády a cukroviniek',
  'Výroba pečiva a dezertov',
  'Výroba nápojov (alkoholické, nealkoholické)',
  'Wine tasting a sommeliérske služby',
  'Pivovarníctvo a craft pivá',
  'Destilácia a liehovarstvo',
  'Tvorba street food konceptov',
  'Food delivery a donáškové služby',
  'Food tech a inovácie v gastronómii',
  'Testovanie kuchynských prístrojov a technológií',
  'Gastronomické eventy a večere',
  'Degustácie syrov, vín, piva, čokolády',
  'Kulinárske súťaže a olympiády',
  'Food pairing a harmonizácia chutí',
  'Výroba džemov, sirupov a ovocných produktov',
  'Home cooking a domáca kuchyňa',
  'Urban farming a pestovanie vlastných surovín',
  'Herbár a využitie byliniek v kuchyni',
  'Výroba korenín a ochucovadiel',
  'Fermentované nápoje (kombucha, kefír)',
  'Príprava jedál podľa sezóny',
  'Tvorba tematických jedál (sviatočné, etnické)',
  'Práca s exotickými surovinami',
  'Výroba domácich cestovín, knedlí a pierogov',
  'Výroba vlastných omáčok a marinád',
  'Food waste management a udržateľnosť v kuchyni',
  'Zero waste varenie',
  'Vývoj a testovanie kuchynských receptov pre restaurácie',
  'Práca s lokálnymi farmárskymi produktmi',
  'Predaj a prezentácia jedál na trhoch a festivalech',
  'Street gastronomy a food trucks',
  'Food innovation a nové gastronomické trendy',
  'Výroba tradičných jedál a remeselných produktov',
  'Výroba domácich pekárenských výrobkov',
  'Kulinárska edukácia a kurzy pre deti a dospelých',
  'Food science a experimentálna gastronómia',
  'Degustácie a food pairing eventy',
  'Vytváranie kulinárskych zážitkov',
  'Plánovanie gastronomických ciest a zážitkov',
  'Tvorba menu pre catering a eventy',
  'Gastro storytelling a prezentácia jedál',
  'Food photography a food videography',
  'Branding a vizuálna identita gastronomických projektov',
  'Gastro recenzie a hodnotenia reštaurácií',
  'Poradenstvo pri otvorení reštaurácie alebo food biznisu',
  'Vývoj produktov a balení pre gastronomické značky',
  'Marketing a propagácia gastronomických služieb',
  'Udržateľné a etické sourcing surovín',
  'Lokálne a sezónne menu',
  'Príprava bufetov a cateringových stolov',
  'Tvorba dezertov a fine dining prezentácií',
  'Gastro workshopy a interaktívne kurzy',
  'Vývoj food konceptov pre firmy a značky',
  'Senzorické hodnotenie jedál a nápojov',
  'Food storytelling a kulinárske eventy',
  'Tvorba receptúr a produktov pre retail a horeca',
  'Výroba a predaj remeselných potravín',
  'Food innovation labs a testovanie nových receptov',
  'Vývoj produktov pre zdravú výživu a špeciálne diéty',
];

