export const ZDRAVOTNA_STAROSTLIVOST_A_FIRST_AID: string[] = [
  'Prvá pomoc a resuscitácia (CPR)',
  'Prvá pomoc pri poraneniach a krvácaní',
  'Ošetrenie popálenín a opaľovacích úrazov',
  'Ošetrenie zlomenín, vyvrtnutí a podvrtnutí',
  'Prvá pomoc pri dusení a zadusení',
  'Prvá pomoc pri srdcových a cievnych príhodách',
  'Prvá pomoc pri cukrovke a hypoglykémii',
  'Prvá pomoc pri epileptických záchvatoch',
  'Prvá pomoc pri alergických reakciách a anafylaxii',
  'Použitie AED a defibrilátorov',
  'Základy zdravotnej starostlivosti',
  'Monitorovanie životných funkcií (pulz, tlak, dýchanie)',
  'Ošetrenie rán a infekčných poranení',
  'Bandážovanie a fixácia poranených končatín',
  'Ovládanie šoku a kolapsu',
  'Prvá pomoc pri úpale a podchladení',
  'Bezpečnosť a hygiena pri poskytovaní prvej pomoci',
  'Základy anatómie a fyziológie pre first aid',
  'Starostlivosť o pacientov po úrazoch a operáciách',
  'Asistencia pri lekárskych zákrokoch',
  'Základy farmakológie a podávanie liekov',
  'Preventívna zdravotná starostlivosť',
  'Starostlivosť o chronických pacientov',
  'Domáca zdravotná starostlivosť',
  'Starostlivosť o seniorov a imobilných pacientov',
  'Nutričné a diétne poradenstvo',
  'Edukácia pacientov a prevencia chorôb',
  'Správa zdravotnej dokumentácie a záznamov',
  'Hygiena a dezinfekcia pri zdravotnej starostlivosti',
  'Starostlivosť o deti a dojčatá',
  'Starostlivosť o osoby so špeciálnymi potrebami',
  'Podpora psychického zdravia pacientov',
  'Základy prvej pomoci v prírode a outdoor aktivitách',
  'Poskytovanie prvej pomoci pri dopravných nehodách',
  'Základy traumatológie a urgentnej medicíny',
  'Príprava na certifikované kurzy prvej pomoci',
  'Poskytovanie zdravotnej pomoci v komunitách',
  'Starostlivosť o pacientov s infekčnými chorobami',
  'Ovládanie resuscitačných techník pre deti a dospelých',
  'Podpora zdravia a wellness programov',
  'Asistencia pri rehabilitácii pacientov',
  'Poskytovanie prvého kontaktu pri akútnych stavoch',
  'Základy pediatrickej prvej pomoci',
  'Základy geriatrickej starostlivosti',
  'Prvá pomoc pri intoxikáciách a otravách',
  'Prvá pomoc pri duševných a psychických krízach',
  'Koordinácia s profesionálnou zdravotnou službou',
  'Starostlivosť pri popôrodných komplikáciách',
  'Poskytovanie pomoci pri respiračných problémoch',
  'Starostlivosť pri kardiovaskulárnych problémoch',
  'Základy pre zdravotníkov a dobrovoľníkov',
  'Podpora samostatného zvládania chronických chorôb',
  'Základy hygieny a prevencie infekcií',
  'Starostlivosť pri akútnych alergiách a anafylaktických reakciách',
  'Ovládanie základných diagnostických nástrojov (tlakomery, teplomery)',
  'Prvá pomoc pri nehodách a úrazoch v domácnosti',
  'Základy poskytovania zdravotnej pomoci v športových aktivitách',
  'Kurzy a školenia prvej pomoci pre školy, firmy a komunitu',
  'Používanie zdravotníckych pomôcok a vybavenia',
  'Poskytovanie pomoci pri duševnej traume a stresových situáciách',
  'Starostlivosť pri chronických bolestiach a rehabilitácii',
  'Prevencia úrazov a bezpečnostné postupy',
  'Základy zdravotnej dokumentácie a monitorovania pacientov',
  'Podpora pri liečebných a terapeutických procesoch',
  'Prvá pomoc v neštandardných podmienkach (príroda, outdoor, extrémne situácie)',
  'Kurzy a osvedčenia prvej pomoci pre verejnosť a profesionálov',
  'Podpora zdravotnej osvety a edukácie spoločnosti',
  'Poskytovanie prvej pomoci v krizových situáciách a katastrofách',
  'Starostlivosť o pacientov po operáciách a úrazoch',
  'Podpora pri samostatnom sledovaní zdravotného stavu pacientov',
];

