export const DOMACNOST_A_SLUZBY: string[] = [
  'Upratovanie domácností',
  'Umývanie okien',
  'Pranie, žehlenie, skladanie bielizne',
  'Starostlivosť o domácnosť počas dovolenky',
  'Triedenie, organizovanie vecí',
  'Odstraňovanie škvŕn a čistenie kobercov',
  'Dezinfekcia priestorov',
  'Čistenie kuchýň, kúpeľní a spotrebičov',
  'Upratovanie po maľovaní alebo rekonštrukcii',
  'Kosenie trávnika',
  'Strihanie živých plotov',
  'Sadenie a starostlivosť o rastliny',
  'Polievanie a hnojenie',
  'Orezávanie stromov a kríkov',
  'Pestovanie zeleniny a ovocia',
  'Odstraňovanie buriny',
  'Zber úrody',
  'Stavba záhradných chodníkov, altánkov, pergol',
  'Zavlažovacie systémy',
  'Vodoinštalatérske práce',
  'Elektroinštalácie',
  'Maliarske a natieračské práce',
  'Montáž nábytku',
  'Inštalácia spotrebičov',
  'Opravy dverí, okien, kľučiek, zámkov',
  'Murárske a obkladačské práce',
  'Oprava kúrenia a klimatizácií',
  'Tesárske a stolárske práce',
  'Pokrývačské a strešné opravy',
  'Babysitting',
  'Opatera starších ľudí',
  'Opatera domácich zvierat',
  'Venčenie psov',
  'Kúpanie a úprava zvierat',
  'Varovanie domu/bytu počas neprítomnosti',
  'Donáška potravín, obedov',
  'Nakupovanie na objednávku',
  'Pomoc pri sťahovaní',
  'Pomoc pri organizovaní rodinných osláv',
  'Návrh interiéru',
  'Výroba dekorácií',
  'Redizajn starého nábytku',
  'Sezónna výzdoba (Vianoce, Veľká noc, svadby)',
  'Aranžovanie kvetov',
  'Tapetovanie',
  'Poradenstvo v oblasti štýlu bývania',
  'Varenie a pečenie na objednávku',
  'Cateringové služby',
  'Príprava domácich jedál',
  'Výroba džemov, sirupov, koláčov',
  'Domáce pekárstvo',
  'Výučba varenia',
  'Degustácie, foodstyling',
  'Šitie a oprava odevov',
  'Výroba záclon, poťahov, vankúšov',
  'Vyšívanie, háčkovanie, pletenie',
  'Redizajn starého oblečenia',
  'Pranie a chemické čistenie',
  'Inštalácia zabezpečovacích systémov',
  'Kamerové systémy',
  'Inštalácia dverových zámkov a alarmov',
  'Revízie spotrebičov a elektroinštalácie',
  'Odstraňovanie havárií (voda, plyn, elektrina)',
  'Triedenie odpadu a recyklácia',
  'Kompostovanie',
  'Upcyklácia starých vecí',
  'Eko čistiace prostriedky',
  'Úspora energie a vody',
  'Zber dažďovej vody',
  'Oprava namiesto vyhadzovania',
  'Oprava spotrebičov',
  'IT podpora v domácnosti (Wi-Fi, PC, TV)',
  'Prenášanie a inštalácia techniky',
  'Sťahovanie, balenie a transport nábytku',
  'Odvoz odpadu a starých vecí',
  'Osobný asistent pre domácnosť',
  'Správa nehnuteľnosti',
  'Concierge služby',
  'House manager',
  'Domáci šofér',
  'Domáci kuchár / súkromný kuchár',
];


