export const IT_A_TECHNOLOGIE: string[] = [
  'Web development (frontend, backend, fullstack)',
  'Mobilné aplikácie (iOS, Android, cross-platform)',
  'Desktopové aplikácie',
  'Herný vývoj (Game Development, Unity, Unreal Engine, Godot)',
  'Embedded systems programming',
  'DevOps, CI/CD, automatizácia',
  'API vývoj a integrácie',
  'Low-code / no-code vývoj',
  'Skriptovanie (Python, Bash, PowerShell, atď.)',
  'Open source vývoj',
  'Návrh systémovej architektúry',
  'Microservices',
  'Databázový dizajn',
  'Optimalizácia výkonu',
  'Cloud-native aplikácie',
  'API architektúra',
  'Refaktoring a škálovanie aplikácií',
  'AWS, Azure, Google Cloud',
  'Cloud deployment a konfigurácia',
  'Kubernetes, Docker, container management',
  'Serverless technológie',
  'Infrastructure as Code (Terraform, Ansible)',
  'Cloud bezpečnosť',
  'Load balancing, CDN',
  'Penetračné testovanie (ethical hacking)',
  'Network security',
  'Application security',
  'Incident response',
  'Malware analýza',
  'Šifrovanie a kryptografia',
  'Bezpečnosť cloudu',
  'Ochrana dát a GDPR',
  'Data science',
  'Machine Learning',
  'Deep Learning',
  'Computer Vision',
  'Natural Language Processing (NLP)',
  'Business Intelligence (BI)',
  'Data Engineering (ETL pipelines, big data spracovanie)',
  'Data Visualization (Power BI, Tableau, matplotlib, Plotly)',
  'Štatistická analýza',
  'SQL databázy (MySQL, PostgreSQL, MSSQL, Oracle)',
  'NoSQL databázy (MongoDB, Firebase, Cassandra)',
  'Data warehousing (Snowflake, BigQuery)',
  'Data backup & recovery',
  'Query optimalizácia',
  'Indexovanie dát',
  'Správa serverov (Linux, Windows Server)',
  'Sieťové protokoly (TCP/IP, DNS, DHCP, VPN)',
  'Routery, switche, firewally',
  'Monitoring a diagnostika',
  'Virtualizácia (VMware, Hyper-V)',
  'Automatizácia infraštruktúry',
  'Helpdesk, troubleshooting',
  'Správa hardvéru a softvéru',
  'Nasadzovanie systémov',
  'Zálohovanie a obnova dát',
  'Diagnostika chýb',
  'Konfigurácia zariadení',
  'Internet of Things (IoT)',
  'Robotické systémy',
  'Arduino, Raspberry Pi',
  'Smart home technológie',
  'Práca so senzormi',
  'Práca s mikrokontrolérmi',
  'Automatizácia výroby',
  'Generatívna AI (ChatGPT, Midjourney, DALL·E, Claude)',
  'AI integrácie do aplikácií',
  'AI modelovanie a tréning',
  'Prompt engineering',
  'Automatizácia procesov pomocou AI (RPA)',
  'Web design',
  'Mobilný UX/UI dizajn',
  'Prototypovanie (Figma, Sketch, XD)',
  'Grafický dizajn (Photoshop, Illustrator, Canva)',
  'Motion design',
  '3D dizajn (Blender, Cinema 4D)',
  'UX research a testovanie',
  'Herné enginy (Unity, Unreal, Godot)',
  '3D modelovanie a animácia',
  'Fyzikálne simulácie',
  'Herné skriptovanie (C#, Blueprint, Python)',
  'Game design, storytelling',
  'VR / AR vývoj',
  'Agile, Scrum, Kanban',
  'Jira, Trello, Notion',
  'Product ownership',
  'Technická dokumentácia',
  'QA testing',
  'Release management',
  'ITIL procesy',
  'IT školenia',
  'Technická dokumentácia',
  'Mentoring juniorov',
  'Výskum technológií',
  'Online kurzy, tutoring',
  'EduTech riešenia',
  'Blockchain a kryptomeny',
  'Metaverse a XR',
  'Quantum computing',
  'Edge computing',
  '3D tlač a výroba',
  'Biotechnológie a bioinformatika',
  'SpaceTech a drony',
];


