export const JAZYKOVE_SLUZBY_A_PREKLADY: string[] = [
  'Preklady písomných textov',
  'Preklady odborných textov',
  'Preklady technických dokumentov',
  'Preklady právnych dokumentov',
  'Preklady marketingových a reklamných materiálov',
  'Preklady webových stránok',
  'Preklady kníh a literatúry',
  'Preklady vedeckých prác a štúdií',
  'Preklady lekárskych dokumentov',
  'Preklady finančných a účtovných dokumentov',
  'Preklady softvérových a IT materiálov',
  'Preklady zmlúv a obchodnej korešpondencie',
  'Preklady certifikátov a diplomov',
  'Simultánne tlmočenie',
  'Konsekutívne tlmočenie',
  'Šepotové tlmočenie',
  'Tlmočenie na konferenciách',
  'Tlmočenie na súdoch',
  'Tlmočenie pre lekárske účely',
  'Tlmočenie pri obchodných stretnutiach',
  'Tlmočenie online a cez videohovory',
  'Jazykové korektúry a editácia textov',
  'Lokalizácia webov a aplikácií',
  'Lokalizácia softvéru',
  'Lokalizácia hier a multimediálneho obsahu',
  'Jazykové konzultácie',
  'Jazykové školenia a kurzy',
  'Príprava na jazykové skúšky',
  'Tlmočenie pri školeniach a workshopoch',
  'Prekladateľské služby pre marketingové kampane',
  'Príprava bilingválnych dokumentov',
  'Proofreading a jazyková kontrola textov',
  'Úprava štýlu a tónu textu',
  'Preklady titulkov a dabing textov',
  'Podpisovanie a certifikácia prekladov',
  'Overovanie a legalizácia prekladov',
  'Preklady pre turistické a cestovateľské služby',
  'Preklady v oblasti kultúry a umenia',
  'Preklady pre e-commerce a online obchody',
  'Preklady v oblasti vzdelávania a školstva',
  'Preklady politických a vládnych dokumentov',
  'Tvorba slovníkov a glosárov',
  'Terminologická konzultácia',
  'Preklady multimediálneho obsahu (audio, video)',
  'Jazyková lokalizácia reklamných materiálov',
  'Preklady technických manuálov a návodov',
  'Tlmočenie a preklady pre medzinárodné podujatia',
  'Tlmočenie pre turistov a cestovateľov',
  'Tlmočenie pre obchodné rokovania',
  'Tlmočenie pre právne a súdne účely',
  'Tlmočenie pre lekárske a zdravotnícke služby',
  'Tlmočenie pre vládne a diplomatické stretnutia',
  'Tlmočenie pre konferencie a sympóziá',
  'Preklady a tlmočenie v oblasti financií a bankovníctva',
  'Preklady a tlmočenie v oblasti IT a technológií',
  'Preklady a tlmočenie v oblasti marketingu a reklamy',
  'Jazykové služby pre digitálne médiá',
  'Preklady webových obsahov a blogov',
  'Preklady emailov a korešpondencie',
  'Preklady manuálov a technických dokumentácií',
  'Preklady prezentácií a PPT materiálov',
  'Tlmočenie pri školeniach a online kurzoch',
  'Tlmočenie pri firemných stretnutiach',
  'Tlmočenie pre online eventy a webináre',
  'Preklady kreatívnych textov a literárnych diel',
  'Preklady newsletterov a marketingových kampaní',
  'Preklady pre sociálne siete a digitálny marketing',
  'Preklady pre e-learning a vzdelávacie platformy',
  'Jazykové poradenstvo a konzultácie',
  'Preklady manuálov pre softvér a aplikácie',
  'Preklady návodov a user guide dokumentov',
  'Tlmočenie a preklady pre turistické a kultúrne programy',
  'Tlmočenie a preklady pre medzinárodné vzdelávacie projekty',
  'Tlmočenie a preklady pre športové a spoločenské podujatia',
  'Tlmočenie a preklady pre kultúrne festivaly a eventy',
  'Tlmočenie a preklady pre obchodné a podnikateľské rokovania',
  'Tlmočenie a preklady pre diplomatické a vládne účely',
  'Tlmočenie pre konferencie, semináre a workshopy',
  'Preklady odborných článkov a publikácií',
  'Preklady technických, vedeckých a akademických materiálov',
  'Preklady kreatívnych a umeleckých diel',
  'Lokalizácia aplikácií, webov a hier',
  'Preklady multimediálnych obsahov (video, audio, titulky)',
  'Tlmočenie a preklady online a offline podujatí',
  'Overovanie a certifikácia prekladov',
  'Jazyková korektúra a proofreading textov',
  'Jazykové konzultácie a poradenstvo pre firmy aj jednotlivcov',
];

