export const MARKETING_A_OBCHOD: string[] = [
  'Predaj produktov a služieb',
  'Online predaj',
  'Telesales a telefonický predaj',
  'Osobný predaj',
  'Door-to-door predaj',
  'Veľkoobchod',
  'Maloobchod',
  'Predaj cez sociálne siete',
  'E-commerce manažment',
  'Vedenie e-shopu',
  'Správa objednávok',
  'Zákaznícka podpora',
  'Starostlivosť o klientov',
  'Cross-selling a upselling',
  'Merchandising',
  'Vystavovanie tovaru',
  'Objednávanie tovaru',
  'Práca s pokladňou a skladom',
  'Skladová logistika',
  'Cenotvorba',
  'Vyjednávanie so zákazníkmi',
  'Uzatváranie obchodov',
  'Tvorba obchodných ponúk',
  'Príprava cenových kalkulácií',
  'Fakturácia a platobné systémy',
  'Prezentácia produktov',
  'Demonštrácia výrobkov',
  'Účasť na výstavách a veľtrhoch',
  'Organizácia promo akcií',
  'Firemné prezentácie',
  'Predajné stratégie',
  'Marketingová stratégia',
  'Analýza trhu',
  'Prieskum trhu',
  'Segmentácia zákazníkov',
  'Cieľové skupiny',
  'Budovanie značky',
  'Branding',
  'Rebranding',
  'Tvorba loga a vizuálnej identity',
  'Storytelling',
  'Tvorba sloganov',
  'Marketingová komunikácia',
  'PR a public relations',
  'Písanie tlačových správ',
  'Krízová komunikácia',
  'Budovanie reputácie',
  'Influencer marketing',
  'Spolupráca s influencermi',
  'Sponzoring a partnerstvá',
  'Affiliate marketing',
  'E-mail marketing',
  'Automatizácia kampaní',
  'Newslettery',
  'Databázy klientov',
  'Direct marketing',
  'Sociálne siete',
  'Správa sociálnych sietí',
  'Tvorba obsahu pre sociálne siete',
  'Platené kampane na sociálnych sieťach',
  'Facebook reklama',
  'Instagram reklama',
  'TikTok reklama',
  'LinkedIn marketing',
  'YouTube marketing',
  'Komunitný manažment',
  'Online reklama',
  'Google Ads',
  'PPC kampane',
  'Bannerová reklama',
  'Remarketing',
  'SEO optimalizácia',
  'Tvorba kľúčových slov',
  'On-page a off-page SEO',
  'Linkbuilding',
  'Copywriting',
  'Tvorba marketingových textov',
  'Reklamné texty',
  'Webový obsah',
  'Produktové popisy',
  'Blogové články',
  'Obsahový marketing',
  'Videomarketing',
  'Tvorba reklamných videí',
  'Scenáre a storyboardy',
  'Produkcia videí',
  'Strih a postprodukcia',
  'Audio reklama a jingles',
  'Podcast marketing',
  'Grafický dizajn v marketingu',
  'Bannery a letáky',
  'Plagáty a brožúry',
  'Vizitky a propagačné materiály',
  'Tvorba prezentácií',
  'Webdizajn',
  'UX/UI dizajn',
  'Tvorba webových stránok',
  'Optimalizácia pre konverzie',
  'Správa kampaní',
  'A/B testovanie',
  'Analýza výsledkov kampaní',
  'Marketingové metriky a KPI',
  'Google Analytics',
  'Štatistiky a reporting',
  'CRM systémy',
  'Správa zákazníckych dát',
  'Automatizácia predaja',
  'Lead generation',
  'Cold calling',
  'Budovanie obchodných vzťahov',
  'Networking',
  'Obchodné rokovania',
  'Zmluvy a dohody',
  'Firemná komunikácia',
  'Obchodné prezentácie',
  'Vyhľadávanie nových klientov',
  'Expanzia na zahraničné trhy',
  'Export a import',
  'Obchod s licencami',
  'Franchising',
  'Distribučné siete',
  'Marketingový výskum',
  'Spotrebiteľské správanie',
  'Analýza konkurencie',
  'Benchmarking',
  'Marketingová psychológia',
  'Neuromarketing',
  'Cenové stratégie',
  'Lojalita zákazníkov',
  'Věrnostné programy',
  'Event marketing',
  'Organizácia promo eventov',
  'Firemné akcie a konferencie',
  'Roadshow',
  'Tlačové konferencie',
  'Sponzorované podujatia',
  'Guerilla marketing',
  'Virálny marketing',
  'Buzz marketing',
  'Street marketing',
  'Ambient marketing',
  'Digitálny marketing',
  'Performance marketing',
  'Influencer kampane',
  'Cross-channel stratégie',
  'Marketingová automatizácia',
  'Data-driven marketing',
  'Umelá inteligencia v marketingu',
  'Marketingová analytika',
  'Growth hacking',
  'Tvorba funnelov',
  'Predajné stránky (sales pages)',
  'Copy pre reklamy a landing pages',
  'Remarketingové stratégie',
  'Obsahové kampane',
  'Online reputačný manažment',
  'Komunikačné stratégie',
  'Firemná identita',
  'Brand voice a tone of voice',
  'PR články a mediálne výstupy',
  'Správa vzťahov s médiami',
  'Tlačové kampane',
  'Outdoor reklama',
  'Billboardy a citylighty',
  'Reklama v dopravných prostriedkoch',
  'Reklama v rádiu a TV',
  'Mediálne plánovanie',
  'Nákup mediálneho priestoru',
  'Marketing pre neziskové organizácie',
  'CSR projekty',
  'Ekologický a etický marketing',
  'Politický marketing',
  'Kultúrny marketing',
  'Športový marketing',
  'Zdravotnícky marketing',
  'Realitný marketing',
  'Marketing v gastronómii',
  'Marketing v cestovnom ruchu',
  'Marketing v IT sektore',
  'B2B marketing',
  'B2C marketing',
  'Brand manažment',
  'Online predajné stratégie',
  'Obchodná komunikácia v angličtine',
  'Vyjednávacie techniky',
  'Time management obchodníkov',
  'Motivácia predajcov',
  'Vedenie obchodného tímu',
  'Obchodné plánovanie',
  'Forecasting predaja',
  'Práca s dátami v marketingu',
  'CRM integrácie',
  'Reporting výsledkov predaja',
  'Obchodné procesy a optimalizácia',
];

