export const MODELARSTVO_A_HOBBY_TVORBA: string[] = [
  'Plastové modely a makety',
  'Kartónové modely a papierové makety',
  'Letecké modely a RC lietadlá',
  'Vláčikové modely a železnice',
  'Automodely a RC autá',
  'Lodné modely a RC lode',
  'Miniatúry a diorámy',
  '3D tlačené modely a figuríny',
  'Sochárstvo a modelovanie hlinou alebo polymérom',
  'Modelovanie z dreva a kovu',
  'Modelárske súpravy a stavebnice',
  'Figúrky a postavičky pre hry a zbierky',
  'Makety budov a architektúry',
  'Diorámy a scény pre modely',
  'Plastelína a modelovacie hmoty',
  'Modelárske nástroje a pomôcky',
  'Farby, laky a airbrush techniky',
  'Opravy a úpravy modelov',
  'RC elektronika a servomotory',
  'Montáž a lepenie modelov',
  'Modelárske súťaže a výstavy',
  'Vytváranie vlastných konštrukcií',
  'Modelovanie vozidiel a strojov',
  'Papierové figúrky a origami',
  'Miniatúrne scenérie a prírodné prvky',
  'Modelovanie zvierat a postáv',
  'Replika historických predmetov a zbraní',
  'Modelovanie fantazijných postáv a svetov',
  'Modelovanie pre stolové hry a RPG',
  'Modelovanie s prírodnými materiálmi',
  'Rezanie, gravírovanie a rytie',
  'Laserové a CNC modelárske technológie',
  'Elektronické doplnky pre modely',
  'Zvukové a svetelné efekty pre modely',
  'Modelárske dielne a workshopy',
  'Vzdelávacie modelárske projekty',
  'Kolekcionárske a zberateľské modely',
  'Hobby tvorba šperkov a dekorácií',
  'Ručné práce a kreatívne DIY projekty',
  'Scrapbooking a tvorba papierových projektov',
  'Výroba darčekov a personalizovaných predmetov',
  'Tvorba hand-made dekorácií',
  'Tvorba kostýmov a cosplay doplnkov',
  'Miniatúrne rekvizity a doplnky',
  'Modelovanie pomocou živice a formovacích techník',
  'Modelovanie a tvorba rekvizít pre filmy a divadlo',
  'Modelovanie pre hry, figurky a RPG doplnky',
  'Modelárske blogy a online komunity',
  'Videotutoriály a online kurzy modelárstva',
  'Kombinované materiály (drevo, kov, plast, živica)',
  'Techniky starnutia a weathering modelov',
  'Tvorba tematických scén a diorám',
  'Zberateľské edície a limitované modely',
  'Výroba mechanických modelov a prevodov',
  'Modelovanie vozidiel, lietadiel a lodí v mierke',
  'Kreatívne projekty pre deti a mládež',
  'Tvorba interaktívnych modelov a mechanizmov',
  'Vytváranie vlastných šablón a dielov',
  'Modelovanie historických scén a bitiek',
  'Miniatúrne krajiny a prírodné scenérie',
  'Výroba a zdobenie mini domčekov a budov',
  'Modelovanie zvierat, rastlín a fantazijných bytostí',
  'Vytváranie realistických efektov (sneh, voda, piesok)',
  'Modelovanie pre stolné hry a strategické hry',
  'Experimentálne materiály a netradičné techniky',
  'Modelárske súpravy pre začiatočníkov a pokročilých',
  'Organizovanie modelárskych klubov a stretnutí',
  'Modelárske výstavy a prezentácie tvorby',
  'Tvorba vlastných projektov a prototypov',
  'Modelovanie mini nábytku a doplnkov do diorám',
  'Kombinácia tradičných a moderných techník',
  'Modelovanie s použitím 3D softvérov a digitálnych nástrojov',
  'Tvorba vlastných návrhov a konceptov pre modely',
  'Edukačné projekty a tvorba modelov pre školy a workshopy',
  'Tvorba detailných a realistických miniatur',
  'Modelárske techniky farbenia a patinovania',
  'Výroba mechanických a pohyblivých modelov',
  'Experimentovanie s materiálmi a kreatívnymi technikami',
  'Hobby tvorba a ručné práce pre relax a voľný čas',
];

