export const HUDBA_A_VYSTUPENIA: string[] = [
  'Hra na gitare',
  'Hra na basgitare',
  'Hra na elektrickej gitare',
  'Hra na akustickej gitare',
  'Hra na klavíri',
  'Hra na keyboarde',
  'Hra na husliach',
  'Hra na violončele',
  'Hra na kontrabase',
  'Hra na flaute',
  'Hra na priečnej flaute',
  'Hra na saxofóne',
  'Hra na klarinete',
  'Hra na trúbke',
  'Hra na pozoune',
  'Hra na bicích',
  'Hra na perkusných nástrojoch',
  'Hra na ukulele',
  'Hra na mandolíne',
  'Hra na harmonike',
  'Hra na akordeóne',
  'Hra na harfe',
  'Hra na sintetizátore',
  'Hra na organ',
  'Spev',
  'Sólový spev',
  'Skupinový spev',
  'Zborový spev',
  'Spevácky tréning',
  'Hlasová technika',
  'Improvizácia v speve',
  'Nahrávanie vokálov',
  'Tvorba vlastných piesní',
  'Písanie textov piesní',
  'Hudobná produkcia',
  'Hudobná kompozícia',
  'Aranžovanie skladieb',
  'Mix a mastering',
  'Nahrávanie v štúdiu',
  'DJing',
  'Tvorba setov',
  'Práca s gramofónmi',
  'Práca s mixpultom',
  'Práca s MIDI kontrolerom',
  'Tvorba elektronickej hudby',
  'Remixovanie',
  'Sound design',
  'Filmová hudba',
  'Herná hudba',
  'Hudba pre reklamy',
  'Orchestrálna kompozícia',
  'Zborové aranžmány',
  'Tvorba notových zápisov',
  'Dirigovanie',
  'Hudobná teória',
  'Sluchová analýza',
  'Rytmika',
  'Intonácia',
  'Hudobná improvizácia',
  'Učenie hudby',
  'Učenie hry na nástroj',
  'Hudobná pedagogika',
  'Individuálne lekcie hudby',
  'Skupinové hudobné kurzy',
  'Príprava na konzervatórium',
  'Hudobné workshopy',
  'Hudobné súťaže',
  'Tvorba hudobných videí',
  'Videoklipy a vizuály',
  'Režisér hudobného klipu',
  'Strih a postprodukcia hudobných videí',
  'Scénografia a svetelný dizajn',
  'Tanečné vystúpenia',
  'Tanečné choreografie',
  'Učenie tanca',
  'Moderný tanec',
  'Hip-hop tanec',
  'Breakdance',
  'Street dance',
  'Jazz dance',
  'Balet',
  'Spoločenské tance',
  'Latinskoamerické tance',
  'Ľudové tance',
  'Orientálny tanec',
  'Pole dance',
  'Akrobatický tanec',
  'Tanečné improvizácie',
  'Tanečné súťaže',
  'Hudobné vystúpenia',
  'Spevácke vystúpenia',
  'Kapelové koncerty',
  'Orchestrálne koncerty',
  'DJ vystúpenia',
  'Tanečné show',
  'Pouličné vystúpenia',
  'Sólové vystúpenia',
  'Firemné eventy',
  'Svadby a oslavy',
  'Divadelné predstavenia',
  'Muzikály',
  'Kabaretné predstavenia',
  'Stand-up comedy',
  'Improvizačné divadlo',
  'Herecký tréning',
  'Dabing',
  'Moderovanie',
  'Konferencie',
  'Uvádzanie kultúrnych podujatí',
  'Sprievodcovanie akcií',
  'Tvorba scenára pre vystúpenie',
  'Režisérska činnosť',
  'Svetelný a zvukový technik',
  'Stage management',
  'Hudobné festivaly',
  'Organizácia koncertov',
  'Hudobné agentúry',
  'Booking interpretov',
  'Hudobná propagácia',
  'PR a marketing pre umelcov',
  'Sociálne siete pre hudobníkov',
  'Fotografovanie koncertov',
  'Tvorba vizuálov pre vystúpenia',
  'Kostýmy a maskovanie',
  'Make-up pre javisko',
  'Tanečné a hudobné kostýmy',
  'Stage efekty a pyrotechnika',
  'Svetelné inštalácie',
  'Performance art',
  'Experimentálne hudobné vystúpenia',
  'Pouličné hranie (busking)',
  'Tvorba soundtrackov',
  'Hudba pre podcasty',
  'Nahrávanie živých vystúpení',
  'Živý streaming koncertov',
  'Tvorba hudobných podcastov',
  'Umelecké spolupráce',
  'Crossžánrové projekty',
  'Medzinárodné vystúpenia',
  'Umelecké rezidencie',
  'Tvorba portfólia hudobníka',
];


