export const ZVIERATA_A_PRIRODA: string[] = [
  'Starostlivosť o domáce zvieratá',
  'Kŕmenie zvierat',
  'Venčenie psov',
  'Kúpanie a úprava srsti',
  'Výcvik psov',
  'Výcvik mačiek',
  'Výcvik iných domácich zvierat',
  'Chov mačiek',
  'Chov psov',
  'Chov exotických zvierat',
  'Chov vtákov',
  'Chov hlodavcov',
  'Chov rybičiek a akvárií',
  'Chov plazov',
  'Starostlivosť o hospodárske zvieratá',
  'Kŕmenie a dojenie',
  'Veterinárna starostlivosť',
  'Prevencia chorôb',
  'Očkovanie zvierat',
  'Záchrana a rehabilitácia zvierat',
  'Zvieracie útulky',
  'Záchranné stanice',
  'Záchrana ohrozených druhov',
  'Biologický monitoring',
  'Pozorovanie vtáctva',
  'Pozorovanie cicavcov',
  'Terénne výskumy živočíchov',
  'Ekologický výskum',
  'Botaniky a starostlivosť o rastliny',
  'Sadenie stromov',
  'Orezávanie stromov a kríkov',
  'Starostlivosť o kvety',
  'Upratovanie prírodných lokalít',
  'Údržba parkov a záhrad',
  'Chránené územia',
  'Národné parky',
  'Lesníctvo',
  'Preventívna ochrana lesa',
  'Výsadba a obnova lesov',
  'Starostlivosť o pôdu',
  'Udržateľné poľnohospodárstvo',
  'Ekologické farmy',
  'Kompostovanie a recyklácia',
  'Monitorovanie ekosystémov',
  'Hydrológia a starostlivosť o vodné plochy',
  'Čistenie riek a jazier',
  'Rybolov a chov rýb',
  'Ochrana ohrozených druhov',
  'Vytváranie biotopov',
  'Prírodná edukácia',
  'Výchova k ochrane prírody',
  'Ekoturistika',
  'Vedenie prírodných chodníkov',
  'Sprievodcovanie v prírode',
  'Lesná pedagogika',
  'Fotografovanie divokej prírody',
  'Videodokumentácia prírody',
  'Školenia a workshopy o prírode',
  'Výskum biodiverzity',
  'Zaznamenávanie druhov',
  'Analýza environmentálnych dát',
  'Mapovanie biotopov',
  'Prevencia poľnohospodárskych škôd',
  'Ochrana rastlín',
  'Kontrola invazívnych druhov',
  'Udržiavanie prírodných rezervácií',
  'Vedenie environmentálnych projektov',
  'Organizácia dobrovoľníckych činností',
  'Udržiavanie záhrad v komunitách',
  'Starostlivosť o mestskú zeleň',
  'Presádzanie a množiteľstvo rastlín',
  'Údržba zelene v parkoch a verejných priestranstvách',
  'Starostlivosť o bonsaje',
  'Vedenie botanických záhrad',
  'Tvorba a údržba akvárií',
  'Správa terárií',
  'Edukačné programy pre deti o prírode',
  'Vývoj ekologických programov',
  'Prírodné laboratóriá',
  'Laboratórne štúdium živočíchov a rastlín',
  'Výskum klimatických zmien a ich vplyv na prírodu',
  'Monitorovanie fauny a flóry',
  'Analýza pôd a vody',
  'Výskum migrácie vtáctva',
  'Tvorba ochranných opatrení pre ohrozené druhy',
  'Odchyt a presun zvierat',
  'Údržba a kontrola kŕmidiel a búdok',
  'Starostlivosť o včely a včelárstvo',
  'Produkcia medu a vosku',
  'Zabezpečenie prírodných zdrojov pre zvieratá',
  'Organizácia prírodných workshopov a táborov',
  'Edukácia verejnosti o prírode a zvieratách',
  'Konzultácie pre environmentálne projekty',
  'Participácia na vedeckých projektoch prírody',
  'Dobrovoľnícka činnosť v oblasti ochrany prírody',
  'Obnova zničených biotopov',
  'Ochrana lesných porastov pred požiarmi',
  'Monitorovanie znečistenia prírodných lokalít',
  'Vedenie environmentálne zameraných kampaní',
  'Správa prírodných rezervácií a parkov',
  'Dokumentácia prírodných javov',
  'Ochrana pôvodných druhov rastlín a živočíchov',
  'Vyhľadávanie a dokumentácia ohrozených druhov',
  'Prevencia erózie pôdy',
  'Vedenie botanických inventárov',
  'Starostlivosť o vodné ekosystémy',
  'Monitorovanie populácií živočíchov',
  'Ekologický monitoring',
  'Vytváranie zelených koridorov pre zvieratá',
  'Vzdelávacie aktivity o udržateľnom rozvoji a prírode',
];

