export const OSOBNY_ROZVOJ_A_MENTORING: string[] = [
  'Sebapoznanie a introspekcia',
  'Rozvoj osobných zručností',
  'Time management a plánovanie',
  'Organizácia a produktivita',
  'Stanovenie cieľov a priorít',
  'Motivácia a sebamotivácia',
  'Rozvoj kritického myslenia',
  'Rozvoj kreativity',
  'Rozvoj emočnej inteligencie',
  'Sebaúcta a sebadôvera',
  'Komunikačné zručnosti',
  'Prezentačné zručnosti',
  'Verbálna a neverbálna komunikácia',
  'Vedenie rozhovorov a diskusií',
  'Vyjednávacie zručnosti',
  'Konflikt management',
  'Riešenie problémov',
  'Rozvoj líderských schopností',
  'Mentoring a koučing',
  'Osobný koučing',
  'Profesionálny koučing',
  'Kariérne poradenstvo',
  'Networking a budovanie vzťahov',
  'Efektívna spolupráca v tíme',
  'Projektový manažment pre osobný rozvoj',
  'Rozvoj prezentačných schopností',
  'Tvorba a vedenie workshopov',
  'Mentoring mladých a študentov',
  'Podpora talentu a rozvoj schopností',
  'Life coaching',
  'Sebadisciplína a návyky',
  'Mindfulness a meditácia',
  'Stres manažment',
  'Rovnováha medzi pracovným a súkromným životom',
  'Rozvoj profesionálnych zručností',
  'Učenie sa novým kompetenciám',
  'Osobná efektivita',
  'Rozvoj strategického myslenia',
  'Rozvoj adaptibility a flexibility',
  'Rozvoj emočnej odolnosti',
  'Mentoring programy',
  'Budovanie mentorsko-mentee vzťahov',
  'Feedback a hodnotenie výkonu',
  'Rozvoj kariéry a profesijného rastu',
  'Príprava na pracovné pohovory',
  'Sebaprezentácia a osobná značka',
  'Public speaking a verejné vystupovanie',
  'Rozvoj kritického a analytického myslenia',
  'Kreatívne a inovatívne myslenie',
  'Rozvoj rozhodovacích schopností',
  'Tvorba a udržiavanie pozitívnych návykov',
  'Rozvoj profesionálnych a osobných cieľov',
  'Mentoring v oblasti podnikania a startupov',
  'Koučing pre vedúcich pracovníkov',
  'Rozvoj tímovej spolupráce a leadershipu',
  'Mentoring pre študentov a mladých profesionálov',
  'Rozvoj sociálnych zručností',
  'Rozvoj medziľudských vzťahov',
  'Mentoring a podpora osobného rastu',
  'Self-improvement programy',
  'Osobný plán rozvoja',
  'Cieľové plánovanie a sledovanie progresu',
  'Rozvoj adaptability v meniacom sa prostredí',
  'Rozvoj odolnosti voči stresu',
  'Mentoring pre zlepšenie výkonu',
  'Coaching a mentoring soft skills',
  'Leadership development',
  'Rozvoj tímového vedenia',
  'Mentoring pre kariérny postup',
  'Rozvoj podnikateľských schopností',
  'Rozvoj rozhodovacích procesov',
  'Koučing pre zvýšenie efektivity',
  'Mentoring pre osobnú a profesionálnu transformáciu',
  'Strategické plánovanie osobného rozvoja',
  'Mentoring a koučing pre motiváciu',
  'Rozvoj schopnosti riešiť konflikty',
  'Mentoring a podpora pri dosahovaní cieľov',
  'Rozvoj emocionálnej regulácie',
  'Rozvoj resiliencie',
  'Mentoring v oblasti vzdelávania a školenia',
  'Rozvoj sebareflexie a sebahodnotenia',
  'Osobné a profesionálne hodnotenie výkonu',
  'Mentoring pre vedenie projektov',
  'Rozvoj kreatívnych riešení problémov',
  'Koučing pre zlepšenie pracovného výkonu',
  'Mentoring pre zlepšenie komunikácie',
  'Rozvoj rozhodovacích a analytických schopností',
  'Mentoring pri osobných životných rozhodnutiach',
  'Mentoring pre dosahovanie životných cieľov',
  'Podpora pri osobnej transformácii a raste',
  'Mentoring programy pre zamestnancov a organizácie',
  'Rozvoj osobnej a profesionálnej identity',
  'Rozvoj sebavedomia a osobnej značky',
  'Mentoring a koučing pre zlepšenie vzťahov',
  'Rozvoj adaptívnych a flexibilných schopností',
  'Koučing pre vedenie tímu a projektov',
  'Mentoring pre rozvoj kreativity a inovácií',
  'Mentoring a koučing pre osobný leadership',
];

