export const FOTOGRAFIA_A_VIDEOGRAFIA: string[] = [
  'Fotografovanie portrétov',
  'Fotografovanie krajiny',
  'Makro fotografia',
  'Street fotografia',
  'Reportážna fotografia',
  'Dokumentárna fotografia',
  'Svadobná fotografia',
  'Eventová fotografia',
  'Produktová fotografia',
  'Reklamná fotografia',
  'Fashion a módna fotografia',
  'Architektonická fotografia',
  'Interiérová fotografia',
  'Športová fotografia',
  'Nočná fotografia',
  'Astrofotografia',
  'Food fotografia',
  'Produktová a e-commerce fotografia',
  'Kreatívna a umelecká fotografia',
  'Fotografovanie zvierat a prírody',
  'Cestovateľská fotografia',
  'Black & white fotografia',
  'Fotografia s dronmi',
  'Panoramatická fotografia',
  '360° fotografia',
  'HDR fotografia',
  'Retušovanie a úprava fotografií',
  'Color grading',
  'Fotografie pre sociálne médiá',
  'Fotografie pre webové stránky',
  'Komerčná a profesionálna fotografia',
  'Vzdelávacie workshopy a kurzy fotografie',
  'Tvorba portfólií',
  'Tlač fotografií a fotoknihy',
  'Archívna správa fotografií',
  'Video tvorba',
  'Natáčanie videí',
  'Režijná práca a scenár',
  'Storyboarding',
  'Kameramanstvo a technika natáčania',
  'Svietenie a osvetlenie vo videu',
  'Zvuk a nahrávanie zvuku',
  'Editácia videa',
  'Color grading vo videu',
  'Motion graphics a animácie',
  'Tvorba krátkych filmov',
  'Dokumentárne videá',
  'Reklamné videá',
  'Hudobné videá',
  'Eventové a reportážne videá',
  'Drone videography',
  '360° video a VR video',
  'Time-lapse a slow-motion videá',
  'Live streaming',
  'Vlogging a obsah pre sociálne siete',
  'YouTube a Twitch produkcia',
  'Video marketing a promo videá',
  'Postprodukcia videa',
  'Titulky a grafické prvky vo videu',
  'Tvorba trailerov a upútaviek',
  'Stop motion a animované videá',
  'Video storytelling',
  'Tvorba video tutoriálov',
  'Video dokumentácia eventov a projektov',
  'Archívna správa videí',
  'Distribúcia a publikovanie videí',
  'Sledovanie trendov vo fotografii a videu',
  'Práca s fotografickými a video softvérmi',
  'Adobe Photoshop, Lightroom, Premiere, After Effects',
  'Tvorba vizuálneho obsahu pre branding',
  'Komerčné projekty a spolupráce',
  'Fotografie a videá pre e-commerce',
  'Tvorba vizuálneho obsahu pre marketing',
  'Kreatívne projekty a koncepty',
  'Portrétové a lifestyle videá',
  'Natáčanie rozhovorov a testimonialov',
  'Making-of a behind-the-scenes videá',
  'Správa multimediálnych projektov',
  'Konzultácie a mentoring vo fotografii a videu',
  'Kurzy a školenia pre začiatočníkov aj profesionálov',
  'Portfolio a prezentácia práce',
  'Online kurzy a webináre',
  'Technické poradenstvo pri fotení a natáčaní',
  'Tvorba vizuálneho obsahu pre sociálne médiá',
  'Výroba reklamných kampaní',
  'Kreatívna režijná práca',
  'Experimentálne a umelecké projekty',
  'Fotografia a video pre dokumentárne projekty',
  'Správa autorských práv a licencovanie fotografií a videí',
  'Tvorba interaktívneho multimediálneho obsahu',
  'Fotografia a videografia pre vzdelávacie projekty',
  '3D vizualizácie a CGI integrácia do videa',
  'Video produkcia pre firmy a značky',
  'Konzultácie pre vizuálnu komunikáciu',
  'Fotografovanie a natáčanie pre e-commerce a online obchody',
  'Tvorba vizuálneho obsahu pre influencerov a kreatívcov',
  'Experimentovanie s vizuálnymi štýlmi a technikami',
  'Vytváranie vizuálneho storytellingu a konceptov',
  'Správa digitálnych médií a archívov',
  'Organizovanie foto a video workshopov',
  'Vývoj portfólií a prezentácií pre klientov',
  'Branding a vizuálna identita prostredníctvom fotografie a videa',
  'Integrácia videa a fotografie do marketingových stratégií',
  'Multimediálne projekty pre online a offline použitie',
];

