export const PSYCHOLOGIA_A_PORADENSTVO: string[] = [
  'Individuálne psychologické poradenstvo',
  'Poradenstvo pre páry a partnerské vzťahy',
  'Rodinné a parenting poradenstvo',
  'Poradenstvo pre deti a adolescentov',
  'Kariérne poradenstvo a pracovná orientácia',
  'Psychoterapia a terapeutické sedenia',
  'Kognitívno-behaviorálna terapia (CBT)',
  'Emocionálna podpora a zvládanie stresu',
  'Krízová intervencia a podpora',
  'Trauma a posttraumatická terapia',
  'Poradenstvo pri úzkostiach a depresii',
  'Poradenstvo pri závislostiach a návykových poruchách',
  'Psychologická diagnostika a hodnotenie',
  'Mentálne zdravie a wellbeing',
  'Rozvoj emočnej inteligencie',
  'Mindfulness a meditácia',
  'Sebapoznanie a sebahodnota',
  'Rozvoj sebavedomia a sebaúcty',
  'Poradenstvo pre študentov a mladých ľudí',
  'Life coaching a osobný rozvoj',
  'Motivačné a behaviorálne koučingové techniky',
  'Poradenstvo pri zmenách a životných prechodných obdobiach',
  'Riešenie konfliktov a komunikácia',
  'Sociálne zručnosti a asertivita',
  'Poradenstvo pri výkonnostných problémoch',
  'Work-life balance a prevencia vyhorenia',
  'Poradenstvo pre manažérov a lídrov',
  'Profesionálny koučing a mentoring',
  'Psychologické testy a hodnotenia osobnosti',
  'Neuropsychologické vyšetrenia',
  'Poradenstvo pri zdravotných problémoch a chronických ochoreniach',
  'Psychologická podpora pre seniorov',
  'Online psychologické poradenstvo',
  'Skupinová terapia a podporné skupiny',
  'Poradenstvo pri smútku a stratách',
  'Psychologická príprava na súťaže a výkony',
  'Psychoedukácia a vzdelávanie o duševnom zdraví',
  'Riešenie stresových situácií a coping stratégie',
  'Poradenstvo pri problémoch so sebakontrolou',
  'Poradenstvo pri poruchách spánku',
  'Rozvoj kreativity a osobného potenciálu',
  'Psychologická podpora pri migrácii a adaptácii',
  'Poradenstvo pri problémových vzťahoch',
  'Poradenstvo pre rodičov a opatrovateľov',
  'Poradenstvo pri sexuálnych a intímnych otázkach',
  'Poradenstvo pri identite a sebarealizácii',
  'Poradenstvo pri rozhodovaní a životných voľbách',
  'Poradenstvo pri finančných a kariérnych rozhodnutiach',
  'Poradenstvo pri zvládaní tlaku a nárokov v práci či škole',
  'Koučing na rozvoj osobných a profesionálnych kompetencií',
  'Psychohygiena a prevencia duševných problémov',
  'Poradenstvo pri závažných životných udalostiach',
  'Podpora resilience a odolnosti',
  'Poradenstvo pri zvládaní traumy a stresových reakcií',
  'Krízové linky a okamžitá psychologická pomoc',
  'Poradenstvo pre LGBTQ+ komunity',
  'Rozvoj empatie a sociálneho povedomia',
  'Koučing pre tímovú spoluprácu a leadership',
  'Poradenstvo pri poruchách príjmu potravy',
  'Podpora duševného zdravia v školách a firmách',
  'Poradenstvo pri závislostiach na technológiách',
  'Edukačné a motivačné programy pre osobný rozvoj',
  'Mentoring a koučing pre študentov a mladých profesionálov',
  'Poradenstvo pri osobnom raste a sebarealizácii',
  'Psychoedukácia pre rodičov a učiteľov',
  'Tvorba a implementácia rozvojových programov',
  'Online kurzy a workshopy z psychológie a osobného rozvoja',
  'Poradenstvo pri zvládaní emocionálnych a behaviorálnych problémov',
  'Poradenstvo pri profesijnom a osobnom plánovaní',
  'Psychologická podpora pre komunity a skupiny',
  'Koučing a mentoring zameraný na zlepšenie výkonu a wellbeing',
];

