export const SOCIALNE_SIETE_A_DIGITALNY_OBSAH: string[] = [
  'Správa sociálnych sietí (Facebook, Instagram, TikTok, LinkedIn, Twitter/X)',
  'Tvorba a plánovanie obsahu',
  'Content marketing a obsahová stratégia',
  'Copywriting a písanie príspevkov',
  'Grafický dizajn pre sociálne médiá',
  'Video tvorba a editácia',
  'Fotografia a vizuálny obsah',
  'Reels, Shorts a krátke video formáty',
  'Plánovanie a tvorba kampaní',
  'Influencer marketing a spolupráce',
  'Analytika a reporting výkonnosti obsahu',
  'Správa a optimalizácia profilov',
  'Komunitný manažment a interakcia s fanúšikmi',
  'Budovanie značky a online reputácie',
  'Social media advertising a platené kampane',
  'SEO pre sociálne siete a obsah',
  'Tvorba interaktívneho obsahu (ankety, kvízy, otázky)',
  'Live streaming a eventy online',
  'Digitálne príbehy a storytelling',
  'Content repurposing a recyklácia obsahu',
  'Plánovanie a tvorba editorial kalendárov',
  'Marketing automation a plánovanie príspevkov',
  'Podcasty a audio obsah',
  'Tvorba meme a virálneho obsahu',
  'Vytváranie hashtag stratégií a trendového obsahu',
  'Správa reklamných kampaní a boostovanie príspevkov',
  'Online PR a spolupráca s digitálnymi médiami',
  'Vytváranie infografík a vizualizácií dát',
  'E-mail marketing a newsletter obsah',
  'Kreatívne koncepty a vizuálna identita',
  'Tvorba online kurzov a tutoriálov',
  'Digitálne výzvy a engagement kampane',
  'Monitoring a analýza konkurencie',
  'Vývoj a správa webového obsahu',
  'Digitálne produkty a downloadable content',
  'Personal branding a správa osobného profilu',
  'Vytváranie interaktívnych príbehov (storytelling apps)',
  'Obsah pre mobilné aplikácie a platformy',
  'Tvorba virálneho a zdieľateľného obsahu',
  'Strategické plánovanie a konzultácie obsahu',
  'Digitálna kreativita a experimentovanie s formátmi',
  'Správa influencer kampaní a spoluprác',
  'Engagement strategie a zapájanie komunity',
  'Analýza trendov a sociálnych signálov',
  'Tvorba GIF, animácií a vizuálnych efektov',
  'Digitálne marketingové kampane a výzvy',
  'Správa online komunity a fanbase growth',
  'Edukácia a školenia v oblasti digitálneho obsahu',
  'Vytváranie content guidelines a brand manuálov',
  'Social listening a monitorovanie zmienok značky',
  'Kreatívne výzvy a user-generated content',
  'Tvorba digitálneho portfólia a prezentácií',
  'Obsah pre e-commerce platformy a produktové kampane',
  'Tvorba video sérií a webseriálov',
  'Digitálna stratégia a konzultácie pre firmy',
  'Personalizovaný obsah a targeting audience',
  'Tvorba vizuálneho obsahu pre reklamu',
  'Optimalizácia obsahu pre rôzne platformy',
  'Správa online reputácie a recenzií',
  'Tvorba interaktívnych príspevkov a ankiet',
  'Digitálne storytelling kampane',
  'Obsah pre edukatívne a instruktážne účely',
  'Správa obsahu počas eventov a konferencií',
  'Vývoj vizuálnej identity a grafických šablón',
  'Marketing a propagácia cez digitálne kanály',
  'Tvorba multimediálneho obsahu a digitálnych assetov',
  'Podpora predaja cez digitálny obsah a kampane',
  'Digitálne reklamy a retargeting kampane',
  'Využitie AI a nástrojov pre tvorbu obsahu',
  'Správa blogov a online publikácií',
  'Obsah pre interaktívne platformy a webové aplikácie',
  'Digitálne projekty a online kreatívne kampane',
  'Vytváranie trendového a aktuálneho obsahu',
  'Strategické plánovanie influencer a ambasádorských kampaní',
  'Reporting a vyhodnocovanie online aktivít',
  'Tvorba vizuálnych a textových materiálov pre sociálne siete',
  'Obsah pre mobilné a desktop platformy',
  'Optimalizácia digitálneho obsahu pre engagement a reach',
  'Správa digitálnych kanálov a profilov pre značky',
  'Digitálne stratégie pre storytelling a brand awareness',
  'Tvorba obsahových kampaní pre komunitu a fanúšikov',
  'Vytváranie vizuálnych, textových a multimediálnych assetov',
  'Edukačné digitálne projekty a online tutoriály',
];

