export const TECHNICKA_PODPORA_A_SERVIS: string[] = [
  'Hardvérová diagnostika a oprava počítačov',
  'Oprava notebookov a tabletov',
  'Servis a údržba serverov',
  'Výmena komponentov (RAM, HDD, SSD, grafická karta)',
  'Inštalácia a aktualizácia softvéru',
  'Odstraňovanie vírusov a malvéru',
  'Sieťová diagnostika a konfigurácia',
  'Podpora pri pripojení k internetu a Wi-Fi',
  'Nastavenie a konfigurácia routerov a modemov',
  'Podpora pre operačné systémy (Windows, macOS, Linux)',
  'Softvérová podpora pre aplikácie a programy',
  'Podpora cloudových služieb (Google Drive, OneDrive, Dropbox)',
  'Zálohovanie a obnova dát',
  'Správa a obnova databáz',
  'Správa firemných IT systémov',
  'Podpora pre mobilné zariadenia (smartfóny, tablety)',
  'Servis tlačiarní a multifunkčných zariadení',
  'Nastavenie periférií (myši, klávesnice, monitory)',
  'Podpora pre audio a video zariadenia',
  'Podpora pre herné konzoly',
  'Vzdialená technická podpora',
  'Helpdesk služby',
  'IT poradenstvo a konzultácie',
  'Implementácia softvérových riešení',
  'Upgrade a optimalizácia počítačových systémov',
  'Bezpečnostné poradenstvo a antivírusová ochrana',
  'Monitoring IT infraštruktúry',
  'Servis a údržba serverovní',
  'Podpora pre firemné aplikácie',
  'Správa používateľských účtov a prístupových práv',
  'Nastavenie e-mailových systémov',
  'Podpora pre videokonferencie a komunikáciu',
  'Riadenie a konfigurácia sieťových zariadení',
  'Podpora pri virtualizácii (VMware, Hyper-V)',
  'Oprava a servis elektronických zariadení',
  'Preventívna údržba IT zariadení',
  'Návrh a implementácia IT riešení',
  'Technická dokumentácia a návody',
  'Školenia a konzultácie pre používateľov',
  'Podpora pri migrácii dát',
  'Optimalizácia výkonu počítačov a serverov',
  'Podpora pri IT bezpečnosti a ochrane dát',
  'Správa firewallov a bezpečnostných zariadení',
  'Podpora pre databázové systémy',
  'Audit IT infraštruktúry',
  'Poradenstvo pri výbere hardvéru a softvéru',
  'Servis a podpora sieťových tlačiarní',
  'Nastavenie a správa VPN',
  'Riešenie problémov s kompatibilitou softvéru',
  'Integrácia nových zariadení do siete',
  'Podpora pri cloudových riešeniach (AWS, Azure, Google Cloud)',
  'Technická podpora pre e-commerce systémy',
  'IT helpdesk pre domácnosti aj firmy',
  'Konfigurácia a správa NAS zariadení',
  'Obnova a zabezpečenie dát po havárii',
  'Servis a podpora bezpečnostných systémov (kamery, alarmy)',
  'Optimalizácia IT procesov',
  'Podpora pri softvérovej integrácii',
  'Riadenie IT projektov a implementácií',
  'Testovanie a ladenie softvéru',
  'Podpora pre mobilné a webové aplikácie',
  'Servis a údržba elektronických periférií',
  'Podpora pri nastavení smart domácnosti',
  'Riešenie problémov s periférnymi zariadeniami',
  'Technická asistencia pri školeniach a workshopoch',
  'Podpora pri online platformách a službách',
  'Analýza a riešenie IT problémov',
  'Sledovanie a správa IT infraštruktúry',
  'Poradenstvo pri IT investíciách a nákupoch',
  'Podpora pre enterprise systémy a ERP',
  'Servis a údržba multimediálnych zariadení',
  'Podpora pre videoprodukciu a streaming systémy',
  'Nastavenie a podpora IoT zariadení',
  'Správa a údržba cloudových aplikácií',
  'Konzultácie pri IT bezpečnostných opatreniach',
  'Servis a oprava elektroniky pre domácnosti aj firmy',
  'Preventívna kontrola a aktualizácia systémov',
  'Technická podpora pre vzdelávacie inštitúcie a školy',
  'Podpora pri digitálnej transformácii organizácií',
  'Podpora pri softvérových licencoch a aktiváciách',
  'Riešenie incidentov a urgentných problémov',
  'Vzdialené monitorovanie a riešenie problémov',
];

