export const DOPRAVA_A_LOGISTIKA: string[] = [
  'Riadenie dopravy',
  'Plánovanie trás',
  'Optimalizácia dodávok',
  'Skladové hospodárstvo',
  'Správa zásob',
  'Inventarizácia',
  'Príjem tovaru',
  'Výdaj tovaru',
  'Manipulácia s tovarom',
  'Balenie a označovanie',
  'Nakladanie a vykladanie tovaru',
  'Expedičné služby',
  'Preprava zásielok',
  'Kurýrne služby',
  'Osobná preprava',
  'Nákladná doprava',
  'Medzinárodná preprava',
  'Domáca preprava',
  'Doručovanie balíkov',
  'Freight forwarding',
  'Colné služby',
  'Dokumentácia preprav',
  'Sledovanie zásielok',
  'Riadenie flotily',
  'Údržba vozidiel',
  'Servis a opravy dopravných prostriedkov',
  'Tankovanie a kontrola vozidiel',
  'Logistický planning',
  'Supply chain management',
  'Riadenie dodávateľského reťazca',
  'Prijímanie objednávok',
  'Distribúcia tovaru',
  'Multi-modal transport',
  'Intermodálna doprava',
  'Železničná doprava',
  'Letecká doprava',
  'Námorná doprava',
  'Cestná doprava',
  'Automobilová logistika',
  'Posielanie paliet',
  'Tovarové sklady',
  'Chladené sklady',
  'Skladovanie nebezpečného tovaru',
  'Riadenie zásob v reálnom čase',
  'Balíková logistika',
  'E-commerce logistika',
  'Just-in-time dodávky',
  'Cross-docking',
  'Konsolidácia zásielok',
  'Reverzná logistika',
  'Tracking a tracing zásielok',
  'Automatizácia skladu',
  'Používanie WMS systémov',
  'Používanie TMS systémov',
  'RFID a čiarové kódy',
  'Plánovanie kapacity skladu',
  'Zabezpečenie skladu',
  'Manipulačná technika',
  'Vysokozdvižné vozíky',
  'Paletové vozíky',
  'Dopravné rampy a doky',
  'Bezpečnostné protokoly pri preprave',
  'Školenie vodičov',
  'Dodržiavanie dopravných predpisov',
  'Preprava nebezpečného tovaru (ADR)',
  'Handling krehkého tovaru',
  'Nakladacie a vykladacie operácie',
  'Optimalizácia nákladového vozidla',
  'Sledovanie spotreby paliva',
  'Green logistics / ekologická doprava',
  'Analýza nákladov dopravy',
  'Reporting a KPI dopravy',
  'Projektovanie logistických sietí',
  'Strategické plánovanie dodávok',
  'Outsourcing dopravy a logistiky',
  'Tracking a reporting zásielok klientom',
  'Integrácia logistických systémov',
  'Forecasting dopytu a zásob',
  'Skladové audity a kontrola kvality',
  'Zabezpečenie balenia proti poškodeniu',
  'Oprava a údržba balení',
  'Tvorba dopravných plánov',
  'Optimalizácia trás pre viaceré vozidlá',
  'Riadenie rizík v logistike',
  'Crisis management v doprave',
  'Expresné dodávky',
  'Nočné doručovanie',
  'Last mile delivery',
  'Fulfillment služby',
  'Vývoj a implementácia logistického softvéru',
  'Simulácia a modelovanie logistických procesov',
  'Digitalizácia dodávateľského reťazca',
  'Blockchain v logistike',
  'IoT a smart logistics',
  'Inteligentné sklady',
  'Automatizované dopravné systémy',
  'Drony pre doručovanie',
  'Autonómne vozidlá',
  'Predikcia dopravných zápch a oneskorení',
  'Práca s logistickými dátami',
  'Optimalizácia skladových procesov',
  'Zlepšovanie efektivity dodávok',
  'Reporting nákladov a času dodania',
  'Školenie logistického personálu',
  'Certifikácia a compliance v logistike',
  'Analýza dopravných trendov',
  'Benchmarking logistických procesov',
  'Medzinárodná logistika a compliance',
  'Colné deklarácie a dokumentácia',
  'Optimalizácia intermodálnych transportov',
  'Riadenie skladových zásob v reálnom čase',
  'Servis a podpora logistických systémov',
];

