export const CESTOVANIE_A_ZAZITKY: string[] = [
  'Organizovanie ciest a výletov',
  'Individuálne cestovanie',
  'Skupinové cestovanie',
  'Rodinné výlety',
  'Dobrodružné cestovanie',
  'Backpacking',
  'Road tripy',
  'Plavby a výletné lode',
  'Letné dovolenky',
  'Zimné dovolenky',
  'Lyžiarske zájazdy',
  'Snowboardové zájazdy',
  'Wellness a spa pobyty',
  'Relaxačné pobyty',
  'Exotické destinácie',
  'Kultúrne a historické cestovanie',
  'Návšteva pamiatok',
  'Múzeá a galérie',
  'Festivaly a lokálne podujatia',
  'Gastronomické cestovanie',
  'Ochutnávky jedál a vín',
  'Tematické výlety',
  'Prírodné parky a rezervácie',
  'Turistika',
  'Horolezectvo',
  'Trekking',
  'Camping',
  'Stanovanie a bivakovanie',
  'Outdoor aktivity',
  'Vodné športy',
  'Rafting',
  'Kajakovanie',
  'Potápanie',
  'Surfovanie',
  'Plávanie a šnorchlovanie',
  'Cyklistika a MTB',
  'Jazda na koni',
  'Dobrodružné športy',
  'Paragliding',
  'Bungee jumping',
  'Skydiving',
  'Ski touring',
  'Fotografovanie a dokumentovanie ciest',
  'Tvorba cestovateľských blogov a vlogov',
  'Publikovanie cestovateľských reportáží',
  'Poradenstvo pri plánovaní ciest',
  'Rezervácie ubytovania a dopravy',
  'Letisková a dopravná asistencia',
  'Poistenie a bezpečnostné služby',
  'Cestovanie s domácimi zvieratami',
  'Udržateľné a ekologické cestovanie',
  'Lokálne skúsenosti a zážitky',
  'Workshopy a kurzy v zahraničí',
  'Jazykové pobyty',
  'Dobrovoľnícke cestovanie',
  'Kultúrna výmena',
  'Roadshow a tematické exkurzie',
  'Urban exploration',
  'Mesto a architektúra',
  'Pešie prehliadky miest',
  'Street art a lokálne umenie',
  'Fototúry a fotografické expedície',
  'Nočný život a zábava v destináciách',
  'Lokálne trhy a remeslá',
  'Tradičné festivaly a oslavy',
  'Cestovanie s deťmi',
  'Bezpečnostné tipy a poradenstvo',
  'Cestovanie pre seniorov',
  'Skupinové zájazdy a tour operátori',
  'Adventure travel agentúry',
  'Prírodné rezervácie a safari',
  'Pozorovanie zvierat',
  'Birdwatching',
  'Ekoturistika',
  'Camping v prírode',
  'Pikniky a outdoor aktivity',
  'Turistické chodníky a značenie',
  'Orientácia v teréne a mapovanie',
  'Geocaching',
  'Výpravy za zážitkami',
  'Tematické cesty (gastronómia, história, šport)',
  'Work and travel programy',
  'Cestovanie s fotografovaním',
  'Dokumentárne projekty z ciest',
  'Tvorba itinerárov a plánovanie trás',
  'Organizácia skupinových zážitkov',
  'Eventové cestovanie (festivaly, koncerty)',
  'Kurzy a tréningy v zahraničí',
  'Jazykové a kultúrne výmeny',
  'Tvorba cestovateľských aplikácií',
  'Virtuálne cestovanie a 360° zážitky',
  'Cestovanie vlakom, autobusom, autom',
  'Letiskové transfery a doprava',
  'Cestovanie lodnou dopravou',
  'Hiking a trekking expedície',
  'Expedície do hôr a odľahlých oblastí',
  'Ski a snowboard zážitky',
  'Surfing a vodné športy',
  'Adventure športy a adrenalínové zážitky',
  'Cestovanie pre wellness a relax',
  'Kúpeľné a liečebné pobyty',
  'Lokálne dobrodružstvá a outdoor aktivity',
  'Fotografovanie prírody a krajiny',
  'Dokumentovanie cestovateľských zážitkov',
  'Sprievodcovanie turistov',
  'Tvorba cestovateľských itinerárov',
  'Predaj cestovateľských zážitkov',
  'Booking a rezervácie zážitkov',
  'Organizovanie workshopov na cestách',
  'Kurzy varenia a remesiel v zahraničí',
  'Tvorba zážitkových balíčkov',
  'Správa cestovateľských skupín',
  'Safety a risk management na cestách',
  'Travel consulting a poradenstvo',
  'Lokálne prispôsobené zážitky a toury',
  'Adventure trips a outdoor expedície',
  'Team-buildingové zájazdy a aktivity',
  'Firemné incentive pobyty',
  'Kombinované turistické a športové zážitky',
  'Environmentálne a udržateľné cestovanie',
  'Ochrana prírody pri cestovaní',
  'Vzdelávacie cestovné programy',
  'Kultúrna a historická edukácia počas ciest',
  'Cestovanie s fotografovaním a video dokumentáciou',
  'Storytelling z ciest',
  'Tvorba travel vlogov a blogov',
  'Publikovanie cestovateľských článkov a reportáží',
  'Správa sociálnych médií z ciest',
  'Organizácia a vedenie zážitkových tourov',
];

