export const DOMACA_VYUKA_A_TUTORING: string[] = [
  'Individuálne doučovanie',
  'Skupinové doučovanie',
  'Predmetové doučovanie (matematika, fyzika, jazyky, atď.)',
  'Online tutoring a videolekcie',
  'Príprava na skúšky a testy',
  'Príprava na maturitu a prijímacie skúšky',
  'Príprava na medzinárodné jazykové skúšky (TOEFL, IELTS, DELF, atď.)',
  'Špeciálne vzdelávanie (dyslexia, ADHD, špeciálne potreby)',
  'Mentoring a akademické poradenstvo',
  'Rozvoj študijných zručností',
  'Čítanie a písanie pre deti',
  'Rozvoj kritického myslenia',
  'Práca s učebnicami a vzdelávacími materiálmi',
  'Vyučovanie programovania a IT zručností',
  'Vyučovanie umeleckých a kreatívnych predmetov',
  'Doučovanie hudby a hudobnej teórie',
  'Príprava projektov a domácich úloh',
  'E-learningové platformy a kurzy',
  'Výučba jazykov (angličtina, nemčina, španielčina, atď.)',
  'Konverzačné hodiny a jazyková prax',
  'Rozvoj komunikačných zručností',
  'Príprava prezentácií a písomných prác',
  'Testovanie a hodnotenie pokroku',
  'Edukačné hry a aktivity pre deti',
  'Príprava na olympiády a súťaže',
  'Tvorba individuálnych vzdelávacích plánov',
  'Vzdelávacie workshopy a semináre',
  'Poradenstvo pre rodičov pri domácom vzdelávaní',
  'Študijné techniky a time management',
  'Rozvoj logického a analytického myslenia',
  'Príprava na vysokú školu a prijímacie konania',
  'Doučovanie praktických zručností a remesiel',
  'Online tutoriály a video lekcie',
  'Vedenie študijných skupín a online komunít',
  'Personalizované vzdelávacie programy',
  'Mentoring a podpora motivácie',
  'Príprava portfólií a projektových prác',
  'Edukačné konzultácie pre študentov aj dospelých',
  'Výučba soft skills a životných zručností',
  'Kurzy kreatívneho písania a literatúry',
  'Podpora pri vedeckých a výskumných projektoch',
  'Online platformy pre domáce vzdelávanie',
  'Interaktívne lekcie a cvičenia',
  'Vyučovanie matematiky a prírodovedných predmetov',
  'Rozvoj pamäťových a študijných techník',
  'Doučovanie pre študentov so špeciálnymi potrebami',
  'Tvorba vzdelávacích materiálov a pracovných listov',
  'Koučing a mentoring študijného pokroku',
  'Rozvoj kreativity a umeleckých zručností',
  'Vzdelávacie programy pre dospelých a profesijné kurzy',
  'Príprava na jazykové certifikáty a skúšky',
  'Online webináre a live lekcie',
  'Tvorba testov a hodnotiacich nástrojov',
  'Príprava na súťaže a olympiády',
  'Podpora samostatného štúdia a učenia',
  'Interaktívne vzdelávacie aplikácie',
  'Edukačné hry a simulácie',
  'Rozvoj analytického a kritického myslenia',
  'Doučovanie technických predmetov (programovanie, inžinierstvo)',
  'Kreatívne a projektové vzdelávanie',
  'Mentoring pre rozvoj osobného a akademického potenciálu',
  'Hodnotenie výkonu a spätná väzba',
  'Príprava individuálnych študijných plánov',
  'Online a offline tutoringové služby',
  'Kurzy soft skills pre študentov a profesionálov',
  'Rozvoj prezentácie a verejného vystupovania',
  'Využitie multimédií a digitálnych nástrojov pri učení',
  'Podpora pri rozvoji jazykových a komunikačných zručností',
  'Edukačné konzultácie a poradenstvo pre rodičov a študentov',
];

