export const DOBROVOLNICTVO_A_KOMUNITA: string[] = [
  'Organizovanie komunitných akcií',
  'Organizovanie dobrovoľníckych aktivít',
  'Koordinácia dobrovoľníkov',
  'Nábory dobrovoľníkov',
  'Školenia a tréningy pre dobrovoľníkov',
  'Mentoring a podpora členov komunity',
  'Sociálna pomoc seniorom',
  'Sociálna pomoc deťom',
  'Podpora rodín v núdzi',
  'Pomoc osobám so zdravotným postihnutím',
  'Pomoc bezdomovcom',
  'Pomoc utečencom a migrantom',
  'Organizovanie zbierok a darov',
  'Distribúcia potravín a základných potrieb',
  'Organizovanie komunitných jedál',
  'Koordinácia miestnych projektov',
  'Zapájanie komunity do projektov',
  'Vedenie komunitných centier',
  'Organizovanie workshopov a vzdelávacích aktivít',
  'Kultúrne a spoločenské podujatia pre komunitu',
  'Ochrana životného prostredia v komunite',
  'Údržba verejných priestranstiev',
  'Záhradnícke a komunitné projekty',
  'Usporiadanie komunitných športových aktivít',
  'Organizovanie športových turnajov',
  'Podpora lokálnych iniciatív',
  'Podpora malých podnikov a remesiel',
  'Koordinácia crowdfundingu a komunitného financovania',
  'Sociálne poradenstvo',
  'Právna pomoc v komunitách',
  'Mediácia a riešenie konfliktov',
  'Mentoring mládeže',
  'Organizovanie letných táborov',
  'Programy pre deti a mládež',
  'Programy pre seniorov',
  'Interkultúrne aktivity',
  'Podpora dobrovoľníckych sietí',
  'Networking komunitných lídrov',
  'Tvorba informačných kampaní',
  'Vedenie sociálnych projektov',
  'Monitoring a hodnotenie projektov',
  'Dokumentovanie dobrovoľníckych aktivít',
  'Organizovanie fundraisingových akcií',
  'Koordinácia partnerstiev s firmami a organizáciami',
  'Poradenstvo v oblasti komunitného rozvoja',
  'Digitálne komunitné platformy',
  'Správa online skupín a fór',
  'Online mentoring a tutoring',
  'Podpora vzdelávania a e-learningu',
  'Zabezpečenie inklúzie a rovnosti v komunite',
  'Podpora zdravotnej osvetovej činnosti',
  'Organizovanie kultúrnych workshopov',
  'Organizovanie umeleckých aktivít pre komunitu',
  'Podpora športových aktivít a klubov',
  'Organizovanie charitatívnych koncertov a vystúpení',
  'Podpora miestnych festivalov a trhov',
  'Rozvoj dobrovoľníckych programov pre firmy',
  'Programy firemného dobrovoľníctva',
  'Krízová pomoc a humanitárna podpora',
  'Spolupráca s neziskovými organizáciami',
  'Spolupráca s mestskou samosprávou',
  'Vzdelávacie kampane o udržateľnom rozvoji',
  'Organizovanie verejných prednášok a seminárov',
  'Tvorba materiálov a publikácií pre komunitu',
  'Poradenstvo pre vytváranie lokálnych politík',
  'Aktivity pre podporu duševného zdravia v komunite',
  'Podpora inkluzívnych aktivít pre marginalizované skupiny',
  'Koordinácia dobrovoľníckych tímov pri podujatiach',
  'Organizovanie dobrovoľníckych brigád',
  'Zapojiť komunitu do rozhodovacích procesov',
  'Motivácia a udržanie dobrovoľníkov',
  'Tvorba komunitných databáz a registrácií',
  'Reporting a dokumentácia aktivít',
  'Organizovanie dobrovoľníckych odmien a uznaní',
  'Budovanie komunitnej identity',
  'Rozvoj občianskej angažovanosti',
  'Aktivizácia miestnych lídrov a aktivistov',
  'Podpora miestnych kultúrnych a umeleckých iniciatív',
  'Poradenstvo v oblasti sociálnej inklúzie',
  'Podpora medzigeneračných aktivít',
  'Organizovanie komunitných dialógov a stretnutí',
  'Prevencia sociálnej izolácie',
  'Koordinácia humanitárnej pomoci v krízových situáciách',
  'Distribúcia humanitárnych zásob',
  'Spolupráca s dobrovoľníckymi sieťami medzinárodne',
  'Rozvoj miestnych dobrovoľníckych infraštruktúr',
  'Tvorba stratégií rozvoja komunity',
  'Analýza potrieb komunity',
  'Hodnotenie dopadu dobrovoľníckych programov',
  'Edukácia o občianskych právach a povinnostiach',
  'Podpora participácie občanov na rozhodovaní',
  'Organizovanie komunitných rád a komisií',
  'Spolupráca s miestnymi školami a vzdelávacími inštitúciami',
  'Zapájanie komunity do environmentálnych projektov',
  'Tvorba a správa komunitných knižníc a zdrojov',
  'Vedenie komunitných archívov a dokumentácie',
];

