# Generated by Django 4.2.7 on 2026-06-22 19:16

from django.db import migrations, models
import messaging.models
import messaging.storage
import swaply.validators


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_message_offer_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=messaging.storage.get_message_image_storage, upload_to=messaging.models.message_image_upload_to, validators=[swaply.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=messaging.storage.get_message_image_storage, upload_to=messaging.models.message_thumbnail_upload_to),
        ),
    ]
