name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Build frontend
      working-directory: ./frontend
      run: npm run build
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Django migrations
      working-directory: ./backend
      run: |
        python manage.py migrate --settings=swaply.settings_production
        python manage.py collectstatic --noinput --settings=swaply.settings_production
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        
    - name: Deploy to PythonAnywhere
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PYTHONANYWHERE_HOST }}
        username: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        key: ${{ secrets.PYTHONANYWHERE_SSH_KEY }}
        script: |
          cd /home/${{ secrets.PYTHONANYWHERE_USERNAME }}/svap
          git pull origin main
          cd backend
          source venv/bin/activate
          python manage.py migrate --settings=swaply.settings_production
          python manage.py collectstatic --noinput --settings=swaply.settings_production
          # Copy frontend build to frontend directory
          rm -rf ../frontend/*
          cp -r ../../frontend/out/* ../frontend/
          # Reload web app (if using uWSGI)
          touch /var/www/${{ secrets.PYTHONANYWHERE_USERNAME }}_pythonanywhere_com_wsgi.py
